
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class AbstractGroup : Luban.BeanBase
{
    public AbstractGroup(JSONNode _buf) 
    {
        { if(!_buf["group_id"].IsString) { throw new SerializationException(); }  GroupId = _buf["group_id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["icon_path"].IsString) { throw new SerializationException(); }  IconPath = _buf["icon_path"]; }
        { if(!_buf["max_stage"].IsNumber) { throw new SerializationException(); }  MaxStage = _buf["max_stage"]; }
        { var __json0 = _buf["tags"]; if(!__json0.IsArray) { throw new SerializationException(); } Tags = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Tags.Add(__v0); }   }
        { var __json0 = _buf["unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  UnlockConds.Add(__v0); }   }
        { if(!_buf["retired_after_max"].IsBoolean) { throw new SerializationException(); }  RetiredAfterMax = _buf["retired_after_max"]; }
    }

    public static AbstractGroup DeserializeAbstractGroup(JSONNode _buf)
    {
        return new demo.AbstractGroup(_buf);
    }

    /// <summary>
    /// 团体ID
    /// </summary>
    public string GroupId;
    /// <summary>
    /// 名称
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 简介
    /// </summary>
    public string Desc;
    /// <summary>
    /// 图标
    /// </summary>
    public string IconPath;
    /// <summary>
    /// 最高阶段
    /// </summary>
    public int MaxStage;
    /// <summary>
    /// 标签
    /// </summary>
    public System.Collections.Generic.List<string> Tags;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> UnlockConds;
    /// <summary>
    /// 打满后退役
    /// </summary>
    public bool RetiredAfterMax;
   
    public const int __ID__ = -364397934;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UnlockConds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "groupId:" + GroupId + ","
        + "displayName:" + DisplayName + ","
        + "desc:" + Desc + ","
        + "iconPath:" + IconPath + ","
        + "maxStage:" + MaxStage + ","
        + "tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "unlockConds:" + Luban.StringUtil.CollectionToString(UnlockConds) + ","
        + "retiredAfterMax:" + RetiredAfterMax + ","
        + "}";
    }
}
}

