
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class AbstractGroupStage : Luban.BeanBase
{
    public AbstractGroupStage(JSONNode _buf) 
    {
        { if(!_buf["group_id"].IsString) { throw new SerializationException(); }  GroupId = _buf["group_id"]; }
        { if(!_buf["stage"].IsNumber) { throw new SerializationException(); }  Stage = _buf["stage"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["appear_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } AppearConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  AppearConds.Add(__v0); }   }
        { if(!_buf["refresh_weight"].IsNumber) { throw new SerializationException(); }  RefreshWeight = _buf["refresh_weight"]; }
        { if(!_buf["dream_theme_id"].IsString) { throw new SerializationException(); }  DreamThemeId = _buf["dream_theme_id"]; }
        { if(!_buf["dream_theme_display_name"].IsString) { throw new SerializationException(); }  DreamThemeDisplayName = _buf["dream_theme_display_name"]; }
        { if(!_buf["difficulty_id"].IsString) { throw new SerializationException(); }  DifficultyId = _buf["difficulty_id"]; }
        { if(!_buf["required_score"].IsNumber) { throw new SerializationException(); }  RequiredScore = _buf["required_score"]; }
        { if(!_buf["core_max_hp"].IsNumber) { throw new SerializationException(); }  CoreMaxHp = _buf["core_max_hp"]; }
        { if(!_buf["player_max_hp"].IsNumber) { throw new SerializationException(); }  PlayerMaxHp = _buf["player_max_hp"]; }
        { if(!_buf["bullet_damage"].IsNumber) { throw new SerializationException(); }  BulletDamage = _buf["bullet_damage"]; }
        { if(!_buf["aoe_damage"].IsNumber) { throw new SerializationException(); }  AoeDamage = _buf["aoe_damage"]; }
        { if(!_buf["projectile_damage"].IsNumber) { throw new SerializationException(); }  ProjectileDamage = _buf["projectile_damage"]; }
        { if(!_buf["reward_preview_desc"].IsString) { throw new SerializationException(); }  RewardPreviewDesc = _buf["reward_preview_desc"]; }
    }

    public static AbstractGroupStage DeserializeAbstractGroupStage(JSONNode _buf)
    {
        return new demo.AbstractGroupStage(_buf);
    }

    /// <summary>
    /// 团体ID
    /// </summary>
    public string GroupId;
    /// <summary>
    /// 阶段
    /// </summary>
    public int Stage;
    /// <summary>
    /// 阶段名
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 说明
    /// </summary>
    public string Desc;
    /// <summary>
    /// 出现条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> AppearConds;
    /// <summary>
    /// 刷新权重
    /// </summary>
    public int RefreshWeight;
    /// <summary>
    /// 主题ID
    /// </summary>
    public string DreamThemeId;
    /// <summary>
    /// 主题名
    /// </summary>
    public string DreamThemeDisplayName;
    /// <summary>
    /// 难度档
    /// </summary>
    public string DifficultyId;
    /// <summary>
    /// 通关分
    /// </summary>
    public int RequiredScore;
    /// <summary>
    /// 核心HP
    /// </summary>
    public int CoreMaxHp;
    /// <summary>
    /// 玩家HP
    /// </summary>
    public int PlayerMaxHp;
    /// <summary>
    /// 弹伤
    /// </summary>
    public int BulletDamage;
    /// <summary>
    /// AOE
    /// </summary>
    public int AoeDamage;
    /// <summary>
    /// 炮弹
    /// </summary>
    public int ProjectileDamage;
    /// <summary>
    /// 奖励预览
    /// </summary>
    public string RewardPreviewDesc;
   
    public const int __ID__ = -848829556;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in AppearConds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "groupId:" + GroupId + ","
        + "stage:" + Stage + ","
        + "displayName:" + DisplayName + ","
        + "desc:" + Desc + ","
        + "appearConds:" + Luban.StringUtil.CollectionToString(AppearConds) + ","
        + "refreshWeight:" + RefreshWeight + ","
        + "dreamThemeId:" + DreamThemeId + ","
        + "dreamThemeDisplayName:" + DreamThemeDisplayName + ","
        + "difficultyId:" + DifficultyId + ","
        + "requiredScore:" + RequiredScore + ","
        + "coreMaxHp:" + CoreMaxHp + ","
        + "playerMaxHp:" + PlayerMaxHp + ","
        + "bulletDamage:" + BulletDamage + ","
        + "aoeDamage:" + AoeDamage + ","
        + "projectileDamage:" + ProjectileDamage + ","
        + "rewardPreviewDesc:" + RewardPreviewDesc + ","
        + "}";
    }
}
}

