
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class AlchemyTool : Luban.BeanBase
{
    public AlchemyTool(JSONNode _buf) 
    {
        { if(!_buf["tool_id"].IsString) { throw new SerializationException(); }  ToolId = _buf["tool_id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { var __json0 = _buf["bonus_virtues"]; if(!__json0.IsArray) { throw new SerializationException(); } BonusVirtues = new System.Collections.Generic.List<demo.AlchemyVirtueValue>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.AlchemyVirtueValue __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.AlchemyVirtueValue.DeserializeAlchemyVirtueValue(__e0);  }  BonusVirtues.Add(__v0); }   }
        { var __json0 = _buf["bonus_aspects"]; if(!__json0.IsArray) { throw new SerializationException(); } BonusAspects = new System.Collections.Generic.List<demo.AlchemyAspectValue>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.AlchemyAspectValue __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.AlchemyAspectValue.DeserializeAlchemyAspectValue(__e0);  }  BonusAspects.Add(__v0); }   }
        { if(!_buf["extra_material_slots"].IsNumber) { throw new SerializationException(); }  ExtraMaterialSlots = _buf["extra_material_slots"]; }
    }

    public static AlchemyTool DeserializeAlchemyTool(JSONNode _buf)
    {
        return new demo.AlchemyTool(_buf);
    }

    public string ToolId;
    public string DisplayName;
    public System.Collections.Generic.List<demo.AlchemyVirtueValue> BonusVirtues;
    public System.Collections.Generic.List<demo.AlchemyAspectValue> BonusAspects;
    /// <summary>
    /// 额外素材格
    /// </summary>
    public int ExtraMaterialSlots;
   
    public const int __ID__ = -1889873266;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in BonusVirtues) { _e?.ResolveRef(tables); }
        foreach (var _e in BonusAspects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "toolId:" + ToolId + ","
        + "displayName:" + DisplayName + ","
        + "bonusVirtues:" + Luban.StringUtil.CollectionToString(BonusVirtues) + ","
        + "bonusAspects:" + Luban.StringUtil.CollectionToString(BonusAspects) + ","
        + "extraMaterialSlots:" + ExtraMaterialSlots + ","
        + "}";
    }
}
}

