
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class AlchemyProgress : Luban.BeanBase
{
    public AlchemyProgress(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["extra_material_slots"].IsNumber) { throw new SerializationException(); }  ExtraMaterialSlots = _buf["extra_material_slots"]; }
        { if(!_buf["unlock_mode"].IsNumber) { throw new SerializationException(); }  UnlockMode = (demo.EForgeUnlockMode)_buf["unlock_mode"].AsInt; }
        { if(!_buf["unlock_param"].IsString) { throw new SerializationException(); }  UnlockParam = _buf["unlock_param"]; }
        { if(!_buf["unlock_item_min_count"].IsNumber) { throw new SerializationException(); }  UnlockItemMinCount = _buf["unlock_item_min_count"]; }
    }

    public static AlchemyProgress DeserializeAlchemyProgress(JSONNode _buf)
    {
        return new demo.AlchemyProgress(_buf);
    }

    public int Level;
    public string DisplayName;
    /// <summary>
    /// 在炉子基础上追加的素材格
    /// </summary>
    public int ExtraMaterialSlots;
    public demo.EForgeUnlockMode UnlockMode;
    public string UnlockParam;
    public long UnlockItemMinCount;
   
    public const int __ID__ = -393232349;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "displayName:" + DisplayName + ","
        + "extraMaterialSlots:" + ExtraMaterialSlots + ","
        + "unlockMode:" + UnlockMode + ","
        + "unlockParam:" + UnlockParam + ","
        + "unlockItemMinCount:" + UnlockItemMinCount + ","
        + "}";
    }
}
}

