
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class AreaVariantInfo : Luban.BeanBase
{
    public AreaVariantInfo(JSONNode _buf) 
    {
        { if(!_buf["var_id"].IsString) { throw new SerializationException(); }  VarId = _buf["var_id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["logic_area_id"].IsString) { throw new SerializationException(); }  LogicAreaId = _buf["logic_area_id"]; }
        { if(!_buf["show_in_map"].IsBoolean) { throw new SerializationException(); }  ShowInMap = _buf["show_in_map"]; }
        { var __json0 = _buf["show_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } ShowConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  ShowConds.Add(__v0); }   }
        { if(!_buf["scene_name"].IsString) { throw new SerializationException(); }  SceneName = _buf["scene_name"]; }
        { if(!_buf["thumb_map"].IsString) { throw new SerializationException(); }  ThumbMap = _buf["thumb_map"]; }
        { if(!_buf["is_secret_base"].IsBoolean) { throw new SerializationException(); }  IsSecretBase = _buf["is_secret_base"]; }
    }

    public static AreaVariantInfo DeserializeAreaVariantInfo(JSONNode _buf)
    {
        return new demo.AreaVariantInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public string VarId;
    /// <summary>
    /// 名称
    /// </summary>
    public string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
    /// <summary>
    /// 逻辑区域id
    /// </summary>
    public string LogicAreaId;
    /// <summary>
    /// 是否显示
    /// </summary>
    public bool ShowInMap;
    /// <summary>
    /// 显示条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> ShowConds;
    /// <summary>
    /// 场景名
    /// </summary>
    public string SceneName;
    /// <summary>
    /// 场景名
    /// </summary>
    public string ThumbMap;
    /// <summary>
    /// 隐秘据点
    /// </summary>
    public bool IsSecretBase;
   
    public const int __ID__ = 1087994331;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in ShowConds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "varId:" + VarId + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "logicAreaId:" + LogicAreaId + ","
        + "showInMap:" + ShowInMap + ","
        + "showConds:" + Luban.StringUtil.CollectionToString(ShowConds) + ","
        + "sceneName:" + SceneName + ","
        + "thumbMap:" + ThumbMap + ","
        + "isSecretBase:" + IsSecretBase + ","
        + "}";
    }
}
}

