
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class AreaOverlayStateInfo : Luban.BeanBase
{
    public AreaOverlayStateInfo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["var_id"].IsString) { throw new SerializationException(); }  VarId = _buf["var_id"]; }
        { if(!_buf["day_period_limit"].IsNumber) { throw new SerializationException(); }  DayPeriodLimit = _buf["day_period_limit"]; }
        { if(!_buf["map_data_name"].IsString) { throw new SerializationException(); }  MapDataName = _buf["map_data_name"]; }
        { if(!_buf["can_teleport"].IsBoolean) { throw new SerializationException(); }  CanTeleport = _buf["can_teleport"]; }
        { if(!_buf["is_home"].IsBoolean) { throw new SerializationException(); }  IsHome = _buf["is_home"]; }
        { if(!_buf["is_secret_base"].IsBoolean) { throw new SerializationException(); }  IsSecretBase = _buf["is_secret_base"]; }
        { if(!_buf["always_alert"].IsBoolean) { throw new SerializationException(); }  AlwaysAlert = _buf["always_alert"]; }
        { if(!_buf["is_civil_area"].IsBoolean) { throw new SerializationException(); }  IsCivilArea = _buf["is_civil_area"]; }
        { if(!_buf["is_danger_area"].IsBoolean) { throw new SerializationException(); }  IsDangerArea = _buf["is_danger_area"]; }
        { if(!_buf["hunting_target"].IsBoolean) { throw new SerializationException(); }  HuntingTarget = _buf["hunting_target"]; }
        { var __json0 = _buf["hunting_unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } HuntingUnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  HuntingUnlockConds.Add(__v0); }   }
        { if(!_buf["procedural_def_id"].IsString) { throw new SerializationException(); }  ProceduralDefId = _buf["procedural_def_id"]; }
        { if(!_buf["peace_zone_mark"].IsBoolean) { throw new SerializationException(); }  PeaceZoneMark = _buf["peace_zone_mark"]; }
    }

    public static AreaOverlayStateInfo DeserializeAreaOverlayStateInfo(JSONNode _buf)
    {
        return new demo.AreaOverlayStateInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public string Id;
    /// <summary>
    /// 名称
    /// </summary>
    public string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
    /// <summary>
    /// id
    /// </summary>
    public string VarId;
    /// <summary>
    /// 时间要求
    /// </summary>
    public int DayPeriodLimit;
    /// <summary>
    /// 数据文件名
    /// </summary>
    public string MapDataName;
    /// <summary>
    /// 传送标记
    /// </summary>
    public bool CanTeleport;
    /// <summary>
    /// home标记
    /// </summary>
    public bool IsHome;
    /// <summary>
    /// 隐秘据点
    /// </summary>
    public bool IsSecretBase;
    /// <summary>
    /// 警戒标记
    /// </summary>
    public bool AlwaysAlert;
    /// <summary>
    /// 是否为文明区域<br/>城镇地带默认进行伪装
    /// </summary>
    public bool IsCivilArea;
    /// <summary>
    /// 是否为危险区域<br/>危险区域无法以人形前往
    /// </summary>
    public bool IsDangerArea;
    /// <summary>
    /// 是否是出击目标
    /// </summary>
    public bool HuntingTarget;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> HuntingUnlockConds;
    /// <summary>
    /// 程序生成定义 id
    /// </summary>
    public string ProceduralDefId;
    /// <summary>
    /// 全图安全区标记
    /// </summary>
    public bool PeaceZoneMark;
   
    public const int __ID__ = 928836711;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in HuntingUnlockConds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "varId:" + VarId + ","
        + "dayPeriodLimit:" + DayPeriodLimit + ","
        + "mapDataName:" + MapDataName + ","
        + "canTeleport:" + CanTeleport + ","
        + "isHome:" + IsHome + ","
        + "isSecretBase:" + IsSecretBase + ","
        + "alwaysAlert:" + AlwaysAlert + ","
        + "isCivilArea:" + IsCivilArea + ","
        + "isDangerArea:" + IsDangerArea + ","
        + "huntingTarget:" + HuntingTarget + ","
        + "huntingUnlockConds:" + Luban.StringUtil.CollectionToString(HuntingUnlockConds) + ","
        + "proceduralDefId:" + ProceduralDefId + ","
        + "peaceZoneMark:" + PeaceZoneMark + ","
        + "}";
    }
}
}

