
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class BodyPartDef : Luban.BeanBase
{
    public BodyPartDef(JSONNode _buf) 
    {
        { if(!_buf["part_id"].IsNumber) { throw new SerializationException(); }  PartId = (demo.EBodyPart)_buf["part_id"].AsInt; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["max_level"].IsNumber) { throw new SerializationException(); }  MaxLevel = _buf["max_level"]; }
        { if(!_buf["base_gear_point"].IsNumber) { throw new SerializationException(); }  BaseGearPoint = _buf["base_gear_point"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["sort_order"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["sort_order"]; }
        { var __json0 = _buf["unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  UnlockConds.Add(__v0); }   }
    }

    public static BodyPartDef DeserializeBodyPartDef(JSONNode _buf)
    {
        return new demo.BodyPartDef(_buf);
    }

    public demo.EBodyPart PartId;
    public string DisplayName;
    public int MaxLevel;
    public int BaseGearPoint;
    public string Icon;
    public int SortOrder;
    public System.Collections.Generic.List<demo.CommonCheckCond> UnlockConds;
   
    public const int __ID__ = 262308709;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UnlockConds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "partId:" + PartId + ","
        + "displayName:" + DisplayName + ","
        + "maxLevel:" + MaxLevel + ","
        + "baseGearPoint:" + BaseGearPoint + ","
        + "icon:" + Icon + ","
        + "sortOrder:" + SortOrder + ","
        + "unlockConds:" + Luban.StringUtil.CollectionToString(UnlockConds) + ","
        + "}";
    }
}
}

