
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class CharacterGiftRule : Luban.BeanBase
{
    public CharacterGiftRule(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["character_key"].IsString) { throw new SerializationException(); }  CharacterKey = _buf["character_key"]; }
        { if(!_buf["item_id"].IsString) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { if(!_buf["favor_value"].IsNumber) { throw new SerializationException(); }  FavorValue = _buf["favor_value"]; }
        { if(!_buf["receive_dialog_id"].IsString) { throw new SerializationException(); }  ReceiveDialogId = _buf["receive_dialog_id"]; }
    }

    public static CharacterGiftRule DeserializeCharacterGiftRule(JSONNode _buf)
    {
        return new demo.CharacterGiftRule(_buf);
    }

    public int Id;
    public string CharacterKey;
    public string ItemId;
    public int FavorValue;
    public string ReceiveDialogId;
   
    public const int __ID__ = 1931054890;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "characterKey:" + CharacterKey + ","
        + "itemId:" + ItemId + ","
        + "favorValue:" + FavorValue + ","
        + "receiveDialogId:" + ReceiveDialogId + ","
        + "}";
    }
}
}

