
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class CharacterFacilitySupervisor : Luban.BeanBase
{
    public CharacterFacilitySupervisor(JSONNode _buf) 
    {
        { if(!_buf["character_key"].IsString) { throw new SerializationException(); }  CharacterKey = _buf["character_key"]; }
        { if(!_buf["can_assign_supervisor"].IsBoolean) { throw new SerializationException(); }  CanAssignSupervisor = _buf["can_assign_supervisor"]; }
        { if(!_buf["sort_order"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["sort_order"]; }
        { if(!_buf["display_title"].IsString) { throw new SerializationException(); }  DisplayTitle = _buf["display_title"]; }
    }

    public static CharacterFacilitySupervisor DeserializeCharacterFacilitySupervisor(JSONNode _buf)
    {
        return new demo.CharacterFacilitySupervisor(_buf);
    }

    /// <summary>
    /// 角色key
    /// </summary>
    public string CharacterKey;
    /// <summary>
    /// 可派驻监工
    /// </summary>
    public bool CanAssignSupervisor;
    /// <summary>
    /// 排序
    /// </summary>
    public int SortOrder;
    /// <summary>
    /// 头衔
    /// </summary>
    public string DisplayTitle;
   
    public const int __ID__ = 1034527689;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "characterKey:" + CharacterKey + ","
        + "canAssignSupervisor:" + CanAssignSupervisor + ","
        + "sortOrder:" + SortOrder + ","
        + "displayTitle:" + DisplayTitle + ","
        + "}";
    }
}
}

