
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class CharacterFavorInfo : Luban.BeanBase
{
    public CharacterFavorInfo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
        { if(!_buf["favor_level"].IsNumber) { throw new SerializationException(); }  FavorLevel = _buf["favor_level"]; }
        { if(!_buf["need_value"].IsNumber) { throw new SerializationException(); }  NeedValue = _buf["need_value"]; }
    }

    public static CharacterFavorInfo DeserializeCharacterFavorInfo(JSONNode _buf)
    {
        return new demo.CharacterFavorInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id;
    /// <summary>
    /// key
    /// </summary>
    public string Key;
    /// <summary>
    /// 好感度等级
    /// </summary>
    public int FavorLevel;
    /// <summary>
    /// 需求好感度
    /// </summary>
    public int NeedValue;
   
    public const int __ID__ = 1683288302;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "key:" + Key + ","
        + "favorLevel:" + FavorLevel + ","
        + "needValue:" + NeedValue + ","
        + "}";
    }
}
}

