
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class CharDreamEntryInfo : Luban.BeanBase
{
    public CharDreamEntryInfo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["character_key"].IsString) { throw new SerializationException(); }  CharacterKey = _buf["character_key"]; }
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
        { if(!_buf["has_locals"].IsString) { throw new SerializationException(); }  HasLocals = _buf["has_locals"]; }
        { if(!_buf["no_locals"].IsString) { throw new SerializationException(); }  NoLocals = _buf["no_locals"]; }
    }

    public static CharDreamEntryInfo DeserializeCharDreamEntryInfo(JSONNode _buf)
    {
        return new demo.CharDreamEntryInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id;
    /// <summary>
    /// key
    /// </summary>
    public string CharacterKey;
    /// <summary>
    /// 优先度
    /// </summary>
    public int Priority;
    /// <summary>
    /// 条件：有变量
    /// </summary>
    public string HasLocals;
    /// <summary>
    /// 条件：没有变量
    /// </summary>
    public string NoLocals;
   
    public const int __ID__ = -1990763906;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "characterKey:" + CharacterKey + ","
        + "priority:" + Priority + ","
        + "hasLocals:" + HasLocals + ","
        + "noLocals:" + NoLocals + ","
        + "}";
    }
}
}

