
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public sealed partial class CommonCheckCond : Luban.BeanBase
{
    public CommonCheckCond(JSONNode _buf) 
    {
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (demo.ECommonCheckType)_buf["type"].AsInt; }
        { if(!_buf["param1"].IsNumber) { throw new SerializationException(); }  Param1 = _buf["param1"]; }
        { if(!_buf["param2"].IsNumber) { throw new SerializationException(); }  Param2 = _buf["param2"]; }
        { if(!_buf["param3"].IsNumber) { throw new SerializationException(); }  Param3 = _buf["param3"]; }
        { if(!_buf["param4"].IsNumber) { throw new SerializationException(); }  Param4 = _buf["param4"]; }
        { if(!_buf["param5"].IsString) { throw new SerializationException(); }  Param5 = _buf["param5"]; }
        { if(!_buf["param6"].IsString) { throw new SerializationException(); }  Param6 = _buf["param6"]; }
    }

    public static CommonCheckCond DeserializeCommonCheckCond(JSONNode _buf)
    {
        return new demo.CommonCheckCond(_buf);
    }

    /// <summary>
    /// 类型
    /// </summary>
    public readonly demo.ECommonCheckType Type;
    /// <summary>
    /// p1
    /// </summary>
    public readonly long Param1;
    /// <summary>
    /// p2
    /// </summary>
    public readonly long Param2;
    /// <summary>
    /// p3
    /// </summary>
    public readonly long Param3;
    /// <summary>
    /// p4
    /// </summary>
    public readonly long Param4;
    /// <summary>
    /// p5
    /// </summary>
    public readonly string Param5;
    /// <summary>
    /// p6
    /// </summary>
    public readonly string Param6;
   
    public const int __ID__ = 827564148;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "param1:" + Param1 + ","
        + "param2:" + Param2 + ","
        + "param3:" + Param3 + ","
        + "param4:" + Param4 + ","
        + "param5:" + Param5 + ","
        + "param6:" + Param6 + ","
        + "}";
    }
}
}

