
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class ContainerStackTagRule : Luban.BeanBase
{
    public ContainerStackTagRule(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["container_type"].IsNumber) { throw new SerializationException(); }  ContainerType = (demo.EContainerType)_buf["container_type"].AsInt; }
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
        { var __json0 = _buf["tags"]; if(!__json0.IsArray) { throw new SerializationException(); } Tags = new System.Collections.Generic.List<demo.EItemTag>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.EItemTag __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (demo.EItemTag)__e0.AsInt; }  Tags.Add(__v0); }   }
        { if(!_buf["stack_ratio"].IsNumber) { throw new SerializationException(); }  StackRatio = _buf["stack_ratio"]; }
    }

    public static ContainerStackTagRule DeserializeContainerStackTagRule(JSONNode _buf)
    {
        return new demo.ContainerStackTagRule(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id;
    /// <summary>
    /// container_type
    /// </summary>
    public demo.EContainerType ContainerType;
    /// <summary>
    /// priority
    /// </summary>
    public int Priority;
    /// <summary>
    /// 物品tags全部匹配时应用倍率；空表示容器默认
    /// </summary>
    public System.Collections.Generic.List<demo.EItemTag> Tags;
    /// <summary>
    /// stack_ratio
    /// </summary>
    public float StackRatio;
   
    public const int __ID__ = 58899268;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "containerType:" + ContainerType + ","
        + "priority:" + Priority + ","
        + "tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "stackRatio:" + StackRatio + ","
        + "}";
    }
}
}

