
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class ContainerItemStackOverride : Luban.BeanBase
{
    public ContainerItemStackOverride(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["container_type"].IsNumber) { throw new SerializationException(); }  ContainerType = (demo.EContainerType)_buf["container_type"].AsInt; }
        { if(!_buf["item_id"].IsString) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { if(!_buf["max_stack"].IsNumber) { throw new SerializationException(); }  MaxStack = _buf["max_stack"]; }
    }

    public static ContainerItemStackOverride DeserializeContainerItemStackOverride(JSONNode _buf)
    {
        return new demo.ContainerItemStackOverride(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id;
    /// <summary>
    /// container_type
    /// </summary>
    public demo.EContainerType ContainerType;
    /// <summary>
    /// item_id
    /// </summary>
    public string ItemId;
    /// <summary>
    /// max_stack
    /// </summary>
    public int MaxStack;
   
    public const int __ID__ = 1861957291;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "containerType:" + ContainerType + ","
        + "itemId:" + ItemId + ","
        + "maxStack:" + MaxStack + ","
        + "}";
    }
}
}

