
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class CultTechNodeLevel : Luban.BeanBase
{
    public CultTechNodeLevel(JSONNode _buf) 
    {
        { if(!_buf["node_id"].IsNumber) { throw new SerializationException(); }  NodeId = _buf["node_id"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { var __json0 = _buf["prereq_node_ids"]; if(!__json0.IsArray) { throw new SerializationException(); } PrereqNodeIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  PrereqNodeIds.Add(__v0); }   }
        { if(!_buf["faith_cost"].IsNumber) { throw new SerializationException(); }  FaithCost = _buf["faith_cost"]; }
        { if(!_buf["effect_desc"].IsString) { throw new SerializationException(); }  EffectDesc = _buf["effect_desc"]; }
        { if(!_buf["cult_attr"].IsString) { throw new SerializationException(); }  CultAttr = _buf["cult_attr"]; }
        { if(!_buf["cult_attr_value"].IsNumber) { throw new SerializationException(); }  CultAttrValue = _buf["cult_attr_value"]; }
    }

    public static CultTechNodeLevel DeserializeCultTechNodeLevel(JSONNode _buf)
    {
        return new demo.CultTechNodeLevel(_buf);
    }

    /// <summary>
    /// 节点
    /// </summary>
    public int NodeId;
    /// <summary>
    /// 等级
    /// </summary>
    public int Level;
    /// <summary>
    /// 前置节点
    /// </summary>
    public System.Collections.Generic.List<int> PrereqNodeIds;
    /// <summary>
    /// 信仰消耗
    /// </summary>
    public int FaithCost;
    /// <summary>
    /// 效果说明(占位)
    /// </summary>
    public string EffectDesc;
    /// <summary>
    /// ??????????????
    /// </summary>
    public string CultAttr;
    /// <summary>
    /// ?????
    /// </summary>
    public int CultAttrValue;
   
    public const int __ID__ = -918306329;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "nodeId:" + NodeId + ","
        + "level:" + Level + ","
        + "prereqNodeIds:" + Luban.StringUtil.CollectionToString(PrereqNodeIds) + ","
        + "faithCost:" + FaithCost + ","
        + "effectDesc:" + EffectDesc + ","
        + "cultAttr:" + CultAttr + ","
        + "cultAttrValue:" + CultAttrValue + ","
        + "}";
    }
}
}

