
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class CultAnchorAction : Luban.BeanBase
{
    public CultAnchorAction(JSONNode _buf) 
    {
        { if(!_buf["logic_area_id"].IsString) { throw new SerializationException(); }  LogicAreaId = _buf["logic_area_id"]; }
        { if(!_buf["anchor_id"].IsString) { throw new SerializationException(); }  AnchorId = _buf["anchor_id"]; }
        { if(!_buf["anchor_level"].IsNumber) { throw new SerializationException(); }  AnchorLevel = _buf["anchor_level"]; }
        { if(!_buf["action_id"].IsString) { throw new SerializationException(); }  ActionId = _buf["action_id"]; }
        { if(!_buf["progress"].IsNumber) { throw new SerializationException(); }  Progress = _buf["progress"]; }
    }

    public static CultAnchorAction DeserializeCultAnchorAction(JSONNode _buf)
    {
        return new demo.CultAnchorAction(_buf);
    }

    /// <summary>
    /// 逻辑地图
    /// </summary>
    public string LogicAreaId;
    /// <summary>
    /// 锚点ID
    /// </summary>
    public string AnchorId;
    /// <summary>
    /// 锚点等级
    /// </summary>
    public int AnchorLevel;
    /// <summary>
    /// 教会行为ID
    /// </summary>
    public string ActionId;
    /// <summary>
    /// 本次贡献进度
    /// </summary>
    public long Progress;
   
    public const int __ID__ = -1046376272;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "logicAreaId:" + LogicAreaId + ","
        + "anchorId:" + AnchorId + ","
        + "anchorLevel:" + AnchorLevel + ","
        + "actionId:" + ActionId + ","
        + "progress:" + Progress + ","
        + "}";
    }
}
}

