
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class CultAnchorOutput : Luban.BeanBase
{
    public CultAnchorOutput(JSONNode _buf) 
    {
        { if(!_buf["output_id"].IsNumber) { throw new SerializationException(); }  OutputId = _buf["output_id"]; }
        { if(!_buf["cycle_days"].IsNumber) { throw new SerializationException(); }  CycleDays = _buf["cycle_days"]; }
        { if(!_buf["faith"].IsNumber) { throw new SerializationException(); }  Faith = _buf["faith"]; }
        { if(!_buf["item_id"].IsString) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { if(!_buf["item_count"].IsNumber) { throw new SerializationException(); }  ItemCount = _buf["item_count"]; }
        { if(!_buf["dream_resource_id"].IsString) { throw new SerializationException(); }  DreamResourceId = _buf["dream_resource_id"]; }
        { if(!_buf["dream_resource_count"].IsNumber) { throw new SerializationException(); }  DreamResourceCount = _buf["dream_resource_count"]; }
        { if(!_buf["daily_linker_add"].IsNumber) { throw new SerializationException(); }  DailyLinkerAdd = _buf["daily_linker_add"]; }
        { if(!_buf["base_efficiency_percent"].IsNumber) { throw new SerializationException(); }  BaseEfficiencyPercent = _buf["base_efficiency_percent"]; }
        { if(!_buf["efficiency_per_linker_percent"].IsNumber) { throw new SerializationException(); }  EfficiencyPerLinkerPercent = _buf["efficiency_per_linker_percent"]; }
        { if(!_buf["max_efficiency_percent"].IsNumber) { throw new SerializationException(); }  MaxEfficiencyPercent = _buf["max_efficiency_percent"]; }
    }

    public static CultAnchorOutput DeserializeCultAnchorOutput(JSONNode _buf)
    {
        return new demo.CultAnchorOutput(_buf);
    }

    /// <summary>
    /// 产出配置ID
    /// </summary>
    public int OutputId;
    /// <summary>
    /// 周期天数
    /// </summary>
    public int CycleDays;
    /// <summary>
    /// 信仰
    /// </summary>
    public long Faith;
    /// <summary>
    /// 普通物品ID
    /// </summary>
    public string ItemId;
    /// <summary>
    /// 普通物品数量
    /// </summary>
    public long ItemCount;
    /// <summary>
    /// 入梦资源ID(占位)
    /// </summary>
    public string DreamResourceId;
    /// <summary>
    /// 入梦资源数量(占位)
    /// </summary>
    public long DreamResourceCount;
    /// <summary>
    /// 每日增加教徒
    /// </summary>
    public long DailyLinkerAdd;
    /// <summary>
    /// 基础效率百分比
    /// </summary>
    public int BaseEfficiencyPercent;
    /// <summary>
    /// 每名教徒效率百分比
    /// </summary>
    public int EfficiencyPerLinkerPercent;
    /// <summary>
    /// 效率上限百分比
    /// </summary>
    public int MaxEfficiencyPercent;
   
    public const int __ID__ = -628937861;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "outputId:" + OutputId + ","
        + "cycleDays:" + CycleDays + ","
        + "faith:" + Faith + ","
        + "itemId:" + ItemId + ","
        + "itemCount:" + ItemCount + ","
        + "dreamResourceId:" + DreamResourceId + ","
        + "dreamResourceCount:" + DreamResourceCount + ","
        + "dailyLinkerAdd:" + DailyLinkerAdd + ","
        + "baseEfficiencyPercent:" + BaseEfficiencyPercent + ","
        + "efficiencyPerLinkerPercent:" + EfficiencyPerLinkerPercent + ","
        + "maxEfficiencyPercent:" + MaxEfficiencyPercent + ","
        + "}";
    }
}
}

