
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class CultSecretCapabilityLevel : Luban.BeanBase
{
    public CultSecretCapabilityLevel(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["capability"].IsNumber) { throw new SerializationException(); }  Capability = _buf["capability"]; }
        { if(!_buf["cost_jingyuan"].IsNumber) { throw new SerializationException(); }  CostJingyuan = _buf["cost_jingyuan"]; }
        { if(!_buf["cost_item_id"].IsString) { throw new SerializationException(); }  CostItemId = _buf["cost_item_id"]; }
        { if(!_buf["cost_item_count"].IsNumber) { throw new SerializationException(); }  CostItemCount = _buf["cost_item_count"]; }
        { if(!_buf["cost_faith"].IsNumber) { throw new SerializationException(); }  CostFaith = _buf["cost_faith"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static CultSecretCapabilityLevel DeserializeCultSecretCapabilityLevel(JSONNode _buf)
    {
        return new demo.CultSecretCapabilityLevel(_buf);
    }

    /// <summary>
    /// 等级节点
    /// </summary>
    public int Level;
    /// <summary>
    /// 能力值
    /// </summary>
    public int Capability;
    /// <summary>
    /// 消耗精元(池)
    /// </summary>
    public long CostJingyuan;
    /// <summary>
    /// 消耗物品
    /// </summary>
    public string CostItemId;
    /// <summary>
    /// 消耗数量
    /// </summary>
    public long CostItemCount;
    /// <summary>
    /// 消耗信仰
    /// </summary>
    public long CostFaith;
    /// <summary>
    /// 名称
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 说明
    /// </summary>
    public string Desc;
   
    public const int __ID__ = 1688119991;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "capability:" + Capability + ","
        + "costJingyuan:" + CostJingyuan + ","
        + "costItemId:" + CostItemId + ","
        + "costItemCount:" + CostItemCount + ","
        + "costFaith:" + CostFaith + ","
        + "displayName:" + DisplayName + ","
        + "desc:" + Desc + ","
        + "}";
    }
}
}

