
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class CultScoutSite : Luban.BeanBase
{
    public CultScoutSite(JSONNode _buf) 
    {
        { if(!_buf["site_id"].IsString) { throw new SerializationException(); }  SiteId = _buf["site_id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["region_key"].IsString) { throw new SerializationException(); }  RegionKey = _buf["region_key"]; }
        { if(!_buf["logic_area_id"].IsString) { throw new SerializationException(); }  LogicAreaId = _buf["logic_area_id"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { var __json0 = _buf["unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  UnlockConds.Add(__v0); }   }
        { if(!_buf["duration_days"].IsNumber) { throw new SerializationException(); }  DurationDays = _buf["duration_days"]; }
        { if(!_buf["base_faith"].IsNumber) { throw new SerializationException(); }  BaseFaith = _buf["base_faith"]; }
        { if(!_buf["base_linker"].IsNumber) { throw new SerializationException(); }  BaseLinker = _buf["base_linker"]; }
        { if(!_buf["base_item_id"].IsString) { throw new SerializationException(); }  BaseItemId = _buf["base_item_id"]; }
        { if(!_buf["base_item_count"].IsNumber) { throw new SerializationException(); }  BaseItemCount = _buf["base_item_count"]; }
        { if(!_buf["special_item_id"].IsString) { throw new SerializationException(); }  SpecialItemId = _buf["special_item_id"]; }
        { if(!_buf["special_item_count"].IsNumber) { throw new SerializationException(); }  SpecialItemCount = _buf["special_item_count"]; }
        { if(!_buf["special_chance_percent"].IsNumber) { throw new SerializationException(); }  SpecialChancePercent = _buf["special_chance_percent"]; }
    }

    public static CultScoutSite DeserializeCultScoutSite(JSONNode _buf)
    {
        return new demo.CultScoutSite(_buf);
    }

    /// <summary>
    /// 出征点ID
    /// </summary>
    public string SiteId;
    /// <summary>
    /// 显示名
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 所属区域
    /// </summary>
    public string RegionKey;
    /// <summary>
    /// 关联逻辑图
    /// </summary>
    public string LogicAreaId;
    /// <summary>
    /// 说明
    /// </summary>
    public string Description;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> UnlockConds;
    /// <summary>
    /// 工期天数
    /// </summary>
    public int DurationDays;
    /// <summary>
    /// 基础信仰
    /// </summary>
    public long BaseFaith;
    /// <summary>
    /// 基础教徒
    /// </summary>
    public long BaseLinker;
    /// <summary>
    /// 基础物品
    /// </summary>
    public string BaseItemId;
    /// <summary>
    /// 基础数量
    /// </summary>
    public long BaseItemCount;
    /// <summary>
    /// 特殊物品
    /// </summary>
    public string SpecialItemId;
    /// <summary>
    /// 特殊数量
    /// </summary>
    public long SpecialItemCount;
    /// <summary>
    /// 特殊概率%
    /// </summary>
    public int SpecialChancePercent;
   
    public const int __ID__ = -1583307232;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UnlockConds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "siteId:" + SiteId + ","
        + "displayName:" + DisplayName + ","
        + "regionKey:" + RegionKey + ","
        + "logicAreaId:" + LogicAreaId + ","
        + "description:" + Description + ","
        + "unlockConds:" + Luban.StringUtil.CollectionToString(UnlockConds) + ","
        + "durationDays:" + DurationDays + ","
        + "baseFaith:" + BaseFaith + ","
        + "baseLinker:" + BaseLinker + ","
        + "baseItemId:" + BaseItemId + ","
        + "baseItemCount:" + BaseItemCount + ","
        + "specialItemId:" + SpecialItemId + ","
        + "specialItemCount:" + SpecialItemCount + ","
        + "specialChancePercent:" + SpecialChancePercent + ","
        + "}";
    }
}
}

