
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class CultAncientSeat : Luban.BeanBase
{
    public CultAncientSeat(JSONNode _buf) 
    {
        { if(!_buf["seat_id"].IsNumber) { throw new SerializationException(); }  SeatId = _buf["seat_id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["title"].IsString) { throw new SerializationException(); }  Title = _buf["title"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["state_desc"].IsString) { throw new SerializationException(); }  StateDesc = _buf["state_desc"]; }
        { if(!_buf["unlock_faith_cost"].IsNumber) { throw new SerializationException(); }  UnlockFaithCost = _buf["unlock_faith_cost"]; }
        { if(!_buf["default_unlocked"].IsBoolean) { throw new SerializationException(); }  DefaultUnlocked = _buf["default_unlocked"]; }
        { var __json0 = _buf["unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  UnlockConds.Add(__v0); }   }
    }

    public static CultAncientSeat DeserializeCultAncientSeat(JSONNode _buf)
    {
        return new demo.CultAncientSeat(_buf);
    }

    /// <summary>
    /// 座位
    /// </summary>
    public int SeatId;
    /// <summary>
    /// 古老者名称
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 座位标题
    /// </summary>
    public string Title;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
    /// <summary>
    /// 存在状态
    /// </summary>
    public string StateDesc;
    /// <summary>
    /// 点亮信仰
    /// </summary>
    public int UnlockFaithCost;
    /// <summary>
    /// 默认点亮
    /// </summary>
    public bool DefaultUnlocked;
    public System.Collections.Generic.List<demo.CommonCheckCond> UnlockConds;
   
    public const int __ID__ = 109119704;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UnlockConds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "seatId:" + SeatId + ","
        + "displayName:" + DisplayName + ","
        + "title:" + Title + ","
        + "desc:" + Desc + ","
        + "stateDesc:" + StateDesc + ","
        + "unlockFaithCost:" + UnlockFaithCost + ","
        + "defaultUnlocked:" + DefaultUnlocked + ","
        + "unlockConds:" + Luban.StringUtil.CollectionToString(UnlockConds) + ","
        + "}";
    }
}
}

