
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class CultAnchor : Luban.BeanBase
{
    public CultAnchor(JSONNode _buf) 
    {
        { if(!_buf["anchor_id"].IsString) { throw new SerializationException(); }  AnchorId = _buf["anchor_id"]; }
        { if(!_buf["logic_area_id"].IsString) { throw new SerializationException(); }  LogicAreaId = _buf["logic_area_id"]; }
        { if(!_buf["region_key"].IsString) { throw new SerializationException(); }  RegionKey = _buf["region_key"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["establish_progress"].IsNumber) { throw new SerializationException(); }  EstablishProgress = _buf["establish_progress"]; }
        { var __json0 = _buf["show_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } ShowConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  ShowConds.Add(__v0); }   }
        { if(!_buf["output_id"].IsNumber) { throw new SerializationException(); }  OutputId = _buf["output_id"]; }
        { if(!_buf["rarity"].IsNumber) { throw new SerializationException(); }  Rarity = _buf["rarity"]; }
    }

    public static CultAnchor DeserializeCultAnchor(JSONNode _buf)
    {
        return new demo.CultAnchor(_buf);
    }

    /// <summary>
    /// 锚点ID
    /// </summary>
    public string AnchorId;
    /// <summary>
    /// 逻辑地图
    /// </summary>
    public string LogicAreaId;
    /// <summary>
    /// 所属区域
    /// </summary>
    public string RegionKey;
    /// <summary>
    /// 显示名称
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 建立所需进度
    /// </summary>
    public long EstablishProgress;
    /// <summary>
    /// 显示条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> ShowConds;
    /// <summary>
    /// 产出配置ID
    /// </summary>
    public int OutputId;
    /// <summary>
    /// 稀有度
    /// </summary>
    public int Rarity;
   
    public const int __ID__ = -837324326;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in ShowConds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "anchorId:" + AnchorId + ","
        + "logicAreaId:" + LogicAreaId + ","
        + "regionKey:" + RegionKey + ","
        + "displayName:" + DisplayName + ","
        + "establishProgress:" + EstablishProgress + ","
        + "showConds:" + Luban.StringUtil.CollectionToString(ShowConds) + ","
        + "outputId:" + OutputId + ","
        + "rarity:" + Rarity + ","
        + "}";
    }
}
}

