
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class CultTechNode : Luban.BeanBase
{
    public CultTechNode(JSONNode _buf) 
    {
        { if(!_buf["node_id"].IsNumber) { throw new SerializationException(); }  NodeId = _buf["node_id"];
        { SeatId = _buf["seat_id"]; } }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["max_level"].IsNumber) { throw new SerializationException(); }  MaxLevel = _buf["max_level"]; }
        { if(!_buf["ring"].IsNumber) { throw new SerializationException(); }  Ring = _buf["ring"]; }
        { if(!_buf["angle_deg"].IsNumber) { throw new SerializationException(); }  AngleDeg = _buf["angle_deg"]; }
        { if(!_buf["icon_path"].IsString) { throw new SerializationException(); }  IconPath = _buf["icon_path"]; }
    }

    public static CultTechNode DeserializeCultTechNode(JSONNode _buf)
    {
        return new demo.CultTechNode(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int NodeId;
    public int SeatId;
    /// <summary>
    /// 名称
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
    /// <summary>
    /// 最大等级
    /// </summary>
    public int MaxLevel;
    /// <summary>
    /// 环(0中心)
    /// </summary>
    public int Ring;
    /// <summary>
    /// 角度
    /// </summary>
    public int AngleDeg;
    /// <summary>
    /// 图标
    /// </summary>
    public string IconPath;
   
    public const int __ID__ = 2140251037;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "nodeId:" + NodeId + ","
        + "displayName:" + DisplayName + ","
        + "desc:" + Desc + ","
        + "maxLevel:" + MaxLevel + ","
        + "ring:" + Ring + ","
        + "angleDeg:" + AngleDeg + ","
        + "iconPath:" + IconPath + ","
        + "}";
    }
}
}

