
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class DesireCrystalDef : Luban.BeanBase
{
    public DesireCrystalDef(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["item_id"].IsString) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { if(!_buf["random_pick_weight"].IsNumber) { throw new SerializationException(); }  RandomPickWeight = _buf["random_pick_weight"]; }
    }

    public static DesireCrystalDef DeserializeDesireCrystalDef(JSONNode _buf)
    {
        return new demo.DesireCrystalDef(_buf);
    }

    /// <summary>
    /// 结晶类型 id
    /// </summary>
    public string Id;
    /// <summary>
    /// 收获时给的道具 id（需在 item 表存在）
    /// </summary>
    public string ItemId;
    /// <summary>
    /// 随机抽取权重
    /// </summary>
    public int RandomPickWeight;
   
    public const int __ID__ = 200891492;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "itemId:" + ItemId + ","
        + "randomPickWeight:" + RandomPickWeight + ","
        + "}";
    }
}
}

