
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class DialogMetaInfo : Luban.BeanBase
{
    public DialogMetaInfo(JSONNode _buf) 
    {
        { if(!_buf["dialog_id"].IsString) { throw new SerializationException(); }  DialogId = _buf["dialog_id"]; }
        { if(!_buf["is_auto_trigger"].IsBoolean) { throw new SerializationException(); }  IsAutoTrigger = _buf["is_auto_trigger"]; }
        { if(!_buf["only_once"].IsBoolean) { throw new SerializationException(); }  OnlyOnce = _buf["only_once"]; }
        { if(!_buf["json_data_name"].IsString) { throw new SerializationException(); }  JsonDataName = _buf["json_data_name"]; }
        { if(!_buf["need_map"].IsString) { throw new SerializationException(); }  NeedMap = _buf["need_map"]; }
        { var __json0 = _buf["trigger_cond"]; if(!__json0.IsArray) { throw new SerializationException(); } TriggerCond = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  TriggerCond.Add(__v0); }   }
        { if(!_buf["active_trigger_npc"].IsString) { throw new SerializationException(); }  ActiveTriggerNpc = _buf["active_trigger_npc"]; }
        { if(!_buf["lock_global_time"].IsBoolean) { throw new SerializationException(); }  LockGlobalTime = _buf["lock_global_time"]; }
        { var __json0 = _buf["controlled_entity_list"]; if(!__json0.IsArray) { throw new SerializationException(); } ControlledEntityList = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  ControlledEntityList.Add(__v0); }   }
        { if(!_buf["show_priority"].IsNumber) { throw new SerializationException(); }  ShowPriority = _buf["show_priority"]; }
        { var __json0 = _buf["custom_variables"]; if(!__json0.IsArray) { throw new SerializationException(); } CustomVariables = new System.Collections.Generic.Dictionary<string, string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } string _v0;  { if(!__e0[1].IsString) { throw new SerializationException(); }  _v0 = __e0[1]; }  CustomVariables.Add(_k0, _v0); }   }
        { if(!_buf["cutscene_id"].IsString) { throw new SerializationException(); }  CutsceneId = _buf["cutscene_id"]; }
    }

    public static DialogMetaInfo DeserializeDialogMetaInfo(JSONNode _buf)
    {
        return new demo.DialogMetaInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public string DialogId;
    /// <summary>
    /// 是否自动触发
    /// </summary>
    public bool IsAutoTrigger;
    /// <summary>
    /// 是否唯一
    /// </summary>
    public bool OnlyOnce;
    /// <summary>
    /// 数据路径
    /// </summary>
    public string JsonDataName;
    /// <summary>
    /// 触发地图
    /// </summary>
    public string NeedMap;
    /// <summary>
    /// 触发条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> TriggerCond;
    /// <summary>
    /// 触发npc
    /// </summary>
    public string ActiveTriggerNpc;
    /// <summary>
    /// 是否全局时停
    /// </summary>
    public bool LockGlobalTime;
    /// <summary>
    /// 控制列表<br/>键为单位唯一名
    /// </summary>
    public System.Collections.Generic.List<string> ControlledEntityList;
    /// <summary>
    /// 显示优先级<br/>npc始终绑定只一个普通对话，按照优先级排序
    /// </summary>
    public int ShowPriority;
    /// <summary>
    /// 传参入口<br/>用于对白数据复用
    /// </summary>
    public System.Collections.Generic.Dictionary<string, string> CustomVariables;
    /// <summary>
    /// 特殊演出地图<br/>该值有值时会进行场景切换
    /// </summary>
    public string CutsceneId;
   
    public const int __ID__ = 971702598;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in TriggerCond) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "dialogId:" + DialogId + ","
        + "isAutoTrigger:" + IsAutoTrigger + ","
        + "onlyOnce:" + OnlyOnce + ","
        + "jsonDataName:" + JsonDataName + ","
        + "needMap:" + NeedMap + ","
        + "triggerCond:" + Luban.StringUtil.CollectionToString(TriggerCond) + ","
        + "activeTriggerNpc:" + ActiveTriggerNpc + ","
        + "lockGlobalTime:" + LockGlobalTime + ","
        + "controlledEntityList:" + Luban.StringUtil.CollectionToString(ControlledEntityList) + ","
        + "showPriority:" + ShowPriority + ","
        + "customVariables:" + Luban.StringUtil.CollectionToString(CustomVariables) + ","
        + "cutsceneId:" + CutsceneId + ","
        + "}";
    }
}
}

