
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class DreamPasserby : Luban.BeanBase
{
    public DreamPasserby(JSONNode _buf) 
    {
        { if(!_buf["passerby_id"].IsString) { throw new SerializationException(); }  PasserbyId = _buf["passerby_id"]; }
        { if(!_buf["grade"].IsNumber) { throw new SerializationException(); }  Grade = (demo.ECommonGrade)_buf["grade"].AsInt; }
        { if(!_buf["visual_variant"].IsNumber) { throw new SerializationException(); }  VisualVariant = _buf["visual_variant"]; }
        { if(!_buf["refresh_weight"].IsNumber) { throw new SerializationException(); }  RefreshWeight = _buf["refresh_weight"]; }
        { var __json0 = _buf["region_ids"]; if(!__json0.IsArray) { throw new SerializationException(); } RegionIds = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  RegionIds.Add(__v0); }   }
        { if(!_buf["dream_theme_id"].IsString) { throw new SerializationException(); }  DreamThemeId = _buf["dream_theme_id"]; }
        { if(!_buf["dream_theme_display_name"].IsString) { throw new SerializationException(); }  DreamThemeDisplayName = _buf["dream_theme_display_name"]; }
        { if(!_buf["core_max_hp"].IsNumber) { throw new SerializationException(); }  CoreMaxHp = _buf["core_max_hp"]; }
        { if(!_buf["player_max_hp"].IsNumber) { throw new SerializationException(); }  PlayerMaxHp = _buf["player_max_hp"]; }
        { if(!_buf["bullet_damage"].IsNumber) { throw new SerializationException(); }  BulletDamage = _buf["bullet_damage"]; }
        { if(!_buf["aoe_damage"].IsNumber) { throw new SerializationException(); }  AoeDamage = _buf["aoe_damage"]; }
        { if(!_buf["projectile_damage"].IsNumber) { throw new SerializationException(); }  ProjectileDamage = _buf["projectile_damage"]; }
        { if(!_buf["reward_desire_shard"].IsNumber) { throw new SerializationException(); }  RewardDesireShard = _buf["reward_desire_shard"]; }
        { if(!_buf["reward_jingyuan"].IsNumber) { throw new SerializationException(); }  RewardJingyuan = _buf["reward_jingyuan"]; }
        { if(!_buf["reward_fallen_base_amount"].IsNumber) { throw new SerializationException(); }  RewardFallenBaseAmount = _buf["reward_fallen_base_amount"]; }
    }

    public static DreamPasserby DeserializeDreamPasserby(JSONNode _buf)
    {
        return new demo.DreamPasserby(_buf);
    }

    /// <summary>
    /// 路人ID
    /// </summary>
    public string PasserbyId;
    /// <summary>
    /// 品级
    /// </summary>
    public demo.ECommonGrade Grade;
    /// <summary>
    /// 形象档
    /// </summary>
    public int VisualVariant;
    /// <summary>
    /// 权重
    /// </summary>
    public int RefreshWeight;
    /// <summary>
    /// 可刷区域
    /// </summary>
    public System.Collections.Generic.List<string> RegionIds;
    /// <summary>
    /// 主题ID
    /// </summary>
    public string DreamThemeId;
    /// <summary>
    /// 主题名
    /// </summary>
    public string DreamThemeDisplayName;
    /// <summary>
    /// 核心HP
    /// </summary>
    public int CoreMaxHp;
    /// <summary>
    /// 玩家HP
    /// </summary>
    public int PlayerMaxHp;
    /// <summary>
    /// 弹伤
    /// </summary>
    public int BulletDamage;
    /// <summary>
    /// AOE
    /// </summary>
    public int AoeDamage;
    /// <summary>
    /// 炮弹
    /// </summary>
    public int ProjectileDamage;
    /// <summary>
    /// 欲望碎片
    /// </summary>
    public long RewardDesireShard;
    /// <summary>
    /// 精元池
    /// </summary>
    public long RewardJingyuan;
    /// <summary>
    /// 基础沉沦
    /// </summary>
    public long RewardFallenBaseAmount;
   
    public const int __ID__ = -1232032371;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "passerbyId:" + PasserbyId + ","
        + "grade:" + Grade + ","
        + "visualVariant:" + VisualVariant + ","
        + "refreshWeight:" + RefreshWeight + ","
        + "regionIds:" + Luban.StringUtil.CollectionToString(RegionIds) + ","
        + "dreamThemeId:" + DreamThemeId + ","
        + "dreamThemeDisplayName:" + DreamThemeDisplayName + ","
        + "coreMaxHp:" + CoreMaxHp + ","
        + "playerMaxHp:" + PlayerMaxHp + ","
        + "bulletDamage:" + BulletDamage + ","
        + "aoeDamage:" + AoeDamage + ","
        + "projectileDamage:" + ProjectileDamage + ","
        + "rewardDesireShard:" + RewardDesireShard + ","
        + "rewardJingyuan:" + RewardJingyuan + ","
        + "rewardFallenBaseAmount:" + RewardFallenBaseAmount + ","
        + "}";
    }
}
}

