
//------------------------------------------------------------------------------
// <auto-generated>
//     Dream 入梦配置（与 Config/Defines/schema.xml 及 Luban 导出约定一致）
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg.demo
{
    [System.Serializable]
    public sealed class DreamInfiltrationSpot : Luban.BeanBase
    {
        public DreamInfiltrationSpot(JSONNode _buf)
        {
            { if (!_buf["spot_id"].IsString) { throw new SerializationException(); } SpotId = _buf["spot_id"]; }
            { if (!_buf["display_name"].IsString) { throw new SerializationException(); } DisplayName = _buf["display_name"]; }
            { if (!_buf["anchor_x"].IsNumber) { throw new SerializationException(); } AnchorX = _buf["anchor_x"]; }
            { if (!_buf["anchor_y"].IsNumber) { throw new SerializationException(); } AnchorY = _buf["anchor_y"]; }
            {
                var __json0 = _buf["unlock_conds"];
                if (!__json0.IsArray) { throw new SerializationException(); }
                UnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count);
                foreach (JSONNode __e0 in __json0.Children)
                {
                    demo.CommonCheckCond __v0;
                    { if (!__e0.IsObject) { throw new SerializationException(); } __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0); }
                    UnlockConds.Add(__v0);
                }
            }
            {
                var __json0 = _buf["theme_weights"];
                if (!__json0.IsArray) { throw new SerializationException(); }
                ThemeWeights = new System.Collections.Generic.List<demo.DreamThemeWeight>(__json0.Count);
                foreach (JSONNode __e0 in __json0.Children)
                {
                    demo.DreamThemeWeight __v0;
                    { if (!__e0.IsObject) { throw new SerializationException(); } __v0 = global::cfg.demo.DreamThemeWeight.DeserializeDreamThemeWeight(__e0); }
                    ThemeWeights.Add(__v0);
                }
            }
        }

        public static DreamInfiltrationSpot DeserializeDreamInfiltrationSpot(JSONNode _buf)
        {
            return new demo.DreamInfiltrationSpot(_buf);
        }

        public string SpotId;
        public string DisplayName;
        public float AnchorX;
        public float AnchorY;
        public System.Collections.Generic.List<demo.CommonCheckCond> UnlockConds;
        public System.Collections.Generic.List<demo.DreamThemeWeight> ThemeWeights;

        public const int __ID__ = -1890010202;
        public override int GetTypeId() => __ID__;

        public void ResolveRef(Tables tables)
        {
            foreach (var _e in UnlockConds) { _e?.ResolveRef(tables); }
        }

        public override string ToString()
        {
            return "{ spotId:" + SpotId + ",displayName:" + DisplayName + "}";
        }
    }
}
