
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    public enum EAreaCampFilter
    {
        All = 0,
        NotSelf = 1,
        OnlySelf = 2,
    }

} 

