
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    public enum ECommonCheckType
    {
        None = 0,
        TaskFinish = 1,
        CheckVariable = 2,
        OwnItem = 4,
        TaskStep = 5,
    }

} 

