
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    /// <summary>
    /// 通用品级
    /// </summary>
    public enum ECommonGrade
    {
        /// <summary>
        /// 未指定
        /// </summary>
        None = 0,
        /// <summary>
        /// 凡品
        /// </summary>
        Common = 1,
        /// <summary>
        /// 良品
        /// </summary>
        Uncommon = 2,
        /// <summary>
        /// 稀品
        /// </summary>
        Rare = 3,
        /// <summary>
        /// 上品
        /// </summary>
        Epic = 4,
        /// <summary>
        /// 极品
        /// </summary>
        Legendary = 5,
    }

} 

