
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    /// <summary>
    /// 料理风格标签
    /// </summary>
    public enum ECookingStyleTag
    {
        /// <summary>
        /// 无风格
        /// </summary>
        None = 0,
        /// <summary>
        /// 家常
        /// </summary>
        Homestyle = 1,
        /// <summary>
        /// 丰盛
        /// </summary>
        Hearty = 2,
        /// <summary>
        /// 甜味
        /// </summary>
        Sweet = 3,
        /// <summary>
        /// 清爽
        /// </summary>
        Refreshing = 4,
        /// <summary>
        /// 精致
        /// </summary>
        Refined = 5,
        /// <summary>
        /// 节庆
        /// </summary>
        Festive = 6,
        /// <summary>
        /// 异域
        /// </summary>
        Exotic = 7,
        /// <summary>
        /// 怀旧
        /// </summary>
        Nostalgic = 8,
    }

} 

