
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    /// <summary>
    /// 教团秘会任务类型
    /// </summary>
    public enum ECultMissionType
    {
        /// <summary>
        /// 未指定
        /// </summary>
        None = 0,
        /// <summary>
        /// 增幅锚点
        /// </summary>
        AmplifyAnchor = 1,
        /// <summary>
        /// 远征搜集
        /// </summary>
        ScoutGather = 2,
        /// <summary>
        /// 区域传教
        /// </summary>
        Preach = 3,
        /// <summary>
        /// 灭迹
        /// </summary>
        CoverTraces = 4,
        /// <summary>
        /// 献精
        /// </summary>
        OfferEssence = 5,
    }

} 

