
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    public enum EDesireDensityType
    {
        None = 0,
        Normal = 1,
        Elite = 2,
        Boss = 3,
    }

} 

