
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may be lost if the code is regenerated.
//------------------------------------------------------------------------------

namespace cfg.demo
{
    public enum EForgeUnlockMode
    {
        None = 0,
        QuestFinished = 1,
        HasItem = 2,
        GlobalSwitch = 3,
    }
}
