
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    public enum EItemType
    {
        Normal = 0,
        Currency = 1,
        Equip = 2,
        Pocket = 3,
        Insertion = 4,
        Gift = 5,
        HumanWeapon = 6,
        PartGear = 7,
        MindFacet = 10,
    }

} 

