
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    public enum EItemRevealEffectType
    {
        None = 0,
        AddGcVal = 1,
        CostClothes = 2,
    }

} 

