
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    public enum EItemStackProfile
    {
        Custom = 0,
        Single = 1,
        Tiny = 2,
        Small = 3,
        Normal = 4,
        Bulk = 5,
        Large = 6,
        Massive = 7,
        Unlimited = 8,
    }

} 

