
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    public enum EItemUseConsumePolicy
    {
        None = 0,
        StackCount = 1,
        InstanceCharge = 2,
        DestroyInstance = 3,
    }

} 

