
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    public enum EItemStackType
    {
        NoStack = 0,
        Size1 = 1,
        Size2 = 2,
        Size3 = 3,
        Size4 = 4,
        Custom = 5,
        NoLimit = 6,
    }

} 

