
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    /// <summary>
    /// ??????
    /// </summary>
    public enum EItemTag
    {
        /// <summary>
        /// ???
        /// </summary>
        None = 0,
        /// <summary>
        /// ??
        /// </summary>
        Gift = 1,
        /// <summary>
        /// ????
        /// </summary>
        PartGear = 3,
        /// <summary>
        /// ????
        /// </summary>
        HumanWeapon = 4,
        /// <summary>
        /// ????
        /// </summary>
        HumanTool = 5,
        /// <summary>
        /// ??
        /// </summary>
        Pocket = 6,
        /// <summary>
        /// ???
        /// </summary>
        Insertion = 7,
        /// <summary>
        /// ??
        /// </summary>
        Plant = 8,
        /// <summary>
        /// ??
        /// </summary>
        Key = 9,
        /// <summary>
        /// ??
        /// </summary>
        Potion = 10,
        /// <summary>
        /// ??
        /// </summary>
        Furniture = 11,
        /// <summary>
        /// ???
        /// </summary>
        Dismantleable = 12,
        /// <summary>
        /// ??
        /// </summary>
        Jingyuan = 13,
        /// <summary>
        /// ??
        /// </summary>
        Small = 14,
        /// <summary>
        /// ??
        /// </summary>
        Big = 15,
        /// <summary>
        /// ??
        /// </summary>
        Material = 16,
        /// <summary>
        /// ??
        /// </summary>
        Wood = 17,
        /// <summary>
        /// ??
        /// </summary>
        Magic = 18,
        /// <summary>
        /// ??
        /// </summary>
        Alchemy = 19,
        /// <summary>
        /// ??
        /// </summary>
        Fuel = 20,
        /// <summary>
        /// ??
        /// </summary>
        Fiber = 21,
        /// <summary>
        /// ??
        /// </summary>
        Stone = 22,
        /// <summary>
        /// ??
        /// </summary>
        Glass = 23,
        /// <summary>
        /// ??
        /// </summary>
        Clay = 24,
        /// <summary>
        /// ??
        /// </summary>
        Ceramic = 25,
        /// <summary>
        /// ???
        /// </summary>
        Luxury = 26,
        /// <summary>
        /// ??
        /// </summary>
        Craft = 27,
        /// <summary>
        /// ??
        /// </summary>
        Ore = 28,
        /// <summary>
        /// ??
        /// </summary>
        Metal = 29,
        /// <summary>
        /// ???
        /// </summary>
        Precious = 30,
        /// <summary>
        /// ???
        /// </summary>
        Textile = 31,
        /// <summary>
        /// ??
        /// </summary>
        Leather = 32,
        /// <summary>
        /// ??
        /// </summary>
        Bone = 33,
        /// <summary>
        /// ??
        /// </summary>
        Dye = 34,
        /// <summary>
        /// ?
        /// </summary>
        Glue = 35,
        /// <summary>
        /// ??
        /// </summary>
        Latex = 36,
        /// <summary>
        /// ??
        /// </summary>
        Exotic = 37,
        /// <summary>
        /// ???
        /// </summary>
        Loot = 38,
        /// <summary>
        /// ??
        /// </summary>
        Paper = 39,
        /// <summary>
        /// ??
        /// </summary>
        Food = 40,
        /// <summary>
        /// ??
        /// </summary>
        Gel = 41,
        /// <summary>
        /// ??
        /// </summary>
        Crystal = 42,
        /// <summary>
        /// ?
        /// </summary>
        Wax = 43,
        /// <summary>
        /// ??
        /// </summary>
        Toy = 44,
        /// <summary>
        /// ??
        /// </summary>
        Decor = 45,
        /// <summary>
        /// ??
        /// </summary>
        Home = 46,
        /// <summary>
        /// ??
        /// </summary>
        Study = 47,
        /// <summary>
        /// ??
        /// </summary>
        Church = 48,
        /// <summary>
        /// ??
        /// </summary>
        Light = 49,
        /// <summary>
        /// ??
        /// </summary>
        Forest = 50,
        /// <summary>
        /// ??
        /// </summary>
        Storage = 51,
        /// <summary>
        /// ??
        /// </summary>
        Facility = 52,
        /// <summary>
        /// ??
        /// </summary>
        Basic = 53,
        /// <summary>
        /// ??
        /// </summary>
        Salvage = 54,
        /// <summary>
        /// ??
        /// </summary>
        Dew = 55,
        /// <summary>
        /// ??
        /// </summary>
        Fairy = 56,
        /// <summary>
        /// ??
        /// </summary>
        Charge = 57,
        /// <summary>
        /// ??????
        /// </summary>
        PremiumEssenceDrop = 58,
        /// <summary>
        /// ??????
        /// </summary>
        HumanArmar = 59,
        /// <summary>
        /// ?????
        /// </summary>
        ArmarHead = 60,
        /// <summary>
        /// ?????
        /// </summary>
        ArmarChest = 61,
        /// <summary>
        /// ?????
        /// </summary>
        ArmarHand = 62,
        /// <summary>
        /// ?????
        /// </summary>
        ArmarLeg = 63,
        /// <summary>
        /// ?????
        /// </summary>
        ArmarFoot = 64,
        /// <summary>
        /// ?????
        /// </summary>
        ArmarAccessory = 65,
        /// <summary>
        /// 种子
        /// </summary>
        Seed = 66,
    }

} 

