
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    public enum EJingYuanType
    {
        None = 0,
        OrcI = 1,
        OrcII = 2,
        HumanI = 3,
        HumanII = 4,
        HumanIII = 5,
        HumanIV = 6,
        HumanV = 7,
        HumanVI = 8,
        HumanVII = 9,
        MonsterI = 10,
        MonsterII = 11,
        MonsterIII = 12,
    }

} 

