
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class EntitySkillData : Luban.BeanBase
{
    public EntitySkillData(JSONNode _buf) 
    {
        { if(!_buf["skill_id"].IsString) { throw new SerializationException(); }  SkillId = _buf["skill_id"]; }
        { if(!_buf["main_ability_id"].IsString) { throw new SerializationException(); }  MainAbilityId = _buf["main_ability_id"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["is_passive"].IsBoolean) { throw new SerializationException(); }  IsPassive = _buf["is_passive"]; }
        { var __json0 = _buf["passive_buff_ids"]; if(!__json0.IsArray) { throw new SerializationException(); } PassiveBuffIds = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  PassiveBuffIds.Add(__v0); }   }
        { if(!_buf["passive_buff_level_variable_key"].IsString) { throw new SerializationException(); }  PassiveBuffLevelVariableKey = _buf["passive_buff_level_variable_key"]; }
        { if(!_buf["is_combo"].IsBoolean) { throw new SerializationException(); }  IsCombo = _buf["is_combo"]; }
        { if(!_buf["need_h_mode"].IsBoolean) { throw new SerializationException(); }  NeedHMode = _buf["need_h_mode"]; }
        { if(!_buf["interrupt_combo"].IsBoolean) { throw new SerializationException(); }  InterruptCombo = _buf["interrupt_combo"]; }
        { if(!_buf["is_derived"].IsBoolean) { throw new SerializationException(); }  IsDerived = _buf["is_derived"]; }
        { if(!_buf["cool_down"].IsNumber) { throw new SerializationException(); }  CoolDown = _buf["cool_down"]; }
        { if(!_buf["stack_count"].IsNumber) { throw new SerializationException(); }  StackCount = _buf["stack_count"]; }
        { if(!_buf["icon_path"].IsString) { throw new SerializationException(); }  IconPath = _buf["icon_path"]; }
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
        { if(!_buf["desired_use_angle"].IsNumber) { throw new SerializationException(); }  DesiredUseAngle = _buf["desired_use_angle"]; }
        { if(!_buf["desired_use_distance"].IsNumber) { throw new SerializationException(); }  DesiredUseDistance = _buf["desired_use_distance"]; }
        { if(!_buf["buffer_cache_time"].IsNumber) { throw new SerializationException(); }  BufferCacheTime = _buf["buffer_cache_time"]; }
        { var __json0 = _buf["ability_extra"]; if(!__json0.IsArray) { throw new SerializationException(); } AbilityExtra = new System.Collections.Generic.List<demo.SkillAbilityExtraPair>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.SkillAbilityExtraPair __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.SkillAbilityExtraPair.DeserializeSkillAbilityExtraPair(__e0);  }  AbilityExtra.Add(__v0); }   }
        { var __json0 = _buf["cast_conditions"]; if(!__json0.IsArray) { throw new SerializationException(); } CastConditions = new System.Collections.Generic.List<demo.SkillCastCondition>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.SkillCastCondition __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.SkillCastCondition.DeserializeSkillCastCondition(__e0);  }  CastConditions.Add(__v0); }   }
    }

    public static EntitySkillData DeserializeEntitySkillData(JSONNode _buf)
    {
        return new demo.EntitySkillData(_buf);
    }

    /// <summary>
    /// skill_id
    /// </summary>
    public string SkillId;
    /// <summary>
    /// main_ability_id
    /// </summary>
    public string MainAbilityId;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
    /// <summary>
    /// is_passive
    /// </summary>
    public bool IsPassive;
    /// <summary>
    /// c
    /// </summary>
    public System.Collections.Generic.List<string> PassiveBuffIds;
    /// <summary>
    /// passive_buff_level_variable_key
    /// </summary>
    public string PassiveBuffLevelVariableKey;
    /// <summary>
    /// is_combo
    /// </summary>
    public bool IsCombo;
    /// <summary>
    /// need_h_mode
    /// </summary>
    public bool NeedHMode;
    /// <summary>
    /// interrupt_combo
    /// </summary>
    public bool InterruptCombo;
    /// <summary>
    /// is_derived
    /// </summary>
    public bool IsDerived;
    /// <summary>
    /// cool_down
    /// </summary>
    public float CoolDown;
    /// <summary>
    /// stack_count
    /// </summary>
    public int StackCount;
    /// <summary>
    /// icon_path
    /// </summary>
    public string IconPath;
    /// <summary>
    /// priority
    /// </summary>
    public int Priority;
    /// <summary>
    /// desired_use_angle
    /// </summary>
    public float DesiredUseAngle;
    /// <summary>
    /// desired_use_distance
    /// </summary>
    public float DesiredUseDistance;
    /// <summary>
    /// buffer_cache_time
    /// </summary>
    public float BufferCacheTime;
    /// <summary>
    /// ability_extra
    /// </summary>
    public System.Collections.Generic.List<demo.SkillAbilityExtraPair> AbilityExtra;
    /// <summary>
    /// cast_conditions
    /// </summary>
    public System.Collections.Generic.List<demo.SkillCastCondition> CastConditions;
   
    public const int __ID__ = 814216909;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in AbilityExtra) { _e?.ResolveRef(tables); }
        foreach (var _e in CastConditions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "skillId:" + SkillId + ","
        + "mainAbilityId:" + MainAbilityId + ","
        + "desc:" + Desc + ","
        + "isPassive:" + IsPassive + ","
        + "passiveBuffIds:" + Luban.StringUtil.CollectionToString(PassiveBuffIds) + ","
        + "passiveBuffLevelVariableKey:" + PassiveBuffLevelVariableKey + ","
        + "isCombo:" + IsCombo + ","
        + "needHMode:" + NeedHMode + ","
        + "interruptCombo:" + InterruptCombo + ","
        + "isDerived:" + IsDerived + ","
        + "coolDown:" + CoolDown + ","
        + "stackCount:" + StackCount + ","
        + "iconPath:" + IconPath + ","
        + "priority:" + Priority + ","
        + "desiredUseAngle:" + DesiredUseAngle + ","
        + "desiredUseDistance:" + DesiredUseDistance + ","
        + "bufferCacheTime:" + BufferCacheTime + ","
        + "abilityExtra:" + Luban.StringUtil.CollectionToString(AbilityExtra) + ","
        + "castConditions:" + Luban.StringUtil.CollectionToString(CastConditions) + ","
        + "}";
    }
}
}

