
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    public enum EProgressionHubTab
    {
        Skills = 0,
        Talents = 1,
        BodyPart = 2,
        World = 3,
        Runes = 4,
        JingYuanTune = 5,
    }

} 

