
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    public enum ESecretBaseCharacterOptionAction
    {
        Talk = 0,
        Gift = 1,
        OpenTalentTree = 2,
        OpenPanel = 3,
        OpenOptionGroup = 4,
        GivePremiumEssence = 5,
        AppraiseHumanArmar = 6,
    }

} 

