
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class EventGrantTarget : Luban.BeanBase
{
    public EventGrantTarget(JSONNode _buf) 
    {
        { if(!_buf["stat_type"].IsNumber) { throw new SerializationException(); }  StatType = (demo.EStatType)_buf["stat_type"].AsInt; }
        { if(!_buf["arg0"].IsString) { throw new SerializationException(); }  Arg0 = _buf["arg0"]; }
        { if(!_buf["arg1"].IsString) { throw new SerializationException(); }  Arg1 = _buf["arg1"]; }
        { if(!_buf["op"].IsNumber) { throw new SerializationException(); }  Op = (demo.EStatCompareOp)_buf["op"].AsInt; }
        { if(!_buf["value"].IsNumber) { throw new SerializationException(); }  Value = _buf["value"]; }
    }

    public static EventGrantTarget DeserializeEventGrantTarget(JSONNode _buf)
    {
        return new demo.EventGrantTarget(_buf);
    }

    /// <summary>
    /// 统计类型
    /// </summary>
    public demo.EStatType StatType;
    /// <summary>
    /// 参数0
    /// </summary>
    public string Arg0;
    /// <summary>
    /// 参数1
    /// </summary>
    public string Arg1;
    /// <summary>
    /// 比较
    /// </summary>
    public demo.EStatCompareOp Op;
    /// <summary>
    /// 阈值
    /// </summary>
    public long Value;
   
    public const int __ID__ = 1488164766;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "statType:" + StatType + ","
        + "arg0:" + Arg0 + ","
        + "arg1:" + Arg1 + ","
        + "op:" + Op + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

