
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class EventGrant : Luban.BeanBase
{
    public EventGrant(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["deliver_mode"].IsNumber) { throw new SerializationException(); }  DeliverMode = (demo.EEventGrantDeliverMode)_buf["deliver_mode"].AsInt; }
        { if(!_buf["category"].IsNumber) { throw new SerializationException(); }  Category = (demo.EEventGrantCategory)_buf["category"].AsInt; }
        { var __json0 = _buf["enable_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } EnableConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  EnableConds.Add(__v0); }   }
        { var __json0 = _buf["targets"]; if(!__json0.IsArray) { throw new SerializationException(); } Targets = new System.Collections.Generic.List<demo.EventGrantTarget>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.EventGrantTarget __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.EventGrantTarget.DeserializeEventGrantTarget(__e0);  }  Targets.Add(__v0); }   }
        { var __json0 = _buf["rewards"]; if(!__json0.IsArray) { throw new SerializationException(); } Rewards = new System.Collections.Generic.Dictionary<string, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Rewards.Add(_k0, _v0); }   }
        { if(!_buf["passive_id"].IsString) { throw new SerializationException(); }  PassiveId = _buf["passive_id"]; }
        { var __json0 = _buf["stat_bonuses"]; if(!__json0.IsArray) { throw new SerializationException(); } StatBonuses = new System.Collections.Generic.List<demo.TalentStatBonus>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.TalentStatBonus __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.TalentStatBonus.DeserializeTalentStatBonus(__e0);  }  StatBonuses.Add(__v0); }   }
        { if(!_buf["hidden"].IsBoolean) { throw new SerializationException(); }  Hidden = _buf["hidden"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static EventGrant DeserializeEventGrant(JSONNode _buf)
    {
        return new demo.EventGrant(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public string Id;
    /// <summary>
    /// 兑现模式
    /// </summary>
    public demo.EEventGrantDeliverMode DeliverMode;
    /// <summary>
    /// 分类
    /// </summary>
    public demo.EEventGrantCategory Category;
    /// <summary>
    /// 开放条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> EnableConds;
    /// <summary>
    /// 统计目标
    /// </summary>
    public System.Collections.Generic.List<demo.EventGrantTarget> Targets;
    /// <summary>
    /// 物品奖励
    /// </summary>
    public System.Collections.Generic.Dictionary<string, int> Rewards;
    /// <summary>
    /// 被动技能id
    /// </summary>
    public string PassiveId;
    /// <summary>
    /// 属性加成
    /// </summary>
    public System.Collections.Generic.List<demo.TalentStatBonus> StatBonuses;
    /// <summary>
    /// 隐藏
    /// </summary>
    public bool Hidden;
    /// <summary>
    /// 名称
    /// </summary>
    public string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
   
    public const int __ID__ = -1958121555;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in EnableConds) { _e?.ResolveRef(tables); }
        foreach (var _e in Targets) { _e?.ResolveRef(tables); }
        foreach (var _e in StatBonuses) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "deliverMode:" + DeliverMode + ","
        + "category:" + Category + ","
        + "enableConds:" + Luban.StringUtil.CollectionToString(EnableConds) + ","
        + "targets:" + Luban.StringUtil.CollectionToString(Targets) + ","
        + "rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "passiveId:" + PassiveId + ","
        + "statBonuses:" + Luban.StringUtil.CollectionToString(StatBonuses) + ","
        + "hidden:" + Hidden + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "}";
    }
}
}

