
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.demo
{ 
    /// <summary>
    /// 玩家养成聚合属性
    /// </summary>
    public enum EYCAttribute
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 秘密槽位
        /// </summary>
        SecretSlot = 1,
        /// <summary>
        /// 内在魅力
        /// </summary>
        InnerCharm = 2,
        /// <summary>
        /// 固定魅力
        /// </summary>
        StaticCharm = 3,
        /// <summary>
        /// 内在力量
        /// </summary>
        InnerArm = 4,
        /// <summary>
        /// 固定力量
        /// </summary>
        StaticArm = 5,
        /// <summary>
        /// 额外精元槽位
        /// </summary>
        ExtraJingYuanSlot = 6,
        /// <summary>
        /// 调精槽位上限
        /// </summary>
        TiaoJingSlotCap = 7,
        /// <summary>
        /// 植物背包槽位
        /// </summary>
        PlantBagSlots = 8,
        /// <summary>
        /// 钥匙背包槽位
        /// </summary>
        KeyBagSlots = 9,
        /// <summary>
        /// 药水背包槽位
        /// </summary>
        PotionBagSlots = 10,
        /// <summary>
        /// 最终固定减伤
        /// </summary>
        FixDmgReduceFinal = 11,
        /// <summary>
        /// 固定堕落增加
        /// </summary>
        FixFallenAdd = 12,
        /// <summary>
        /// 主背包额外槽位
        /// </summary>
        MainBagSlots = 13,
        /// <summary>
        /// 秘密背包额外槽位
        /// </summary>
        SecretBagSlots = 14,
        /// <summary>
        /// 宠物背包额外槽位（预留）
        /// </summary>
        PetBagSlots = 15,
        /// <summary>
        /// 精神背包额外槽位
        /// </summary>
        MindBagSlots = 16,
        /// <summary>
        /// 重要物品背包额外槽位
        /// </summary>
        ImportantBagSlots = 17,
        /// <summary>
        /// 通用仓库额外槽位
        /// </summary>
        CommonStorageSlots = 18,
        /// <summary>
        /// 家具仓库额外槽位
        /// </summary>
        FurnitureStorageSlots = 19,
        /// <summary>
        /// 肉体强度
        /// </summary>
        PhysicalPower = 20,
        /// <summary>
        /// 肉体耐受
        /// </summary>
        PhysicalResist = 21,
        /// <summary>
        /// 口部装备点
        /// </summary>
        PartGearPoint_Mouth = 100,
        /// <summary>
        /// 胸部装备点
        /// </summary>
        PartGearPoint_Breast = 101,
        /// <summary>
        /// 子宫装备点
        /// </summary>
        PartGearPoint_Womb = 102,
        /// <summary>
        /// 尾部装备点
        /// </summary>
        PartGearPoint_Tail = 103,
        /// <summary>
        /// 翅膀装备点
        /// </summary>
        PartGearPoint_Wing = 104,
        /// <summary>
        /// 皮肤装备点
        /// </summary>
        PartGearPoint_Skin = 105,
    }

} 

