
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class FacilityRenovation : Luban.BeanBase
{
    public FacilityRenovation(JSONNode _buf) 
    {
        { if(!_buf["facility_cfg_id"].IsString) { throw new SerializationException(); }  FacilityCfgId = _buf["facility_cfg_id"]; }
        { if(!_buf["renovation_id"].IsString) { throw new SerializationException(); }  RenovationId = _buf["renovation_id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["min_level"].IsNumber) { throw new SerializationException(); }  MinLevel = _buf["min_level"]; }
        { if(!_buf["sort_order"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["sort_order"]; }
        { var __json0 = _buf["unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  UnlockConds.Add(__v0); }   }
        { var __json0 = _buf["learn_costs"]; if(!__json0.IsArray) { throw new SerializationException(); } LearnCosts = new System.Collections.Generic.List<demo.TalentUnlockCost>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.TalentUnlockCost __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.TalentUnlockCost.DeserializeTalentUnlockCost(__e0);  }  LearnCosts.Add(__v0); }   }
        { var __json0 = _buf["daily_outputs"]; if(!__json0.IsArray) { throw new SerializationException(); } DailyOutputs = new System.Collections.Generic.List<demo.TalentUnlockCost>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.TalentUnlockCost __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.TalentUnlockCost.DeserializeTalentUnlockCost(__e0);  }  DailyOutputs.Add(__v0); }   }
        { var __json0 = _buf["effects"]; if(!__json0.IsArray) { throw new SerializationException(); } Effects = new System.Collections.Generic.List<demo.FacilityEffect>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.FacilityEffect __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.FacilityEffect.DeserializeFacilityEffect(__e0);  }  Effects.Add(__v0); }   }
    }

    public static FacilityRenovation DeserializeFacilityRenovation(JSONNode _buf)
    {
        return new demo.FacilityRenovation(_buf);
    }

    /// <summary>
    /// 设施cfgid
    /// </summary>
    public string FacilityCfgId;
    /// <summary>
    /// 改造项id
    /// </summary>
    public string RenovationId;
    /// <summary>
    /// 显示名
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
    /// <summary>
    /// 最低建筑等级
    /// </summary>
    public int MinLevel;
    /// <summary>
    /// 排序
    /// </summary>
    public int SortOrder;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> UnlockConds;
    /// <summary>
    /// 学习消耗
    /// </summary>
    public System.Collections.Generic.List<demo.TalentUnlockCost> LearnCosts;
    /// <summary>
    /// 每日产出
    /// </summary>
    public System.Collections.Generic.List<demo.TalentUnlockCost> DailyOutputs;
    /// <summary>
    /// 建筑和文明属性效果
    /// </summary>
    public System.Collections.Generic.List<demo.FacilityEffect> Effects;
   
    public const int __ID__ = 1335826817;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UnlockConds) { _e?.ResolveRef(tables); }
        foreach (var _e in LearnCosts) { _e?.ResolveRef(tables); }
        foreach (var _e in DailyOutputs) { _e?.ResolveRef(tables); }
        foreach (var _e in Effects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "facilityCfgId:" + FacilityCfgId + ","
        + "renovationId:" + RenovationId + ","
        + "displayName:" + DisplayName + ","
        + "desc:" + Desc + ","
        + "minLevel:" + MinLevel + ","
        + "sortOrder:" + SortOrder + ","
        + "unlockConds:" + Luban.StringUtil.CollectionToString(UnlockConds) + ","
        + "learnCosts:" + Luban.StringUtil.CollectionToString(LearnCosts) + ","
        + "dailyOutputs:" + Luban.StringUtil.CollectionToString(DailyOutputs) + ","
        + "effects:" + Luban.StringUtil.CollectionToString(Effects) + ","
        + "}";
    }
}
}

