
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class FacilityDevelopmentLevel : Luban.BeanBase
{
    public FacilityDevelopmentLevel(JSONNode _buf) 
    {
        { if(!_buf["facility_id"].IsString) { throw new SerializationException(); }  FacilityId = _buf["facility_id"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  UnlockConds.Add(__v0); }   }
        { var __json0 = _buf["unlock_costs"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockCosts = new System.Collections.Generic.List<demo.TalentUnlockCost>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.TalentUnlockCost __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.TalentUnlockCost.DeserializeTalentUnlockCost(__e0);  }  UnlockCosts.Add(__v0); }   }
        { var __json0 = _buf["daily_outputs"]; if(!__json0.IsArray) { throw new SerializationException(); } DailyOutputs = new System.Collections.Generic.List<demo.TalentUnlockCost>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.TalentUnlockCost __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.TalentUnlockCost.DeserializeTalentUnlockCost(__e0);  }  DailyOutputs.Add(__v0); }   }
    }

    public static FacilityDevelopmentLevel DeserializeFacilityDevelopmentLevel(JSONNode _buf)
    {
        return new demo.FacilityDevelopmentLevel(_buf);
    }

    /// <summary>
    /// 设施cfgid
    /// </summary>
    public string FacilityId;
    /// <summary>
    /// 目标等级
    /// </summary>
    public int Level;
    /// <summary>
    /// 升级名
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> UnlockConds;
    /// <summary>
    /// 消耗
    /// </summary>
    public System.Collections.Generic.List<demo.TalentUnlockCost> UnlockCosts;
    /// <summary>
    /// 每日产出
    /// </summary>
    public System.Collections.Generic.List<demo.TalentUnlockCost> DailyOutputs;
   
    public const int __ID__ = 2063890839;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UnlockConds) { _e?.ResolveRef(tables); }
        foreach (var _e in UnlockCosts) { _e?.ResolveRef(tables); }
        foreach (var _e in DailyOutputs) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "facilityId:" + FacilityId + ","
        + "level:" + Level + ","
        + "displayName:" + DisplayName + ","
        + "desc:" + Desc + ","
        + "unlockConds:" + Luban.StringUtil.CollectionToString(UnlockConds) + ","
        + "unlockCosts:" + Luban.StringUtil.CollectionToString(UnlockCosts) + ","
        + "dailyOutputs:" + Luban.StringUtil.CollectionToString(DailyOutputs) + ","
        + "}";
    }
}
}

