
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class FacilityEffect : Luban.BeanBase
{
    public FacilityEffect(JSONNode _buf) 
    {
        { if(!_buf["effect_type"].IsNumber) { throw new SerializationException(); }  EffectType = (demo.EFacilityEffectType)_buf["effect_type"].AsInt; }
        { if(!_buf["target_facility_id"].IsString) { throw new SerializationException(); }  TargetFacilityId = _buf["target_facility_id"]; }
        { if(!_buf["building_attr"].IsNumber) { throw new SerializationException(); }  BuildingAttr = (demo.EBuildingAttribute)_buf["building_attr"].AsInt; }
        { if(!_buf["human_attr"].IsNumber) { throw new SerializationException(); }  HumanAttr = (demo.EHumanCivilizationAttribute)_buf["human_attr"].AsInt; }
        { if(!_buf["value"].IsNumber) { throw new SerializationException(); }  Value = _buf["value"]; }
    }

    public static FacilityEffect DeserializeFacilityEffect(JSONNode _buf)
    {
        return new demo.FacilityEffect(_buf);
    }

    public demo.EFacilityEffectType EffectType;
    public string TargetFacilityId;
    public demo.EBuildingAttribute BuildingAttr;
    public demo.EHumanCivilizationAttribute HumanAttr;
    public int Value;
   
    public const int __ID__ = -883273313;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "effectType:" + EffectType + ","
        + "targetFacilityId:" + TargetFacilityId + ","
        + "buildingAttr:" + BuildingAttr + ","
        + "humanAttr:" + HumanAttr + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

