
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class FarmPlot : Luban.BeanBase
{
    public FarmPlot(JSONNode _buf) 
    {
        { if(!_buf["plot_id"].IsString) { throw new SerializationException(); }  PlotId = _buf["plot_id"]; }
        { if(!_buf["logic_area_id"].IsString) { throw new SerializationException(); }  LogicAreaId = _buf["logic_area_id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["cell_size"].IsNumber) { throw new SerializationException(); }  CellSize = _buf["cell_size"]; }
        { if(!_buf["cells"].IsString) { throw new SerializationException(); }  Cells = _buf["cells"]; }
        { if(!_buf["show_var"].IsString) { throw new SerializationException(); }  ShowVar = _buf["show_var"]; }
        { if(!_buf["sort_order"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["sort_order"]; }
    }

    public static FarmPlot DeserializeFarmPlot(JSONNode _buf)
    {
        return new demo.FarmPlot(_buf);
    }

    /// <summary>
    /// 田块ID
    /// </summary>
    public string PlotId;
    /// <summary>
    /// 逻辑地图
    /// </summary>
    public string LogicAreaId;
    /// <summary>
    /// 显示名
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 格子尺寸
    /// </summary>
    public float CellSize;
    /// <summary>
    /// 格偏移 x,y|...
    /// </summary>
    public string Cells;
    /// <summary>
    /// 显示所需变量
    /// </summary>
    public string ShowVar;
    /// <summary>
    /// 排序
    /// </summary>
    public int SortOrder;
   
    public const int __ID__ = 1699091970;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "plotId:" + PlotId + ","
        + "logicAreaId:" + LogicAreaId + ","
        + "displayName:" + DisplayName + ","
        + "cellSize:" + CellSize + ","
        + "cells:" + Cells + ","
        + "showVar:" + ShowVar + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

