
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class FishingSpotFish : Luban.BeanBase
{
    public FishingSpotFish(JSONNode _buf) 
    {
        { if(!_buf["line_id"].IsNumber) { throw new SerializationException(); }  LineId = _buf["line_id"]; }
        { if(!_buf["spot_id"].IsString) { throw new SerializationException(); }  SpotId = _buf["spot_id"]; }
        { if(!_buf["fish_item_id"].IsString) { throw new SerializationException(); }  FishItemId = _buf["fish_item_id"]; }
        { var __json0 = _buf["unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  UnlockConds.Add(__v0); }   }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
    }

    public static FishingSpotFish DeserializeFishingSpotFish(JSONNode _buf)
    {
        return new demo.FishingSpotFish(_buf);
    }

    /// <summary>
    /// 行主键，全表唯一
    /// </summary>
    public int LineId;
    /// <summary>
    /// 关联 fishing_spot.id
    /// </summary>
    public string SpotId;
    /// <summary>
    /// 钓到的道具/鱼 item id
    /// </summary>
    public string FishItemId;
    /// <summary>
    /// 解锁条件列表，空单元或单条 None 条件表示无限制（与 dream unlock_conds 填法一致）
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> UnlockConds;
    /// <summary>
    /// 权重（仅对已解锁条目参与加权）
    /// </summary>
    public int Weight;
   
    public const int __ID__ = -1779000071;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UnlockConds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "lineId:" + LineId + ","
        + "spotId:" + SpotId + ","
        + "fishItemId:" + FishItemId + ","
        + "unlockConds:" + Luban.StringUtil.CollectionToString(UnlockConds) + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

