
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class FishingSpot : Luban.BeanBase
{
    public FishingSpot(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["prefab_path"].IsString) { throw new SerializationException(); }  PrefabPath = _buf["prefab_path"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["capacity"].IsNumber) { throw new SerializationException(); }  Capacity = _buf["capacity"]; }
        { if(!_buf["restock_every_n_days"].IsNumber) { throw new SerializationException(); }  RestockEveryNDays = _buf["restock_every_n_days"]; }
    }

    public static FishingSpot DeserializeFishingSpot(JSONNode _buf)
    {
        return new demo.FishingSpot(_buf);
    }

    /// <summary>
    /// 钓点配置 id，与地图 InitInfo.CfgId 一致
    /// </summary>
    public string Id;
    /// <summary>
    /// 相对路径
    /// </summary>
    public string PrefabPath;
    /// <summary>
    /// 显示名
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 可钓次数上限
    /// </summary>
    public int Capacity;
    /// <summary>
    /// 每多少个结算日补满容量
    /// </summary>
    public int RestockEveryNDays;
   
    public const int __ID__ = -1282630911;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "prefabPath:" + PrefabPath + ","
        + "displayName:" + DisplayName + ","
        + "capacity:" + Capacity + ","
        + "restockEveryNDays:" + RestockEveryNDays + ","
        + "}";
    }
}
}

