
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class ForgeRecipe : Luban.BeanBase
{
    public ForgeRecipe(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["recipe_type"].IsNumber) { throw new SerializationException(); }  RecipeType = (demo.EForgeRecipeType)_buf["recipe_type"].AsInt; }
        { if(!_buf["sort"].IsNumber) { throw new SerializationException(); }  Sort = _buf["sort"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["result_item_id"].IsString) { throw new SerializationException(); }  ResultItemId = _buf["result_item_id"]; }
        { if(!_buf["icon_sprite"].IsString) { throw new SerializationException(); }  IconSprite = _buf["icon_sprite"]; }
        { var __json0 = _buf["materials"]; if(!__json0.IsArray) { throw new SerializationException(); } Materials = new System.Collections.Generic.List<demo.ForgeMaterialCost>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.ForgeMaterialCost __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.ForgeMaterialCost.DeserializeForgeMaterialCost(__e0);  }  Materials.Add(__v0); }   }
        { if(!_buf["unlock_mode"].IsNumber) { throw new SerializationException(); }  UnlockMode = (demo.EForgeUnlockMode)_buf["unlock_mode"].AsInt; }
        { if(!_buf["unlock_param"].IsString) { throw new SerializationException(); }  UnlockParam = _buf["unlock_param"]; }
        { if(!_buf["unlock_item_min_count"].IsNumber) { throw new SerializationException(); }  UnlockItemMinCount = _buf["unlock_item_min_count"]; }
    }

    public static ForgeRecipe DeserializeForgeRecipe(JSONNode _buf)
    {
        return new demo.ForgeRecipe(_buf);
    }

    public int Id;
    public demo.EForgeRecipeType RecipeType;
    public int Sort;
    public string DisplayName;
    public string ResultItemId;
    public string IconSprite;
    /// <summary>
    /// item_id,count 用|分隔多条
    /// </summary>
    public System.Collections.Generic.List<demo.ForgeMaterialCost> Materials;
    public demo.EForgeUnlockMode UnlockMode;
    /// <summary>
    /// 任务id/全局开关名/道具或item|数
    /// </summary>
    public string UnlockParam;
    public long UnlockItemMinCount;
   
    public const int __ID__ = 1839858730;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Materials) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "recipeType:" + RecipeType + ","
        + "sort:" + Sort + ","
        + "displayName:" + DisplayName + ","
        + "resultItemId:" + ResultItemId + ","
        + "iconSprite:" + IconSprite + ","
        + "materials:" + Luban.StringUtil.CollectionToString(Materials) + ","
        + "unlockMode:" + UnlockMode + ","
        + "unlockParam:" + UnlockParam + ","
        + "unlockItemMinCount:" + UnlockItemMinCount + ","
        + "}";
    }
}
}

