
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class ForgeMaterialCost : Luban.BeanBase
{
    public ForgeMaterialCost(JSONNode _buf) 
    {
        { if(!_buf["item_id"].IsString) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
    }

    public static ForgeMaterialCost DeserializeForgeMaterialCost(JSONNode _buf)
    {
        return new demo.ForgeMaterialCost(_buf);
    }

    /// <summary>
    /// 材料道具 id
    /// </summary>
    public string ItemId;
    /// <summary>
    /// 数量
    /// </summary>
    public long Count;
   
    public const int __ID__ = 160687920;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "count:" + Count + ","
        + "}";
    }
}
}

