
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class HActInfo : Luban.BeanBase
{
    public HActInfo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["filter_types"]; if(!__json0.IsArray) { throw new SerializationException(); } FilterTypes = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  FilterTypes.Add(__v0); }   }
        { if(!_buf["player_min_desire"].IsNumber) { throw new SerializationException(); }  PlayerMinDesire = _buf["player_min_desire"]; }
        { if(!_buf["is_player_passive"].IsBoolean) { throw new SerializationException(); }  IsPlayerPassive = _buf["is_player_passive"]; }
        { if(!_buf["h_impulse_base"].IsNumber) { throw new SerializationException(); }  HImpulseBase = _buf["h_impulse_base"]; }
        { if(!_buf["self_coef"].IsNumber) { throw new SerializationException(); }  SelfCoef = _buf["self_coef"]; }
        { if(!_buf["contest_coef"].IsNumber) { throw new SerializationException(); }  ContestCoef = _buf["contest_coef"]; }
        { if(!_buf["hp_from_impulse_coef"].IsNumber) { throw new SerializationException(); }  HpFromImpulseCoef = _buf["hp_from_impulse_coef"]; }
        { if(!_buf["player_climax_weight"].IsNumber) { throw new SerializationException(); }  PlayerClimaxWeight = _buf["player_climax_weight"]; }
    }

    public static HActInfo DeserializeHActInfo(JSONNode _buf)
    {
        return new demo.HActInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
    /// <summary>
    /// 筛选类型
    /// </summary>
    public System.Collections.Generic.List<string> FilterTypes;
    /// <summary>
    /// 欲望要求
    /// </summary>
    public int PlayerMinDesire;
    /// <summary>
    /// 主角被动
    /// </summary>
    public bool IsPlayerPassive;
    /// <summary>
    /// 动作基础强度
    /// </summary>
    public float HImpulseBase;
    /// <summary>
    /// 自反馈系数
    /// </summary>
    public float SelfCoef;
    /// <summary>
    /// 对抗姿态
    /// </summary>
    public float ContestCoef;
    /// <summary>
    /// 冲击折血系数
    /// </summary>
    public float HpFromImpulseCoef;
    /// <summary>
    /// 高潮权重
    /// </summary>
    public float PlayerClimaxWeight;
   
    public const int __ID__ = 2131219107;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "filterTypes:" + Luban.StringUtil.CollectionToString(FilterTypes) + ","
        + "playerMinDesire:" + PlayerMinDesire + ","
        + "isPlayerPassive:" + IsPlayerPassive + ","
        + "hImpulseBase:" + HImpulseBase + ","
        + "selfCoef:" + SelfCoef + ","
        + "contestCoef:" + ContestCoef + ","
        + "hpFromImpulseCoef:" + HpFromImpulseCoef + ","
        + "playerClimaxWeight:" + PlayerClimaxWeight + ","
        + "}";
    }
}
}

