
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class HActInfo : Luban.BeanBase
{
    public HActInfo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["filter_type"].IsString) { throw new SerializationException(); }  FilterType = _buf["filter_type"]; }
        { if(!_buf["player_min_desire"].IsNumber) { throw new SerializationException(); }  PlayerMinDesire = _buf["player_min_desire"]; }
        { if(!_buf["is_player_passive"].IsBoolean) { throw new SerializationException(); }  IsPlayerPassive = _buf["is_player_passive"]; }
        { if(!_buf["h_impulse_base"].IsNumber) { throw new SerializationException(); }  HImpulseBase = _buf["h_impulse_base"]; }
        { if(!_buf["coef_player"].IsNumber) { throw new SerializationException(); }  CoefPlayer = _buf["coef_player"]; }
        { if(!_buf["coef_enemy"].IsNumber) { throw new SerializationException(); }  CoefEnemy = _buf["coef_enemy"]; }
        { if(!_buf["player_climax_weight"].IsNumber) { throw new SerializationException(); }  PlayerClimaxWeight = _buf["player_climax_weight"]; }
    }

    public static HActInfo DeserializeHActInfo(JSONNode _buf)
    {
        return new demo.HActInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id;
    /// <summary>
    /// id
    /// </summary>
    public string Desc;
    /// <summary>
    /// 筛选类型
    /// </summary>
    public string FilterType;
    /// <summary>
    /// 玩家欲望要求
    /// </summary>
    public int PlayerMinDesire;
    /// <summary>
    /// 主角被动？
    /// </summary>
    public bool IsPlayerPassive;
    /// <summary>
    /// h冲击力
    /// </summary>
    public float HImpulseBase;
    /// <summary>
    /// h比例
    /// </summary>
    public float CoefPlayer;
    /// <summary>
    /// h比例
    /// </summary>
    public float CoefEnemy;
    /// <summary>
    /// 高潮比例
    /// </summary>
    public float PlayerClimaxWeight;
   
    public const int __ID__ = 2131219107;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "filterType:" + FilterType + ","
        + "playerMinDesire:" + PlayerMinDesire + ","
        + "isPlayerPassive:" + IsPlayerPassive + ","
        + "hImpulseBase:" + HImpulseBase + ","
        + "coefPlayer:" + CoefPlayer + ","
        + "coefEnemy:" + CoefEnemy + ","
        + "playerClimaxWeight:" + PlayerClimaxWeight + ","
        + "}";
    }
}
}

