
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class HumanTechNode : Luban.BeanBase
{
    public HumanTechNode(JSONNode _buf) 
    {
        { if(!_buf["tech_tree_id"].IsString) { throw new SerializationException(); }  TechTreeId = _buf["tech_tree_id"]; }
        { if(!_buf["node_id"].IsNumber) { throw new SerializationException(); }  NodeId = _buf["node_id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["max_level"].IsNumber) { throw new SerializationException(); }  MaxLevel = _buf["max_level"]; }
        { if(!_buf["required_civilization_level"].IsNumber) { throw new SerializationException(); }  RequiredCivilizationLevel = _buf["required_civilization_level"]; }
        { if(!_buf["icon_path"].IsString) { throw new SerializationException(); }  IconPath = _buf["icon_path"]; }
        { if(!_buf["pos_x"].IsNumber) { throw new SerializationException(); }  PosX = _buf["pos_x"]; }
        { if(!_buf["pos_y"].IsNumber) { throw new SerializationException(); }  PosY = _buf["pos_y"]; }
    }

    public static HumanTechNode DeserializeHumanTechNode(JSONNode _buf)
    {
        return new demo.HumanTechNode(_buf);
    }

    /// <summary>
    /// ?????
    /// </summary>
    public string TechTreeId;
    /// <summary>
    /// node_id
    /// </summary>
    public int NodeId;
    /// <summary>
    /// ????
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// ????
    /// </summary>
    public int MaxLevel;
    /// <summary>
    /// 1
    /// </summary>
    public int RequiredCivilizationLevel;
    /// <summary>
    /// ????
    /// </summary>
    public string IconPath;
    /// <summary>
    /// ????X
    /// </summary>
    public int PosX;
    /// <summary>
    /// ????Y
    /// </summary>
    public int PosY;
   
    public const int __ID__ = 440815898;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "techTreeId:" + TechTreeId + ","
        + "nodeId:" + NodeId + ","
        + "displayName:" + DisplayName + ","
        + "maxLevel:" + MaxLevel + ","
        + "requiredCivilizationLevel:" + RequiredCivilizationLevel + ","
        + "iconPath:" + IconPath + ","
        + "posX:" + PosX + ","
        + "posY:" + PosY + ","
        + "}";
    }
}
}

