
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class HumanTechTree : Luban.BeanBase
{
    public HumanTechTree(JSONNode _buf) 
    {
        { if(!_buf["tree_id"].IsString) { throw new SerializationException(); }  TreeId = _buf["tree_id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["layout_prefab_path"].IsString) { throw new SerializationException(); }  LayoutPrefabPath = _buf["layout_prefab_path"]; }
        { if(!_buf["owner_character_key"].IsString) { throw new SerializationException(); }  OwnerCharacterKey = _buf["owner_character_key"]; }
    }

    public static HumanTechTree DeserializeHumanTechTree(JSONNode _buf)
    {
        return new demo.HumanTechTree(_buf);
    }

    /// <summary>
    /// ???id
    /// </summary>
    public string TreeId;
    /// <summary>
    /// ???
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// ???????
    /// </summary>
    public string LayoutPrefabPath;
    /// <summary>
    /// ????key
    /// </summary>
    public string OwnerCharacterKey;
   
    public const int __ID__ = 440997558;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "treeId:" + TreeId + ","
        + "displayName:" + DisplayName + ","
        + "layoutPrefabPath:" + LayoutPrefabPath + ","
        + "ownerCharacterKey:" + OwnerCharacterKey + ","
        + "}";
    }
}
}

