
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class HumanWeapon : Luban.BeanBase
{
    public HumanWeapon(JSONNode _buf) 
    {
        { if(!_buf["item_id"].IsString) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { if(!_buf["func_type"].IsNumber) { throw new SerializationException(); }  FuncType = (demo.EHumanWeaponFuncType)_buf["func_type"].AsInt; }
        { if(!_buf["skill_id"].IsString) { throw new SerializationException(); }  SkillId = _buf["skill_id"]; }
        { if(!_buf["view_prefab"].IsString) { throw new SerializationException(); }  ViewPrefab = _buf["view_prefab"]; }
        { if(!_buf["view_sprite"].IsString) { throw new SerializationException(); }  ViewSprite = _buf["view_sprite"]; }
        { if(!_buf["anim_name"].IsString) { throw new SerializationException(); }  AnimName = _buf["anim_name"]; }
        { if(!_buf["weapon_level"].IsNumber) { throw new SerializationException(); }  WeaponLevel = _buf["weapon_level"]; }
        { if(!_buf["stun_value"].IsNumber) { throw new SerializationException(); }  StunValue = _buf["stun_value"]; }
        { if(!_buf["bullet_id"].IsString) { throw new SerializationException(); }  BulletId = _buf["bullet_id"]; }
        { if(!_buf["weapon_subtype"].IsString) { throw new SerializationException(); }  WeaponSubtype = _buf["weapon_subtype"]; }
        { if(!_buf["affix_pool_id"].IsString) { throw new SerializationException(); }  AffixPoolId = _buf["affix_pool_id"]; }
        { if(!_buf["affix_min_count"].IsNumber) { throw new SerializationException(); }  AffixMinCount = _buf["affix_min_count"]; }
        { if(!_buf["affix_max_count"].IsNumber) { throw new SerializationException(); }  AffixMaxCount = _buf["affix_max_count"]; }
    }

    public static HumanWeapon DeserializeHumanWeapon(JSONNode _buf)
    {
        return new demo.HumanWeapon(_buf);
    }

    /// <summary>
    /// item_id
    /// </summary>
    public string ItemId;
    /// <summary>
    /// func_type
    /// </summary>
    public demo.EHumanWeaponFuncType FuncType;
    /// <summary>
    /// skill_id
    /// </summary>
    public string SkillId;
    /// <summary>
    /// view_prefab
    /// </summary>
    public string ViewPrefab;
    /// <summary>
    /// view_sprite
    /// </summary>
    public string ViewSprite;
    /// <summary>
    /// anim_name
    /// </summary>
    public string AnimName;
    /// <summary>
    /// weapon_level
    /// </summary>
    public int WeaponLevel;
    /// <summary>
    /// stun_value
    /// </summary>
    public long StunValue;
    /// <summary>
    /// bullet_id
    /// </summary>
    public string BulletId;
    /// <summary>
    /// 武器子类型
    /// </summary>
    public string WeaponSubtype;
    /// <summary>
    /// 词条池
    /// </summary>
    public string AffixPoolId;
    /// <summary>
    /// 最少词条数量
    /// </summary>
    public int AffixMinCount;
    /// <summary>
    /// 最多词条数量
    /// </summary>
    public int AffixMaxCount;
   
    public const int __ID__ = -517056002;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "funcType:" + FuncType + ","
        + "skillId:" + SkillId + ","
        + "viewPrefab:" + ViewPrefab + ","
        + "viewSprite:" + ViewSprite + ","
        + "animName:" + AnimName + ","
        + "weaponLevel:" + WeaponLevel + ","
        + "stunValue:" + StunValue + ","
        + "bulletId:" + BulletId + ","
        + "weaponSubtype:" + WeaponSubtype + ","
        + "affixPoolId:" + AffixPoolId + ","
        + "affixMinCount:" + AffixMinCount + ","
        + "affixMaxCount:" + AffixMaxCount + ","
        + "}";
    }
}
}

