
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class HumanTechNodeLevel : Luban.BeanBase
{
    public HumanTechNodeLevel(JSONNode _buf) 
    {
        { if(!_buf["node_id"].IsNumber) { throw new SerializationException(); }  NodeId = _buf["node_id"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { var __json0 = _buf["prereq_node_ids"]; if(!__json0.IsArray) { throw new SerializationException(); } PrereqNodeIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  PrereqNodeIds.Add(__v0); }   }
        { var __json0 = _buf["unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  UnlockConds.Add(__v0); }   }
        { var __json0 = _buf["unlock_costs"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockCosts = new System.Collections.Generic.List<demo.TalentUnlockCost>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.TalentUnlockCost __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.TalentUnlockCost.DeserializeTalentUnlockCost(__e0);  }  UnlockCosts.Add(__v0); }   }
        { if(!_buf["effect_key"].IsNumber) { throw new SerializationException(); }  EffectKey = (demo.EHumanCivilizationAttribute)_buf["effect_key"].AsInt; }
        { if(!_buf["effect_value"].IsNumber) { throw new SerializationException(); }  EffectValue = _buf["effect_value"]; }
    }

    public static HumanTechNodeLevel DeserializeHumanTechNodeLevel(JSONNode _buf)
    {
        return new demo.HumanTechNodeLevel(_buf);
    }

    /// <summary>
    /// node_id
    /// </summary>
    public int NodeId;
    /// <summary>
    /// level
    /// </summary>
    public int Level;
    /// <summary>
    /// ????
    /// </summary>
    public System.Collections.Generic.List<int> PrereqNodeIds;
    /// <summary>
    /// CommonCheck??
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> UnlockConds;
    /// <summary>
    /// ????
    /// </summary>
    public System.Collections.Generic.List<demo.TalentUnlockCost> UnlockCosts;
    /// <summary>
    /// ??????
    /// </summary>
    public demo.EHumanCivilizationAttribute EffectKey;
    /// <summary>
    /// ???
    /// </summary>
    public long EffectValue;
   
    public const int __ID__ = -893322614;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UnlockConds) { _e?.ResolveRef(tables); }
        foreach (var _e in UnlockCosts) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "nodeId:" + NodeId + ","
        + "level:" + Level + ","
        + "prereqNodeIds:" + Luban.StringUtil.CollectionToString(PrereqNodeIds) + ","
        + "unlockConds:" + Luban.StringUtil.CollectionToString(UnlockConds) + ","
        + "unlockCosts:" + Luban.StringUtil.CollectionToString(UnlockCosts) + ","
        + "effectKey:" + EffectKey + ","
        + "effectValue:" + EffectValue + ","
        + "}";
    }
}
}

