
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class HumanCivilizationLevel : Luban.BeanBase
{
    public HumanCivilizationLevel(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  UnlockConds.Add(__v0); }   }
        { var __json0 = _buf["custom_unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } CustomUnlockConds = new System.Collections.Generic.List<demo.HumanCivilizationCustomCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.HumanCivilizationCustomCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.HumanCivilizationCustomCond.DeserializeHumanCivilizationCustomCond(__e0);  }  CustomUnlockConds.Add(__v0); }   }
    }

    public static HumanCivilizationLevel DeserializeHumanCivilizationLevel(JSONNode _buf)
    {
        return new demo.HumanCivilizationLevel(_buf);
    }

    /// <summary>
    /// ????
    /// </summary>
    public int Level;
    /// <summary>
    /// ????
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// ??????????????
    /// </summary>
    public string Desc;
    /// <summary>
    /// CommonCheck????
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> UnlockConds;
    /// <summary>
    /// ??????
    /// </summary>
    public System.Collections.Generic.List<demo.HumanCivilizationCustomCond> CustomUnlockConds;
   
    public const int __ID__ = 316166609;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UnlockConds) { _e?.ResolveRef(tables); }
        foreach (var _e in CustomUnlockConds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "displayName:" + DisplayName + ","
        + "desc:" + Desc + ","
        + "unlockConds:" + Luban.StringUtil.CollectionToString(UnlockConds) + ","
        + "customUnlockConds:" + Luban.StringUtil.CollectionToString(CustomUnlockConds) + ","
        + "}";
    }
}
}

