
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class ItemGift : Luban.BeanBase
{
    public ItemGift(JSONNode _buf) 
    {
        { if(!_buf["item_id"].IsString) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { var __json0 = _buf["gift_tags"]; if(!__json0.IsArray) { throw new SerializationException(); } GiftTags = new System.Collections.Generic.List<demo.EGiftTag>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.EGiftTag __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (demo.EGiftTag)__e0.AsInt; }  GiftTags.Add(__v0); }   }
        { if(!_buf["gift_level"].IsNumber) { throw new SerializationException(); }  GiftLevel = _buf["gift_level"]; }
    }

    public static ItemGift DeserializeItemGift(JSONNode _buf)
    {
        return new demo.ItemGift(_buf);
    }

    /// <summary>
    /// item_id
    /// </summary>
    public string ItemId;
    /// <summary>
    /// gift_tags
    /// </summary>
    public System.Collections.Generic.List<demo.EGiftTag> GiftTags;
    /// <summary>
    /// gift_level
    /// </summary>
    public int GiftLevel;
   
    public const int __ID__ = 1942806190;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "giftTags:" + Luban.StringUtil.CollectionToString(GiftTags) + ","
        + "giftLevel:" + GiftLevel + ","
        + "}";
    }
}
}

