
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class ItemData : Luban.BeanBase
{
    public ItemData(JSONNode _buf) 
    {
        { if(!_buf["item_id"].IsString) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["item_type"].IsNumber) { throw new SerializationException(); }  ItemType = (demo.EItemType)_buf["item_type"].AsInt; }
        { if(!_buf["stackable"].IsBoolean) { throw new SerializationException(); }  Stackable = _buf["stackable"]; }
        { if(!_buf["stack_profile"].IsNumber) { throw new SerializationException(); }  StackProfile = (demo.EItemStackProfile)_buf["stack_profile"].AsInt; }
        { if(!_buf["stack_count"].IsNumber) { throw new SerializationException(); }  StackCount = _buf["stack_count"]; }
        { var __json0 = _buf["tags"]; if(!__json0.IsArray) { throw new SerializationException(); } Tags = new System.Collections.Generic.List<demo.EItemTag>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.EItemTag __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (demo.EItemTag)__e0.AsInt; }  Tags.Add(__v0); }   }
        { if(!_buf["sprite_name"].IsString) { throw new SerializationException(); }  SpriteName = _buf["sprite_name"]; }
        { if(!_buf["can_drop"].IsBoolean) { throw new SerializationException(); }  CanDrop = _buf["can_drop"]; }
        { if(!_buf["rare_tier"].IsNumber) { throw new SerializationException(); }  RareTier = _buf["rare_tier"]; }
        { if(!_buf["reveal_effect_type"].IsNumber) { throw new SerializationException(); }  RevealEffectType = (demo.EItemRevealEffectType)_buf["reveal_effect_type"].AsInt; }
        { if(!_buf["reveal_p1"].IsNumber) { throw new SerializationException(); }  RevealP1 = _buf["reveal_p1"]; }
        { if(!_buf["reveal_p2"].IsNumber) { throw new SerializationException(); }  RevealP2 = _buf["reveal_p2"]; }
        { if(!_buf["auto_destroy"].IsBoolean) { throw new SerializationException(); }  AutoDestroy = _buf["auto_destroy"]; }
        { if(!_buf["auto_destroy_time"].IsNumber) { throw new SerializationException(); }  AutoDestroyTime = _buf["auto_destroy_time"]; }
        { if(!_buf["special_buff_id"].IsString) { throw new SerializationException(); }  SpecialBuffId = _buf["special_buff_id"]; }
        { if(!_buf["special_buff_interval"].IsNumber) { throw new SerializationException(); }  SpecialBuffInterval = _buf["special_buff_interval"]; }
        { if(!_buf["auto_pick"].IsBoolean) { throw new SerializationException(); }  AutoPick = _buf["auto_pick"]; }
        { if(!_buf["is_auto_use"].IsBoolean) { throw new SerializationException(); }  IsAutoUse = _buf["is_auto_use"]; }
        { if(!_buf["can_dismantle"].IsBoolean) { throw new SerializationException(); }  CanDismantle = _buf["can_dismantle"]; }
    }

    public static ItemData DeserializeItemData(JSONNode _buf)
    {
        return new demo.ItemData(_buf);
    }

    /// <summary>
    /// item_id
    /// </summary>
    public string ItemId;
    /// <summary>
    /// display_name
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// item_type
    /// </summary>
    public demo.EItemType ItemType;
    /// <summary>
    /// stackable
    /// </summary>
    public bool Stackable;
    /// <summary>
    /// 非Custom使用通用档位；Custom读取stack_count
    /// </summary>
    public demo.EItemStackProfile StackProfile;
    /// <summary>
    /// stack_count
    /// </summary>
    public int StackCount;
    /// <summary>
    /// 物品语义标签；供容器、Perk和筛选规则匹配
    /// </summary>
    public System.Collections.Generic.List<demo.EItemTag> Tags;
    /// <summary>
    /// sprite_name
    /// </summary>
    public string SpriteName;
    /// <summary>
    /// can_drop
    /// </summary>
    public bool CanDrop;
    /// <summary>
    /// rare_tier
    /// </summary>
    public int RareTier;
    /// <summary>
    /// reveal_effect_type
    /// </summary>
    public demo.EItemRevealEffectType RevealEffectType;
    /// <summary>
    /// reveal_p1
    /// </summary>
    public long RevealP1;
    /// <summary>
    /// reveal_p2
    /// </summary>
    public long RevealP2;
    /// <summary>
    /// auto_destroy
    /// </summary>
    public bool AutoDestroy;
    /// <summary>
    /// 自动销毁时间
    /// </summary>
    public float AutoDestroyTime;
    /// <summary>
    /// 特殊buffid
    /// </summary>
    public string SpecialBuffId;
    /// <summary>
    /// special_buff_interval
    /// </summary>
    public float SpecialBuffInterval;
    /// <summary>
    /// auto_pick
    /// </summary>
    public bool AutoPick;
    /// <summary>
    /// is_auto_use
    /// </summary>
    public bool IsAutoUse;
    /// <summary>
    /// 是否允许进入分解系统；仍需item_dismantle存在对应规则
    /// </summary>
    public bool CanDismantle;
   
    public const int __ID__ = 1942709544;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "displayName:" + DisplayName + ","
        + "itemType:" + ItemType + ","
        + "stackable:" + Stackable + ","
        + "stackProfile:" + StackProfile + ","
        + "stackCount:" + StackCount + ","
        + "tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "spriteName:" + SpriteName + ","
        + "canDrop:" + CanDrop + ","
        + "rareTier:" + RareTier + ","
        + "revealEffectType:" + RevealEffectType + ","
        + "revealP1:" + RevealP1 + ","
        + "revealP2:" + RevealP2 + ","
        + "autoDestroy:" + AutoDestroy + ","
        + "autoDestroyTime:" + AutoDestroyTime + ","
        + "specialBuffId:" + SpecialBuffId + ","
        + "specialBuffInterval:" + SpecialBuffInterval + ","
        + "autoPick:" + AutoPick + ","
        + "isAutoUse:" + IsAutoUse + ","
        + "canDismantle:" + CanDismantle + ","
        + "}";
    }
}
}

