
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class ItemDismantle : Luban.BeanBase
{
    public ItemDismantle(JSONNode _buf) 
    {
        { if(!_buf["item_id"].IsString) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { var __json0 = _buf["outputs"]; if(!__json0.IsArray) { throw new SerializationException(); } Outputs = new System.Collections.Generic.List<demo.ItemAmount>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.ItemAmount __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.ItemAmount.DeserializeItemAmount(__e0);  }  Outputs.Add(__v0); }   }
    }

    public static ItemDismantle DeserializeItemDismantle(JSONNode _buf)
    {
        return new demo.ItemDismantle(_buf);
    }

    /// <summary>
    /// 待分解物品id
    /// </summary>
    public string ItemId;
    /// <summary>
    /// item_id,count；多项用|分隔
    /// </summary>
    public System.Collections.Generic.List<demo.ItemAmount> Outputs;
   
    public const int __ID__ = -185233245;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Outputs) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "outputs:" + Luban.StringUtil.CollectionToString(Outputs) + ","
        + "}";
    }
}
}

