
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class ItemTagInfo : Luban.BeanBase
{
    public ItemTagInfo(JSONNode _buf) 
    {
        { if(!_buf["tag"].IsNumber) { throw new SerializationException(); }  Tag = (demo.EItemTag)_buf["tag"].AsInt; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["hidden"].IsBoolean) { throw new SerializationException(); }  Hidden = _buf["hidden"]; }
        { if(!_buf["requires_instance"].IsBoolean) { throw new SerializationException(); }  RequiresInstance = _buf["requires_instance"]; }
    }

    public static ItemTagInfo DeserializeItemTagInfo(JSONNode _buf)
    {
        return new demo.ItemTagInfo(_buf);
    }

    /// <summary>
    /// tag
    /// </summary>
    public demo.EItemTag Tag;
    /// <summary>
    /// UI显示字
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 是否在UI标签展示中隐藏
    /// </summary>
    public bool Hidden;
    /// <summary>
    /// 是否需要创建实例容器
    /// </summary>
    public bool RequiresInstance;
   
    public const int __ID__ = 1878256938;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "tag:" + Tag + ","
        + "displayName:" + DisplayName + ","
        + "hidden:" + Hidden + ","
        + "requiresInstance:" + RequiresInstance + ","
        + "}";
    }
}
}

