
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class JingYuanEssenceLevelMap : Luban.BeanBase
{
    public JingYuanEssenceLevelMap(JSONNode _buf) 
    {
        { if(!_buf["map_id"].IsString) { throw new SerializationException(); }  MapId = _buf["map_id"]; }
        { if(!_buf["npc_level_min"].IsNumber) { throw new SerializationException(); }  NpcLevelMin = _buf["npc_level_min"]; }
        { if(!_buf["npc_level_max"].IsNumber) { throw new SerializationException(); }  NpcLevelMax = _buf["npc_level_max"]; }
        { if(!_buf["essence_level"].IsNumber) { throw new SerializationException(); }  EssenceLevel = _buf["essence_level"]; }
    }

    public static JingYuanEssenceLevelMap DeserializeJingYuanEssenceLevelMap(JSONNode _buf)
    {
        return new demo.JingYuanEssenceLevelMap(_buf);
    }

    /// <summary>
    /// 映射主键
    /// </summary>
    public string MapId;
    /// <summary>
    /// NPC等级下限
    /// </summary>
    public int NpcLevelMin;
    /// <summary>
    /// NPC等级上限
    /// </summary>
    public int NpcLevelMax;
    /// <summary>
    /// 精华等级
    /// </summary>
    public int EssenceLevel;
   
    public const int __ID__ = 1938563100;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "mapId:" + MapId + ","
        + "npcLevelMin:" + NpcLevelMin + ","
        + "npcLevelMax:" + NpcLevelMax + ","
        + "essenceLevel:" + EssenceLevel + ","
        + "}";
    }
}
}

