
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class JingYuanTypePoolEntry : Luban.BeanBase
{
    public JingYuanTypePoolEntry(JSONNode _buf) 
    {
        { if(!_buf["entry_id"].IsNumber) { throw new SerializationException(); }  EntryId = _buf["entry_id"]; }
        { if(!_buf["pool_id"].IsString) { throw new SerializationException(); }  PoolId = _buf["pool_id"]; }
        { if(!_buf["type_id"].IsString) { throw new SerializationException(); }  TypeId = _buf["type_id"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
    }

    public static JingYuanTypePoolEntry DeserializeJingYuanTypePoolEntry(JSONNode _buf)
    {
        return new demo.JingYuanTypePoolEntry(_buf);
    }

    /// <summary>
    /// entry_id
    /// </summary>
    public int EntryId;
    /// <summary>
    /// pool_id
    /// </summary>
    public string PoolId;
    /// <summary>
    /// type_id
    /// </summary>
    public string TypeId;
    /// <summary>
    /// weight
    /// </summary>
    public int Weight;
   
    public const int __ID__ = 1391425424;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "entryId:" + EntryId + ","
        + "poolId:" + PoolId + ","
        + "typeId:" + TypeId + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

