
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class JingYuanTypePoolEnum : Luban.BeanBase
{
    public JingYuanTypePoolEnum(JSONNode _buf) 
    {
        { if(!_buf["entry_id"].IsNumber) { throw new SerializationException(); }  EntryId = _buf["entry_id"]; }
        { if(!_buf["pool_id"].IsString) { throw new SerializationException(); }  PoolId = _buf["pool_id"]; }
        { if(!_buf["type_id"].IsNumber) { throw new SerializationException(); }  TypeId = (demo.EJingYuanType)_buf["type_id"].AsInt; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
    }

    public static JingYuanTypePoolEnum DeserializeJingYuanTypePoolEnum(JSONNode _buf)
    {
        return new demo.JingYuanTypePoolEnum(_buf);
    }

    /// <summary>
    /// 入口 id
    /// </summary>
    public int EntryId;
    /// <summary>
    /// 精型池
    /// </summary>
    public string PoolId;
    /// <summary>
    /// 精型枚举
    /// </summary>
    public demo.EJingYuanType TypeId;
    /// <summary>
    /// 权重
    /// </summary>
    public int Weight;
   
    public const int __ID__ = 1984547363;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "entryId:" + EntryId + ","
        + "poolId:" + PoolId + ","
        + "typeId:" + TypeId + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

