
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class JingYuanPremiumEffect : Luban.BeanBase
{
    public JingYuanPremiumEffect(JSONNode _buf) 
    {
        { if(!_buf["type_id"].IsNumber) { throw new SerializationException(); }  TypeId = (demo.EJingYuanType)_buf["type_id"].AsInt; }
        { if(!_buf["drop_level"].IsNumber) { throw new SerializationException(); }  DropLevel = _buf["drop_level"]; }
        { if(!_buf["concentration_floor"].IsNumber) { throw new SerializationException(); }  ConcentrationFloor = _buf["concentration_floor"]; }
        { if(!_buf["attr_id"].IsNumber) { throw new SerializationException(); }  AttrId = _buf["attr_id"]; }
        { if(!_buf["attr_value"].IsNumber) { throw new SerializationException(); }  AttrValue = _buf["attr_value"]; }
    }

    public static JingYuanPremiumEffect DeserializeJingYuanPremiumEffect(JSONNode _buf)
    {
        return new demo.JingYuanPremiumEffect(_buf);
    }

    /// <summary>
    /// 精型枚举
    /// </summary>
    public demo.EJingYuanType TypeId;
    /// <summary>
    /// 掉落等级
    /// </summary>
    public int DropLevel;
    /// <summary>
    /// 浓度下限(0-100)
    /// </summary>
    public int ConcentrationFloor;
    /// <summary>
    /// EYCAttribute
    /// </summary>
    public int AttrId;
    /// <summary>
    /// 属性加成
    /// </summary>
    public long AttrValue;
   
    public const int __ID__ = -555136324;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "typeId:" + TypeId + ","
        + "dropLevel:" + DropLevel + ","
        + "concentrationFloor:" + ConcentrationFloor + ","
        + "attrId:" + AttrId + ","
        + "attrValue:" + AttrValue + ","
        + "}";
    }
}
}

