
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class JingYuanCodexLevel : Luban.BeanBase
{
    public JingYuanCodexLevel(JSONNode _buf) 
    {
        { if(!_buf["codex_id"].IsString) { throw new SerializationException(); }  CodexId = _buf["codex_id"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["need_extract_count"].IsNumber) { throw new SerializationException(); }  NeedExtractCount = _buf["need_extract_count"]; }
        { if(!_buf["need_total_amount"].IsNumber) { throw new SerializationException(); }  NeedTotalAmount = _buf["need_total_amount"]; }
        { var __json0 = _buf["stat_bonuses"]; if(!__json0.IsArray) { throw new SerializationException(); } StatBonuses = new System.Collections.Generic.List<demo.TalentStatBonus>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.TalentStatBonus __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.TalentStatBonus.DeserializeTalentStatBonus(__e0);  }  StatBonuses.Add(__v0); }   }
    }

    public static JingYuanCodexLevel DeserializeJingYuanCodexLevel(JSONNode _buf)
    {
        return new demo.JingYuanCodexLevel(_buf);
    }

    /// <summary>
    /// codex_id
    /// </summary>
    public string CodexId;
    /// <summary>
    /// level
    /// </summary>
    public int Level;
    /// <summary>
    /// need_extract_count
    /// </summary>
    public int NeedExtractCount;
    /// <summary>
    /// need_total_amount
    /// </summary>
    public long NeedTotalAmount;
    /// <summary>
    /// stat_bonuses
    /// </summary>
    public System.Collections.Generic.List<demo.TalentStatBonus> StatBonuses;
   
    public const int __ID__ = -1270976859;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in StatBonuses) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "codexId:" + CodexId + ","
        + "level:" + Level + ","
        + "needExtractCount:" + NeedExtractCount + ","
        + "needTotalAmount:" + NeedTotalAmount + ","
        + "statBonuses:" + Luban.StringUtil.CollectionToString(StatBonuses) + ","
        + "}";
    }
}
}

