
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class MapAreaEffect : Luban.BeanBase
{
    public MapAreaEffect(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["shape_type"].IsNumber) { throw new SerializationException(); }  ShapeType = (demo.EAreaShapeType)_buf["shape_type"].AsInt; }
        { if(!_buf["shape_length"].IsNumber) { throw new SerializationException(); }  ShapeLength = _buf["shape_length"]; }
        { if(!_buf["shape_width"].IsNumber) { throw new SerializationException(); }  ShapeWidth = _buf["shape_width"]; }
        { if(!_buf["shape_radius"].IsNumber) { throw new SerializationException(); }  ShapeRadius = _buf["shape_radius"]; }
        { if(!_buf["shape_angle"].IsNumber) { throw new SerializationException(); }  ShapeAngle = _buf["shape_angle"]; }
        { if(!_buf["area_buff_id"].IsString) { throw new SerializationException(); }  AreaBuffId = _buf["area_buff_id"]; }
        { if(!_buf["camp_filter"].IsNumber) { throw new SerializationException(); }  CampFilter = (demo.EAreaCampFilter)_buf["camp_filter"].AsInt; }
        { if(!_buf["default_lifetime"].IsNumber) { throw new SerializationException(); }  DefaultLifetime = _buf["default_lifetime"]; }
        RefreshBuffDuration = _buf["refresh_buff_duration"].IsBoolean && _buf["refresh_buff_duration"].AsBool;
    }

    public static MapAreaEffect DeserializeMapAreaEffect(JSONNode _buf)
    {
        return new demo.MapAreaEffect(_buf);
    }

    /// <summary>
    /// cfgId
    /// </summary>
    public string Id;
    /// <summary>
    /// 形状
    /// </summary>
    public demo.EAreaShapeType ShapeType;
    /// <summary>
    /// 长/方盒X
    /// </summary>
    public float ShapeLength;
    /// <summary>
    /// 方盒Y
    /// </summary>
    public float ShapeWidth;
    /// <summary>
    /// 圆半径
    /// </summary>
    public float ShapeRadius;
    /// <summary>
    /// 扇形角
    /// </summary>
    public float ShapeAngle;
    /// <summary>
    /// 区内 Buff
    /// </summary>
    public string AreaBuffId;
    /// <summary>
    /// 阵营过滤
    /// </summary>
    public demo.EAreaCampFilter CampFilter;
    /// <summary>
    /// 默认寿命秒
    /// </summary>
    public float DefaultLifetime;
    /// <summary>
    /// true：区内每 tick 刷新 Buff 时长，离区不 Remove（Buff 需自带 DefaultDuration）
    /// </summary>
    public bool RefreshBuffDuration;
   
    public const int __ID__ = -1902217713;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "shapeType:" + ShapeType + ","
        + "shapeLength:" + ShapeLength + ","
        + "shapeWidth:" + ShapeWidth + ","
        + "shapeRadius:" + ShapeRadius + ","
        + "shapeAngle:" + ShapeAngle + ","
        + "areaBuffId:" + AreaBuffId + ","
        + "campFilter:" + CampFilter + ","
        + "defaultLifetime:" + DefaultLifetime + ","
        + "refreshBuffDuration:" + RefreshBuffDuration + ","
        + "}";
    }
}
}

