
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class MapAreaInfo : Luban.BeanBase
{
    public MapAreaInfo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["scene_name"].IsString) { throw new SerializationException(); }  SceneName = _buf["scene_name"]; }
        { if(!_buf["is_home"].IsBoolean) { throw new SerializationException(); }  IsHome = _buf["is_home"]; }
        { if(!_buf["always_alert"].IsBoolean) { throw new SerializationException(); }  AlwaysAlert = _buf["always_alert"]; }
        { if(!_buf["default_disguise"].IsBoolean) { throw new SerializationException(); }  DefaultDisguise = _buf["default_disguise"]; }
        { if(!_buf["hunting_target"].IsBoolean) { throw new SerializationException(); }  HuntingTarget = _buf["hunting_target"]; }
        { var __json0 = _buf["hunting_unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } HuntingUnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  HuntingUnlockConds.Add(__v0); }   }
    }

    public static MapAreaInfo DeserializeMapAreaInfo(JSONNode _buf)
    {
        return new demo.MapAreaInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public string Id;
    /// <summary>
    /// 名称
    /// </summary>
    public string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
    /// <summary>
    /// 场景名
    /// </summary>
    public string SceneName;
    /// <summary>
    /// 警戒标记
    /// </summary>
    public bool IsHome;
    /// <summary>
    /// 警戒标记
    /// </summary>
    public bool AlwaysAlert;
    /// <summary>
    /// 默认伪装
    /// </summary>
    public bool DefaultDisguise;
    /// <summary>
    /// 是否是出击目标
    /// </summary>
    public bool HuntingTarget;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> HuntingUnlockConds;
   
    public const int __ID__ = 1607084204;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in HuntingUnlockConds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "sceneName:" + SceneName + ","
        + "isHome:" + IsHome + ","
        + "alwaysAlert:" + AlwaysAlert + ","
        + "defaultDisguise:" + DefaultDisguise + ","
        + "huntingTarget:" + HuntingTarget + ","
        + "huntingUnlockConds:" + Luban.StringUtil.CollectionToString(HuntingUnlockConds) + ","
        + "}";
    }
}
}

