
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class MapDesireCrystalBudget : Luban.BeanBase
{
    public MapDesireCrystalBudget(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["map_id"].IsString) { throw new SerializationException(); }  MapId = _buf["map_id"]; }
        { if(!_buf["attach_count"].IsNumber) { throw new SerializationException(); }  AttachCount = _buf["attach_count"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
    }

    public static MapDesireCrystalBudget DeserializeMapDesireCrystalBudget(JSONNode _buf)
    {
        return new demo.MapDesireCrystalBudget(_buf);
    }

    /// <summary>
    /// 行主键
    /// </summary>
    public string Id;
    /// <summary>
    /// 地图 id（TbMapAreaInfo）
    /// </summary>
    public string MapId;
    /// <summary>
    /// 附着 npc 刷新槽数量上限
    /// </summary>
    public int AttachCount;
    /// <summary>
    /// 权重
    /// </summary>
    public int Weight;
   
    public const int __ID__ = -303701824;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "mapId:" + MapId + ","
        + "attachCount:" + AttachCount + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

