
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class MicroPlotDef : Luban.BeanBase
{
    public MicroPlotDef(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["managed_uniqnames"]; if(!__json0.IsArray) { throw new SerializationException(); } ManagedUniqnames = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  ManagedUniqnames.Add(__v0); }   }
        { if(!_buf["max_duration_sec"].IsNumber) { throw new SerializationException(); }  MaxDurationSec = _buf["max_duration_sec"]; }
        { if(!_buf["consume_on"].IsNumber) { throw new SerializationException(); }  ConsumeOn = (demo.EMicroPlotConsumeOn)_buf["consume_on"].AsInt; }
    }

    public static MicroPlotDef DeserializeMicroPlotDef(JSONNode _buf)
    {
        return new demo.MicroPlotDef(_buf);
    }

    /// <summary>
    /// 演出定义 id，由触发器引用
    /// </summary>
    public string Id;
    /// <summary>
    /// 管辖 NPC 的地图 UniqName，与导出刷新项一致，竖线分隔
    /// </summary>
    public System.Collections.Generic.List<string> ManagedUniqnames;
    /// <summary>
    /// 超时强制结束（秒）
    /// </summary>
    public float MaxDurationSec;
    /// <summary>
    /// 完成后何时记为已消耗：SuccessOrAbort / SuccessOnly
    /// </summary>
    public demo.EMicroPlotConsumeOn ConsumeOn;
   
    public const int __ID__ = -1067997621;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "managedUniqnames:" + Luban.StringUtil.CollectionToString(ManagedUniqnames) + ","
        + "maxDurationSec:" + MaxDurationSec + ","
        + "consumeOn:" + ConsumeOn + ","
        + "}";
    }
}
}

