
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class NpcDialogInfo : Luban.BeanBase
{
    public NpcDialogInfo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["npc_id"].IsString) { throw new SerializationException(); }  NpcId = _buf["npc_id"]; }
        { if(!_buf["dialog_id"].IsString) { throw new SerializationException(); }  DialogId = _buf["dialog_id"]; }
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
        { var __json0 = _buf["show_cond"]; if(!__json0.IsArray) { throw new SerializationException(); } ShowCond = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  ShowCond.Add(__v0); }   }
        { if(!_buf["need_npc_val"].IsString) { throw new SerializationException(); }  NeedNpcVal = _buf["need_npc_val"]; }
    }

    public static NpcDialogInfo DeserializeNpcDialogInfo(JSONNode _buf)
    {
        return new demo.NpcDialogInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id;
    /// <summary>
    /// npcId
    /// </summary>
    public string NpcId;
    /// <summary>
    /// 对话id
    /// </summary>
    public string DialogId;
    /// <summary>
    /// id
    /// </summary>
    public int Priority;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> ShowCond;
    /// <summary>
    /// 所需标记
    /// </summary>
    public string NeedNpcVal;
   
    public const int __ID__ = -177343764;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in ShowCond) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "npcId:" + NpcId + ","
        + "dialogId:" + DialogId + ","
        + "priority:" + Priority + ","
        + "showCond:" + Luban.StringUtil.CollectionToString(ShowCond) + ","
        + "needNpcVal:" + NeedNpcVal + ","
        + "}";
    }
}
}

