
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class NpcRoutineProfile : Luban.BeanBase
{
    public NpcRoutineProfile(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["fallback_rule_id"].IsString) { throw new SerializationException(); }  FallbackRuleId = _buf["fallback_rule_id"]; }
        { if(!_buf["reevaluate_interval_sec"].IsNumber) { throw new SerializationException(); }  ReevaluateIntervalSec = _buf["reevaluate_interval_sec"]; }
    }

    public static NpcRoutineProfile DeserializeNpcRoutineProfile(JSONNode _buf)
    {
        return new demo.NpcRoutineProfile(_buf);
    }

    /// <summary>
    /// profile id
    /// </summary>
    public string Id;
    /// <summary>
    /// fallback rule id
    /// </summary>
    public string FallbackRuleId;
    /// <summary>
    /// rule reevaluation interval
    /// </summary>
    public float ReevaluateIntervalSec;
   
    public const int __ID__ = -1697463781;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "fallbackRuleId:" + FallbackRuleId + ","
        + "reevaluateIntervalSec:" + ReevaluateIntervalSec + ","
        + "}";
    }
}
}
