
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class PartGear : Luban.BeanBase
{
    public PartGear(JSONNode _buf) 
    {
        { if(!_buf["item_id"].IsString) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { if(!_buf["body_part"].IsNumber) { throw new SerializationException(); }  BodyPart = (demo.EBodyPart)_buf["body_part"].AsInt; }
        { if(!_buf["gear_slot_cost"].IsNumber) { throw new SerializationException(); }  GearSlotCost = _buf["gear_slot_cost"]; }
        { if(!_buf["min_part_level"].IsNumber) { throw new SerializationException(); }  MinPartLevel = _buf["min_part_level"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["local_bonuses"]; if(!__json0.IsArray) { throw new SerializationException(); } LocalBonuses = new System.Collections.Generic.List<demo.PartLocalStatBonus>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.PartLocalStatBonus __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.PartLocalStatBonus.DeserializePartLocalStatBonus(__e0);  }  LocalBonuses.Add(__v0); }   }
    }

    public static PartGear DeserializePartGear(JSONNode _buf)
    {
        return new demo.PartGear(_buf);
    }

    /// <summary>
    /// item_id
    /// </summary>
    public string ItemId;
    /// <summary>
    /// body_part
    /// </summary>
    public demo.EBodyPart BodyPart;
    /// <summary>
    /// gear_slot_cost
    /// </summary>
    public int GearSlotCost;
    /// <summary>
    /// min_part_level
    /// </summary>
    public int MinPartLevel;
    /// <summary>
    /// desc
    /// </summary>
    public string Desc;
    /// <summary>
    /// local_bonuses
    /// </summary>
    public System.Collections.Generic.List<demo.PartLocalStatBonus> LocalBonuses;
   
    public const int __ID__ = 1953515501;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in LocalBonuses) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "bodyPart:" + BodyPart + ","
        + "gearSlotCost:" + GearSlotCost + ","
        + "minPartLevel:" + MinPartLevel + ","
        + "desc:" + Desc + ","
        + "localBonuses:" + Luban.StringUtil.CollectionToString(LocalBonuses) + ","
        + "}";
    }
}
}

