
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class PlayerAttachInfo : Luban.BeanBase
{
    public PlayerAttachInfo(JSONNode _buf) 
    {
        { if(!_buf["attach_id"].IsString) { throw new SerializationException(); }  AttachId = _buf["attach_id"]; }
        { if(!_buf["attach_type"].IsString) { throw new SerializationException(); }  AttachType = _buf["attach_type"]; }
        { if(!_buf["display_weight"].IsNumber) { throw new SerializationException(); }  DisplayWeight = _buf["display_weight"]; }
        { if(!_buf["display_count_weight"].IsNumber) { throw new SerializationException(); }  DisplayCountWeight = _buf["display_count_weight"]; }
        { if(!_buf["display_group_id"].IsString) { throw new SerializationException(); }  DisplayGroupId = _buf["display_group_id"]; }
        { if(!_buf["max_visible_count"].IsNumber) { throw new SerializationException(); }  MaxVisibleCount = _buf["max_visible_count"]; }
        { if(!_buf["attach_main_buff"].IsString) { throw new SerializationException(); }  AttachMainBuff = _buf["attach_main_buff"]; }
        { if(!_buf["attach_view_prefab"].IsString) { throw new SerializationException(); }  AttachViewPrefab = _buf["attach_view_prefab"]; }
        { if(!_buf["auto_drop_time"].IsNumber) { throw new SerializationException(); }  AutoDropTime = _buf["auto_drop_time"]; }
        { if(!_buf["hit_count"].IsNumber) { throw new SerializationException(); }  HitCount = _buf["hit_count"]; }
    }

    public static PlayerAttachInfo DeserializePlayerAttachInfo(JSONNode _buf)
    {
        return new demo.PlayerAttachInfo(_buf);
    }

    /// <summary>
    /// attach id
    /// </summary>
    public string AttachId;
    /// <summary>
    /// attach type used by interact checks
    /// </summary>
    public string AttachType;
    /// <summary>
    /// higher value is shown first
    /// </summary>
    public int DisplayWeight;
    /// <summary>
    /// extra sorting weight per same group count
    /// </summary>
    public int DisplayCountWeight;
    /// <summary>
    /// same group can collapse visible instances; empty uses attach_type/attach_id
    /// </summary>
    public string DisplayGroupId;
    /// <summary>
    /// 0 means show all instances in group
    /// </summary>
    public int MaxVisibleCount;
    /// <summary>
    /// main buff added while attach is active
    /// </summary>
    public string AttachMainBuff;
    /// <summary>
    /// Resources prefab path under Prefab/Attach; empty uses attach_id
    /// </summary>
    public string AttachViewPrefab;
    /// <summary>
    /// auto drop duration; negative means no timer
    /// </summary>
    public float AutoDropTime;
    /// <summary>
    /// hit count before attach breaks
    /// </summary>
    public float HitCount;
   
    public const int __ID__ = -1448051937;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "attachId:" + AttachId + ","
        + "attachType:" + AttachType + ","
        + "displayWeight:" + DisplayWeight + ","
        + "displayCountWeight:" + DisplayCountWeight + ","
        + "displayGroupId:" + DisplayGroupId + ","
        + "maxVisibleCount:" + MaxVisibleCount + ","
        + "attachMainBuff:" + AttachMainBuff + ","
        + "attachViewPrefab:" + AttachViewPrefab + ","
        + "autoDropTime:" + AutoDropTime + ","
        + "hitCount:" + HitCount + ","
        + "}";
    }
}
}

