
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class PlayerDesireLevel : Luban.BeanBase
{
    public PlayerDesireLevel(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["desire_line"].IsNumber) { throw new SerializationException(); }  DesireLine = _buf["desire_line"]; }
        { if(!_buf["aura_h_effect"].IsNumber) { throw new SerializationException(); }  AuraHEffect = _buf["aura_h_effect"]; }
        { if(!_buf["aura_max_range"].IsNumber) { throw new SerializationException(); }  AuraMaxRange = _buf["aura_max_range"]; }
        { if(!_buf["spirit_monster_total_budget"].IsNumber) { throw new SerializationException(); }  SpiritMonsterTotalBudget = _buf["spirit_monster_total_budget"]; }
        { if(!_buf["spirit_monster_refresh_interval_sec"].IsNumber) { throw new SerializationException(); }  SpiritMonsterRefreshIntervalSec = _buf["spirit_monster_refresh_interval_sec"]; }
        { if(!_buf["ambient_spirit_drift_speed"].IsNumber) { throw new SerializationException(); }  AmbientSpiritDriftSpeed = _buf["ambient_spirit_drift_speed"]; }
    }

    public static PlayerDesireLevel DeserializePlayerDesireLevel(JSONNode _buf)
    {
        return new demo.PlayerDesireLevel(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public int Level;
    /// <summary>
    /// 欲望线
    /// </summary>
    public int DesireLine;
    /// <summary>
    /// 光环值
    /// </summary>
    public float AuraHEffect;
    /// <summary>
    /// 每秒传播
    /// </summary>
    public float AuraMaxRange;
    /// <summary>
    /// 实战影怪总预算(各类型 budget_cost 之和上限)
    /// </summary>
    public int SpiritMonsterTotalBudget;
    /// <summary>
    /// 按预算补全影怪的刷新间隔(秒)
    /// </summary>
    public float SpiritMonsterRefreshIntervalSec;
    /// <summary>
    /// 后场漂移速度系数
    /// </summary>
    public float AmbientSpiritDriftSpeed;
   
    public const int __ID__ = -1173769842;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "desireLine:" + DesireLine + ","
        + "auraHEffect:" + AuraHEffect + ","
        + "auraMaxRange:" + AuraMaxRange + ","
        + "spiritMonsterTotalBudget:" + SpiritMonsterTotalBudget + ","
        + "spiritMonsterRefreshIntervalSec:" + SpiritMonsterRefreshIntervalSec + ","
        + "ambientSpiritDriftSpeed:" + AmbientSpiritDriftSpeed + ","
        + "}";
    }
}
}

