
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class PlayerSanCorruptLevel : Luban.BeanBase
{
    public PlayerSanCorruptLevel(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["san_line"].IsNumber) { throw new SerializationException(); }  SanLine = _buf["san_line"]; }
        { if(!_buf["basic_estrus"].IsNumber) { throw new SerializationException(); }  BasicEstrus = _buf["basic_estrus"]; }
        { if(!_buf["spirit_monster_total_budget"].IsNumber) { throw new SerializationException(); }  SpiritMonsterTotalBudget = _buf["spirit_monster_total_budget"]; }
        { if(!_buf["spirit_monster_refresh_interval_sec"].IsNumber) { throw new SerializationException(); }  SpiritMonsterRefreshIntervalSec = _buf["spirit_monster_refresh_interval_sec"]; }
        { if(!_buf["ambient_spirit_drift_speed"].IsNumber) { throw new SerializationException(); }  AmbientSpiritDriftSpeed = _buf["ambient_spirit_drift_speed"]; }
    }

    public static PlayerSanCorruptLevel DeserializePlayerSanCorruptLevel(JSONNode _buf)
    {
        return new demo.PlayerSanCorruptLevel(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public int Level;
    /// <summary>
    /// 理智线
    /// </summary>
    public int SanLine;
    /// <summary>
    /// 基准发情
    /// </summary>
    public int BasicEstrus;
    /// <summary>
    /// 实战影怪总预算(各类型 budget_cost 之和上限)
    /// </summary>
    public int SpiritMonsterTotalBudget;
    /// <summary>
    /// 按预算补全影怪的刷新间隔(秒)
    /// </summary>
    public float SpiritMonsterRefreshIntervalSec;
    /// <summary>
    /// 后场漂移速度系数
    /// </summary>
    public float AmbientSpiritDriftSpeed;
   
    public const int __ID__ = 1190698603;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "sanLine:" + SanLine + ","
        + "basicEstrus:" + BasicEstrus + ","
        + "spiritMonsterTotalBudget:" + SpiritMonsterTotalBudget + ","
        + "spiritMonsterRefreshIntervalSec:" + SpiritMonsterRefreshIntervalSec + ","
        + "ambientSpiritDriftSpeed:" + AmbientSpiritDriftSpeed + ","
        + "}";
    }
}
}

