
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class PlayerClothesExposeInfo : Luban.BeanBase
{
    public PlayerClothesExposeInfo(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["line_min"].IsNumber) { throw new SerializationException(); }  LineMin = _buf["line_min"]; }
        { if(!_buf["line_max"].IsNumber) { throw new SerializationException(); }  LineMax = _buf["line_max"]; }
        { if(!_buf["h_impluse_resist"].IsNumber) { throw new SerializationException(); }  HImpluseResist = _buf["h_impluse_resist"]; }
        { if(!_buf["gaze_resist"].IsNumber) { throw new SerializationException(); }  GazeResist = _buf["gaze_resist"]; }
    }

    public static PlayerClothesExposeInfo DeserializePlayerClothesExposeInfo(JSONNode _buf)
    {
        return new demo.PlayerClothesExposeInfo(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public int Level;
    /// <summary>
    /// 名称
    /// </summary>
    public string Name;
    /// <summary>
    /// 衣装线min
    /// </summary>
    public int LineMin;
    /// <summary>
    /// 衣装线max
    /// </summary>
    public int LineMax;
    /// <summary>
    /// h冲击减伤率
    /// </summary>
    public float HImpluseResist;
    /// <summary>
    /// 视线减伤率
    /// </summary>
    public float GazeResist;
   
    public const int __ID__ = -641350418;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "name:" + Name + ","
        + "lineMin:" + LineMin + ","
        + "lineMax:" + LineMax + ","
        + "hImpluseResist:" + HImpluseResist + ","
        + "gazeResist:" + GazeResist + ","
        + "}";
    }
}
}

