
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class ProgressionHubTabDef : Luban.BeanBase
{
    public ProgressionHubTabDef(JSONNode _buf) 
    {
        { if(!_buf["tab_id"].IsNumber) { throw new SerializationException(); }  TabId = (demo.EProgressionHubTab)_buf["tab_id"].AsInt; }
        { if(!_buf["func_open_type"].IsNumber) { throw new SerializationException(); }  FuncOpenType = (demo.EFuncOpenType)_buf["func_open_type"].AsInt; }
        { if(!_buf["sort_order"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["sort_order"]; }
    }

    public static ProgressionHubTabDef DeserializeProgressionHubTabDef(JSONNode _buf)
    {
        return new demo.ProgressionHubTabDef(_buf);
    }

    /// <summary>
    /// 选项卡
    /// </summary>
    public demo.EProgressionHubTab TabId;
    /// <summary>
    /// 功能解锁(Invalid=始终开放)
    /// </summary>
    public demo.EFuncOpenType FuncOpenType;
    /// <summary>
    /// 排序
    /// </summary>
    public int SortOrder;
   
    public const int __ID__ = 417121365;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "tabId:" + TabId + ","
        + "funcOpenType:" + FuncOpenType + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

