
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class QuestData : Luban.BeanBase
{
    public QuestData(JSONNode _buf) 
    {
        { if(!_buf["quest_id"].IsNumber) { throw new SerializationException(); }  QuestId = _buf["quest_id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["init_step_id"].IsString) { throw new SerializationException(); }  InitStepId = _buf["init_step_id"]; }
        { var __json0 = _buf["finish_reward"]; if(!__json0.IsArray) { throw new SerializationException(); } FinishReward = new System.Collections.Generic.Dictionary<string, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  FinishReward.Add(_k0, _v0); }   }
        { if(!_buf["is_auto_accept"].IsBoolean) { throw new SerializationException(); }  IsAutoAccept = _buf["is_auto_accept"]; }
        { var __json0 = _buf["acceept_cond"]; if(!__json0.IsArray) { throw new SerializationException(); } AcceeptCond = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  AcceeptCond.Add(__v0); }   }
        { if(!_buf["start_npc_id"].IsString) { throw new SerializationException(); }  StartNpcId = _buf["start_npc_id"]; }
    }

    public static QuestData DeserializeQuestData(JSONNode _buf)
    {
        return new demo.QuestData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int QuestId;
    /// <summary>
    /// 名称
    /// </summary>
    public string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;
    /// <summary>
    /// 初始step
    /// </summary>
    public string InitStepId;
    /// <summary>
    /// 完成奖励
    /// </summary>
    public System.Collections.Generic.Dictionary<string, int> FinishReward;
    /// <summary>
    /// 是否自动接取
    /// </summary>
    public bool IsAutoAccept;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> AcceeptCond;
    /// <summary>
    /// 接取npcid
    /// </summary>
    public string StartNpcId;
   
    public const int __ID__ = 477752641;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in AcceeptCond) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "questId:" + QuestId + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "initStepId:" + InitStepId + ","
        + "finishReward:" + Luban.StringUtil.CollectionToString(FinishReward) + ","
        + "isAutoAccept:" + IsAutoAccept + ","
        + "acceeptCond:" + Luban.StringUtil.CollectionToString(AcceeptCond) + ","
        + "startNpcId:" + StartNpcId + ","
        + "}";
    }
}
}

