
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class QuestStepObjective : Luban.BeanBase
{
    public QuestStepObjective(JSONNode _buf) 
    {
        { if(!_buf["obj_id"].IsString) { throw new SerializationException(); }  ObjId = _buf["obj_id"]; }
        { if(!_buf["custom_desc"].IsBoolean) { throw new SerializationException(); }  CustomDesc = _buf["custom_desc"]; }
        { if(!_buf["format_desc"].IsString) { throw new SerializationException(); }  FormatDesc = _buf["format_desc"]; }
        { if(!_buf["is_option"].IsBoolean) { throw new SerializationException(); }  IsOption = _buf["is_option"]; }
        { if(!_buf["is_hidden"].IsBoolean) { throw new SerializationException(); }  IsHidden = _buf["is_hidden"]; }
        { if(!_buf["completion_tag"].IsString) { throw new SerializationException(); }  CompletionTag = _buf["completion_tag"]; }
        { if(!_buf["obj_type"].IsNumber) { throw new SerializationException(); }  ObjType = (demo.EQuestObjectiveType)_buf["obj_type"].AsInt; }
        { if(!_buf["obj_progress"].IsNumber) { throw new SerializationException(); }  ObjProgress = _buf["obj_progress"]; }
        { if(!_buf["obj_p0"].IsNumber) { throw new SerializationException(); }  ObjP0 = _buf["obj_p0"]; }
        { if(!_buf["obj_p1"].IsNumber) { throw new SerializationException(); }  ObjP1 = _buf["obj_p1"]; }
        { if(!_buf["obj_p2"].IsNumber) { throw new SerializationException(); }  ObjP2 = _buf["obj_p2"]; }
        { if(!_buf["obj_p3"].IsNumber) { throw new SerializationException(); }  ObjP3 = _buf["obj_p3"]; }
        { if(!_buf["obj_p4"].IsString) { throw new SerializationException(); }  ObjP4 = _buf["obj_p4"]; }
        { if(!_buf["obj_p5"].IsString) { throw new SerializationException(); }  ObjP5 = _buf["obj_p5"]; }
        { if(!_buf["obj_p_extra"].IsString) { throw new SerializationException(); }  ObjPExtra = _buf["obj_p_extra"]; }
    }

    public static QuestStepObjective DeserializeQuestStepObjective(JSONNode _buf)
    {
        return new demo.QuestStepObjective(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public string ObjId;
    /// <summary>
    /// 自定义desc
    /// </summary>
    public bool CustomDesc;
    /// <summary>
    /// 格式化描述
    /// </summary>
    public string FormatDesc;
    /// <summary>
    /// 是否隐藏
    /// </summary>
    public bool IsOption;
    /// <summary>
    /// 是否隐藏
    /// </summary>
    public bool IsHidden;
    /// <summary>
    /// 完成标记
    /// </summary>
    public string CompletionTag;
    /// <summary>
    /// 目标类型
    /// </summary>
    public demo.EQuestObjectiveType ObjType;
    /// <summary>
    /// 进度要求
    /// </summary>
    public long ObjProgress;
    /// <summary>
    /// p0<br/>int
    /// </summary>
    public int ObjP0;
    /// <summary>
    /// p1<br/>int
    /// </summary>
    public int ObjP1;
    /// <summary>
    /// p2<br/>long
    /// </summary>
    public long ObjP2;
    /// <summary>
    /// p3<br/>long
    /// </summary>
    public long ObjP3;
    /// <summary>
    /// p4<br/>long
    /// </summary>
    public string ObjP4;
    /// <summary>
    /// p5<br/>long
    /// </summary>
    public string ObjP5;
    /// <summary>
    /// 复杂进度参数
    /// </summary>
    public string ObjPExtra;
   
    public const int __ID__ = 561189910;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "objId:" + ObjId + ","
        + "customDesc:" + CustomDesc + ","
        + "formatDesc:" + FormatDesc + ","
        + "isOption:" + IsOption + ","
        + "isHidden:" + IsHidden + ","
        + "completionTag:" + CompletionTag + ","
        + "objType:" + ObjType + ","
        + "objProgress:" + ObjProgress + ","
        + "objP0:" + ObjP0 + ","
        + "objP1:" + ObjP1 + ","
        + "objP2:" + ObjP2 + ","
        + "objP3:" + ObjP3 + ","
        + "objP4:" + ObjP4 + ","
        + "objP5:" + ObjP5 + ","
        + "objPExtra:" + ObjPExtra + ","
        + "}";
    }
}
}

