
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class RenewableResourceNode : Luban.BeanBase
{
    public RenewableResourceNode(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["unlock_required_progress"].IsNumber) { throw new SerializationException(); }  UnlockRequiredProgress = _buf["unlock_required_progress"]; }
        { if(!_buf["reward_item_id"].IsString) { throw new SerializationException(); }  RewardItemId = _buf["reward_item_id"]; }
        { if(!_buf["reward_count"].IsNumber) { throw new SerializationException(); }  RewardCount = _buf["reward_count"]; }
        { if(!_buf["restock_every_n_days"].IsNumber) { throw new SerializationException(); }  RestockEveryNDays = _buf["restock_every_n_days"]; }
        { if(!_buf["capacity"].IsNumber) { throw new SerializationException(); }  Capacity = _buf["capacity"]; }
        { if(!_buf["immediate_ready_on_unlock"].IsBoolean) { throw new SerializationException(); }  ImmediateReadyOnUnlock = _buf["immediate_ready_on_unlock"]; }
        { if(!_buf["locked_status_id"].IsNumber) { throw new SerializationException(); }  LockedStatusId = _buf["locked_status_id"]; }
        { if(!_buf["waiting_status_id"].IsNumber) { throw new SerializationException(); }  WaitingStatusId = _buf["waiting_status_id"]; }
        { if(!_buf["ready_status_id"].IsNumber) { throw new SerializationException(); }  ReadyStatusId = _buf["ready_status_id"]; }
    }

    public static RenewableResourceNode DeserializeRenewableResourceNode(JSONNode _buf)
    {
        return new demo.RenewableResourceNode(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public string Id;
    /// <summary>
    /// 名称
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 永久解锁所需进度
    /// </summary>
    public int UnlockRequiredProgress;
    /// <summary>
    /// 产出物品
    /// </summary>
    public string RewardItemId;
    /// <summary>
    /// 单次产量
    /// </summary>
    public int RewardCount;
    /// <summary>
    /// 恢复结算日
    /// </summary>
    public int RestockEveryNDays;
    /// <summary>
    /// 库存上限
    /// </summary>
    public int Capacity;
    /// <summary>
    /// 解锁时立即成熟
    /// </summary>
    public bool ImmediateReadyOnUnlock;
    /// <summary>
    /// 未解锁状态
    /// </summary>
    public int LockedStatusId;
    /// <summary>
    /// 已解锁等待状态
    /// </summary>
    public int WaitingStatusId;
    /// <summary>
    /// 可收获状态
    /// </summary>
    public int ReadyStatusId;
   
    public const int __ID__ = -1877070772;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "displayName:" + DisplayName + ","
        + "unlockRequiredProgress:" + UnlockRequiredProgress + ","
        + "rewardItemId:" + RewardItemId + ","
        + "rewardCount:" + RewardCount + ","
        + "restockEveryNDays:" + RestockEveryNDays + ","
        + "capacity:" + Capacity + ","
        + "immediateReadyOnUnlock:" + ImmediateReadyOnUnlock + ","
        + "lockedStatusId:" + LockedStatusId + ","
        + "waitingStatusId:" + WaitingStatusId + ","
        + "readyStatusId:" + ReadyStatusId + ","
        + "}";
    }
}
}

