
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class RumorIntel : Luban.BeanBase
{
    public RumorIntel(JSONNode _buf) 
    {
        { if(!_buf["rumor_id"].IsString) { throw new SerializationException(); }  RumorId = _buf["rumor_id"]; }
        { if(!_buf["thumb_name"].IsString) { throw new SerializationException(); }  ThumbName = _buf["thumb_name"]; }
        { if(!_buf["full_text"].IsString) { throw new SerializationException(); }  FullText = _buf["full_text"]; }
        { if(!_buf["cost_item_id"].IsString) { throw new SerializationException(); }  CostItemId = _buf["cost_item_id"]; }
        { if(!_buf["cost_count"].IsNumber) { throw new SerializationException(); }  CostCount = _buf["cost_count"]; }
        { if(!_buf["duration_days"].IsNumber) { throw new SerializationException(); }  DurationDays = _buf["duration_days"]; }
        { if(!_buf["effect_type"].IsNumber) { throw new SerializationException(); }  EffectType = (demo.ERumorEffectType)_buf["effect_type"].AsInt; }
        { if(!_buf["loot_point_cfg_id"].IsString) { throw new SerializationException(); }  LootPointCfgId = _buf["loot_point_cfg_id"]; }
        { if(!_buf["npc_cfg_id"].IsString) { throw new SerializationException(); }  NpcCfgId = _buf["npc_cfg_id"]; }
        { if(!_buf["intel_kind"].IsNumber) { throw new SerializationException(); }  IntelKind = (demo.ERumorIntelKind)_buf["intel_kind"].AsInt; }
        { var __json0 = _buf["appear_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } AppearConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  AppearConds.Add(__v0); }   }
        { if(!_buf["interact_point_cfg_id"].IsString) { throw new SerializationException(); }  InteractPointCfgId = _buf["interact_point_cfg_id"]; }
    }

    public static RumorIntel DeserializeRumorIntel(JSONNode _buf)
    {
        return new demo.RumorIntel(_buf);
    }

    /// <summary>
    /// rumor_id
    /// </summary>
    public string RumorId;
    /// <summary>
    /// thumb_name
    /// </summary>
    public string ThumbName;
    /// <summary>
    /// full_text
    /// </summary>
    public string FullText;
    /// <summary>
    /// cost_item_id
    /// </summary>
    public string CostItemId;
    /// <summary>
    /// cost_count
    /// </summary>
    public long CostCount;
    /// <summary>
    /// duration_days
    /// </summary>
    public int DurationDays;
    /// <summary>
    /// effect_type
    /// </summary>
    public demo.ERumorEffectType EffectType;
    /// <summary>
    /// loot_point_cfg_id
    /// </summary>
    public string LootPointCfgId;
    /// <summary>
    /// npc_cfg_id
    /// </summary>
    public string NpcCfgId;
    /// <summary>
    /// intel_kind
    /// </summary>
    public demo.ERumorIntelKind IntelKind;
    /// <summary>
    /// appear_conds
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> AppearConds;
    /// <summary>
    /// interact_point_cfg_id
    /// </summary>
    public string InteractPointCfgId;
   
    public const int __ID__ = -815770636;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in AppearConds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "rumorId:" + RumorId + ","
        + "thumbName:" + ThumbName + ","
        + "fullText:" + FullText + ","
        + "costItemId:" + CostItemId + ","
        + "costCount:" + CostCount + ","
        + "durationDays:" + DurationDays + ","
        + "effectType:" + EffectType + ","
        + "lootPointCfgId:" + LootPointCfgId + ","
        + "npcCfgId:" + NpcCfgId + ","
        + "intelKind:" + IntelKind + ","
        + "appearConds:" + Luban.StringUtil.CollectionToString(AppearConds) + ","
        + "interactPointCfgId:" + InteractPointCfgId + ","
        + "}";
    }
}
}

