
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class RumorRandomPool : Luban.BeanBase
{
    public RumorRandomPool(JSONNode _buf) 
    {
        { if(!_buf["entry_id"].IsString) { throw new SerializationException(); }  EntryId = _buf["entry_id"]; }
        { if(!_buf["pool_id"].IsString) { throw new SerializationException(); }  PoolId = _buf["pool_id"]; }
        { if(!_buf["rumor_id"].IsString) { throw new SerializationException(); }  RumorId = _buf["rumor_id"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
    }

    public static RumorRandomPool DeserializeRumorRandomPool(JSONNode _buf)
    {
        return new demo.RumorRandomPool(_buf);
    }

    /// <summary>
    /// entry_id
    /// </summary>
    public string EntryId;
    /// <summary>
    /// pool_id
    /// </summary>
    public string PoolId;
    /// <summary>
    /// rumor_id
    /// </summary>
    public string RumorId;
    /// <summary>
    /// weight
    /// </summary>
    public int Weight;
   
    public const int __ID__ = -2056475871;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "entryId:" + EntryId + ","
        + "poolId:" + PoolId + ","
        + "rumorId:" + RumorId + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

