
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class RuneUpgradeInfo : Luban.BeanBase
{
    public RuneUpgradeInfo(JSONNode _buf) 
    {
        { if(!_buf["upgrade_id"].IsString) { throw new SerializationException(); }  UpgradeId = _buf["upgrade_id"]; }
        { if(!_buf["base_rune_id"].IsString) { throw new SerializationException(); }  BaseRuneId = _buf["base_rune_id"]; }
        { if(!_buf["branch_id"].IsString) { throw new SerializationException(); }  BranchId = _buf["branch_id"]; }
        { var __json0 = _buf["prerequisite_upgrade_ids"]; if(!__json0.IsArray) { throw new SerializationException(); } PrerequisiteUpgradeIds = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  PrerequisiteUpgradeIds.Add(__v0); }   }
        { if(!_buf["passive_skill_id"].IsString) { throw new SerializationException(); }  PassiveSkillId = _buf["passive_skill_id"]; }
        { if(!_buf["func_unlock_key"].IsString) { throw new SerializationException(); }  FuncUnlockKey = _buf["func_unlock_key"]; }
        { if(!_buf["func_open_type"].IsNumber) { throw new SerializationException(); }  FuncOpenType = (demo.EFuncOpenType)_buf["func_open_type"].AsInt; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["layout_slot"].IsNumber) { throw new SerializationException(); }  LayoutSlot = _buf["layout_slot"]; }
        { if(!_buf["sort_order"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["sort_order"]; }
    }

    public static RuneUpgradeInfo DeserializeRuneUpgradeInfo(JSONNode _buf)
    {
        return new demo.RuneUpgradeInfo(_buf);
    }

    public string UpgradeId;
    public string BaseRuneId;
    public string BranchId;
    public System.Collections.Generic.List<string> PrerequisiteUpgradeIds;
    public string PassiveSkillId;
    public string FuncUnlockKey;
    public demo.EFuncOpenType FuncOpenType;
    public string Icon;
    public string Name;
    public string Desc;
    public int LayoutSlot;
    public int SortOrder;
   
    public const int __ID__ = 1357224741;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "upgradeId:" + UpgradeId + ","
        + "baseRuneId:" + BaseRuneId + ","
        + "branchId:" + BranchId + ","
        + "prerequisiteUpgradeIds:" + Luban.StringUtil.CollectionToString(PrerequisiteUpgradeIds) + ","
        + "passiveSkillId:" + PassiveSkillId + ","
        + "funcUnlockKey:" + FuncUnlockKey + ","
        + "funcOpenType:" + FuncOpenType + ","
        + "icon:" + Icon + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "layoutSlot:" + LayoutSlot + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

