
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class RuneData : Luban.BeanBase
{
    public RuneData(JSONNode _buf) 
    {
        { if(!_buf["rune_id"].IsString) { throw new SerializationException(); }  RuneId = _buf["rune_id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["rune_type"].IsNumber) { throw new SerializationException(); }  RuneType = (demo.ERuneType)_buf["rune_type"].AsInt; }
        { if(!_buf["equip_slot"].IsNumber) { throw new SerializationException(); }  EquipSlot = (demo.ERuneEquipSlot)_buf["equip_slot"].AsInt; }
        { if(!_buf["initial_upgrade_id"].IsString) { throw new SerializationException(); }  InitialUpgradeId = _buf["initial_upgrade_id"]; }
        { if(!_buf["layout_template_id"].IsString) { throw new SerializationException(); }  LayoutTemplateId = _buf["layout_template_id"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["sort_order"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["sort_order"]; }
    }

    public static RuneData DeserializeRuneData(JSONNode _buf)
    {
        return new demo.RuneData(_buf);
    }

    public string RuneId;
    public string Name;
    public demo.ERuneType RuneType;
    public demo.ERuneEquipSlot EquipSlot;
    public string InitialUpgradeId;
    public string LayoutTemplateId;
    public string Icon;
    public string Desc;
    public int SortOrder;
   
    public const int __ID__ = 1585911247;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "runeId:" + RuneId + ","
        + "name:" + Name + ","
        + "runeType:" + RuneType + ","
        + "equipSlot:" + EquipSlot + ","
        + "initialUpgradeId:" + InitialUpgradeId + ","
        + "layoutTemplateId:" + LayoutTemplateId + ","
        + "icon:" + Icon + ","
        + "desc:" + Desc + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

