
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class SecretBaseBuildLevel : Luban.BeanBase
{
    public SecretBaseBuildLevel(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["scroll_min_x"].IsNumber) { throw new SerializationException(); }  ScrollMinX = _buf["scroll_min_x"]; }
        { if(!_buf["scroll_max_x"].IsNumber) { throw new SerializationException(); }  ScrollMaxX = _buf["scroll_max_x"]; }
    }

    public static SecretBaseBuildLevel DeserializeSecretBaseBuildLevel(JSONNode _buf)
    {
        return new demo.SecretBaseBuildLevel(_buf);
    }

    /// <summary>
    /// 建设等级
    /// </summary>
    public int Level;
    /// <summary>
    /// 卷轴左边界
    /// </summary>
    public float ScrollMinX;
    /// <summary>
    /// 卷轴右边界
    /// </summary>
    public float ScrollMaxX;
   
    public const int __ID__ = 1230741890;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "scrollMinX:" + ScrollMinX + ","
        + "scrollMaxX:" + ScrollMaxX + ","
        + "}";
    }
}
}

