
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class SecretBaseFacilityLevel : Luban.BeanBase
{
    public SecretBaseFacilityLevel(JSONNode _buf) 
    {
        { if(!_buf["facility_id"].IsString) { throw new SerializationException(); }  FacilityId = _buf["facility_id"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["pool_capacity"].IsNumber) { throw new SerializationException(); }  PoolCapacity = _buf["pool_capacity"]; }
        { if(!_buf["decompose_jingyuan_per_residue"].IsNumber) { throw new SerializationException(); }  DecomposeJingyuanPerResidue = _buf["decompose_jingyuan_per_residue"]; }
        { if(!_buf["upgrade_cost_jingyuan"].IsNumber) { throw new SerializationException(); }  UpgradeCostJingyuan = _buf["upgrade_cost_jingyuan"]; }
        { if(!_buf["upgrade_cost_item_id"].IsString) { throw new SerializationException(); }  UpgradeCostItemId = _buf["upgrade_cost_item_id"]; }
        { if(!_buf["upgrade_cost_item_count"].IsNumber) { throw new SerializationException(); }  UpgradeCostItemCount = _buf["upgrade_cost_item_count"]; }
    }

    public static SecretBaseFacilityLevel DeserializeSecretBaseFacilityLevel(JSONNode _buf)
    {
        return new demo.SecretBaseFacilityLevel(_buf);
    }

    /// <summary>
    /// 设施ID
    /// </summary>
    public string FacilityId;
    /// <summary>
    /// 等级
    /// </summary>
    public int Level;
    /// <summary>
    /// 名称
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// 说明
    /// </summary>
    public string Desc;
    /// <summary>
    /// 精元池容量
    /// </summary>
    public long PoolCapacity;
    /// <summary>
    /// 分解：多少精元=1残精
    /// </summary>
    public int DecomposeJingyuanPerResidue;
    /// <summary>
    /// 升级消耗池精元
    /// </summary>
    public long UpgradeCostJingyuan;
    /// <summary>
    /// 升级消耗物品
    /// </summary>
    public string UpgradeCostItemId;
    /// <summary>
    /// 升级消耗数量
    /// </summary>
    public long UpgradeCostItemCount;
   
    public const int __ID__ = 134373205;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "facilityId:" + FacilityId + ","
        + "level:" + Level + ","
        + "displayName:" + DisplayName + ","
        + "desc:" + Desc + ","
        + "poolCapacity:" + PoolCapacity + ","
        + "decomposeJingyuanPerResidue:" + DecomposeJingyuanPerResidue + ","
        + "upgradeCostJingyuan:" + UpgradeCostJingyuan + ","
        + "upgradeCostItemId:" + UpgradeCostItemId + ","
        + "upgradeCostItemCount:" + UpgradeCostItemCount + ","
        + "}";
    }
}
}

