
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class SkillAbilityExtraPair : Luban.BeanBase
{
    public SkillAbilityExtraPair(JSONNode _buf) 
    {
        { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
        { if(!_buf["val"].IsString) { throw new SerializationException(); }  Val = _buf["val"]; }
    }

    public static SkillAbilityExtraPair DeserializeSkillAbilityExtraPair(JSONNode _buf)
    {
        return new demo.SkillAbilityExtraPair(_buf);
    }

    public string Key;
    public string Val;
   
    public const int __ID__ = 675988358;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "val:" + Val + ","
        + "}";
    }
}
}

