
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class SkillSchool : Luban.BeanBase
{
    public SkillSchool(JSONNode _buf) 
    {
        { if(!_buf["school_id"].IsNumber) { throw new SerializationException(); }  SchoolId = _buf["school_id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { if(!_buf["icon_path"].IsString) { throw new SerializationException(); }  IconPath = _buf["icon_path"]; }
        { if(!_buf["sort_order"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["sort_order"]; }
    }

    public static SkillSchool DeserializeSkillSchool(JSONNode _buf)
    {
        return new demo.SkillSchool(_buf);
    }

    /// <summary>
    /// school_id
    /// </summary>
    public int SchoolId;
    /// <summary>
    /// display_name
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// icon_path
    /// </summary>
    public string IconPath;
    /// <summary>
    /// sort_order
    /// </summary>
    public int SortOrder;
   
    public const int __ID__ = 1896214906;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "schoolId:" + SchoolId + ","
        + "displayName:" + DisplayName + ","
        + "iconPath:" + IconPath + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

