
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may be lost if regenerated from Luban / xlsx.
//     源表：建议在 player_status.xlsx 中增加 spirit_monster_budget sheet 后运行 Luban 再覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class SpiritMonsterTypeBudget : Luban.BeanBase
{
    public SpiritMonsterTypeBudget(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["npc_cfg_id"].IsString) { throw new SerializationException(); }  NpcCfgId = _buf["npc_cfg_id"]; }
        { if(!_buf["budget_cost"].IsNumber) { throw new SerializationException(); }  BudgetCost = _buf["budget_cost"]; }
        { if(!_buf["min_desire_level"].IsNumber) { throw new SerializationException(); }  MinDesireLevel = _buf["min_desire_level"]; }
        { if(!_buf["restore_san"].IsNumber) { throw new SerializationException(); }  RestoreSan = _buf["restore_san"]; }
        { if(!_buf["spawn_weight"].IsNumber) { throw new SerializationException(); }  SpawnWeight = _buf["spawn_weight"]; }
    }

    public static SpiritMonsterTypeBudget DeserializeSpiritMonsterTypeBudget(JSONNode _buf)
    {
        return new demo.SpiritMonsterTypeBudget(_buf);
    }

    // 行主键（唯一）
    public string Id;
    // TbUnitNpc id
    public string NpcCfgId;
    // 占据总预算的单体消耗（至少为 1）
    public int BudgetCost;
    // 玩家欲望等级达到该值后才可进入随机池
    public int MinDesireLevel;
    // 击杀后恢复理智（与 PlayerGamePlayRule 兼容）
    public long RestoreSan;
    // 随机权重（越大越容易被抽到）
    public int SpawnWeight;
   
    public const int __ID__ = 901234567;
    public override int GetTypeId() => __ID__;

    public void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "npcCfgId:" + NpcCfgId + ","
        + "budgetCost:" + BudgetCost + ","
        + "minDesireLevel:" + MinDesireLevel + ","
        + "restoreSan:" + RestoreSan + ","
        + "spawnWeight:" + SpawnWeight + ","
        + "}";
    }
}
}
