
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class TalentNode : Luban.BeanBase
{
    public TalentNode(JSONNode _buf) 
    {
        { if(!_buf["node_id"].IsNumber) { throw new SerializationException(); }  NodeId = _buf["node_id"]; }
        { if(!_buf["display_name"].IsString) { throw new SerializationException(); }  DisplayName = _buf["display_name"]; }
        { var __json0 = _buf["prereq_node_ids"]; if(!__json0.IsArray) { throw new SerializationException(); } PrereqNodeIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  PrereqNodeIds.Add(__v0); }   }
        { var __json0 = _buf["unlock_conds"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockConds = new System.Collections.Generic.List<demo.CommonCheckCond>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.CommonCheckCond __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.CommonCheckCond.DeserializeCommonCheckCond(__e0);  }  UnlockConds.Add(__v0); }   }
        { var __json0 = _buf["unlock_costs"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockCosts = new System.Collections.Generic.List<demo.TalentUnlockCost>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.TalentUnlockCost __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.TalentUnlockCost.DeserializeTalentUnlockCost(__e0);  }  UnlockCosts.Add(__v0); }   }
        { var __json0 = _buf["stat_bonuses"]; if(!__json0.IsArray) { throw new SerializationException(); } StatBonuses = new System.Collections.Generic.List<demo.TalentStatBonus>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.TalentStatBonus __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.TalentStatBonus.DeserializeTalentStatBonus(__e0);  }  StatBonuses.Add(__v0); }   }
        { if(!_buf["passive_skill_id"].IsString) { throw new SerializationException(); }  PassiveSkillId = _buf["passive_skill_id"]; }
    }

    public static TalentNode DeserializeTalentNode(JSONNode _buf)
    {
        return new demo.TalentNode(_buf);
    }

    /// <summary>
    /// node_id
    /// </summary>
    public int NodeId;
    /// <summary>
    /// display_name
    /// </summary>
    public string DisplayName;
    /// <summary>
    /// prereq_node_ids
    /// </summary>
    public System.Collections.Generic.List<int> PrereqNodeIds;
    /// <summary>
    /// unlock_conds
    /// </summary>
    public System.Collections.Generic.List<demo.CommonCheckCond> UnlockConds;
    /// <summary>
    /// unlock_costs
    /// </summary>
    public System.Collections.Generic.List<demo.TalentUnlockCost> UnlockCosts;
    /// <summary>
    /// stat_bonuses
    /// </summary>
    public System.Collections.Generic.List<demo.TalentStatBonus> StatBonuses;
    /// <summary>
    /// passive_skill_id
    /// </summary>
    public string PassiveSkillId;
   
    public const int __ID__ = -1523122663;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in UnlockConds) { _e?.ResolveRef(tables); }
        foreach (var _e in UnlockCosts) { _e?.ResolveRef(tables); }
        foreach (var _e in StatBonuses) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "nodeId:" + NodeId + ","
        + "displayName:" + DisplayName + ","
        + "prereqNodeIds:" + Luban.StringUtil.CollectionToString(PrereqNodeIds) + ","
        + "unlockConds:" + Luban.StringUtil.CollectionToString(UnlockConds) + ","
        + "unlockCosts:" + Luban.StringUtil.CollectionToString(UnlockCosts) + ","
        + "statBonuses:" + Luban.StringUtil.CollectionToString(StatBonuses) + ","
        + "passiveSkillId:" + PassiveSkillId + ","
        + "}";
    }
}
}

