
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 抽象团体阶段
/// </summary>
public partial class TbAbstractGroupStage
{
    private readonly System.Collections.Generic.List<demo.AbstractGroupStage> _dataList;

    private System.Collections.Generic.Dictionary<(string, int), demo.AbstractGroupStage> _dataMapUnion;

    public TbAbstractGroupStage(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<demo.AbstractGroupStage>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.AbstractGroupStage _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.AbstractGroupStage.DeserializeAbstractGroupStage(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(string, int), demo.AbstractGroupStage>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.GroupId, _v.Stage), _v);
        }
    }

    public System.Collections.Generic.List<demo.AbstractGroupStage> DataList => _dataList;

    public demo.AbstractGroupStage Get(string group_id, int stage) => _dataMapUnion.TryGetValue((group_id, stage), out demo.AbstractGroupStage __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

