
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 抽象团体阶段奖励
/// </summary>
public partial class TbAbstractGroupStageReward
{
    private readonly System.Collections.Generic.List<demo.AbstractGroupStageReward> _dataList;

    private System.Collections.Generic.Dictionary<(string, int, int), demo.AbstractGroupStageReward> _dataMapUnion;

    public TbAbstractGroupStageReward(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<demo.AbstractGroupStageReward>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.AbstractGroupStageReward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.AbstractGroupStageReward.DeserializeAbstractGroupStageReward(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(string, int, int), demo.AbstractGroupStageReward>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.GroupId, _v.Stage, _v.RewardIndex), _v);
        }
    }

    public System.Collections.Generic.List<demo.AbstractGroupStageReward> DataList => _dataList;

    public demo.AbstractGroupStageReward Get(string group_id, int stage, int reward_index) => _dataMapUnion.TryGetValue((group_id, stage, reward_index), out demo.AbstractGroupStageReward __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

