
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 抽象团体主表
/// </summary>
public partial class TbAbstractGroup
{
    private readonly System.Collections.Generic.Dictionary<string, demo.AbstractGroup> _dataMap;
    private readonly System.Collections.Generic.List<demo.AbstractGroup> _dataList;
    
    public TbAbstractGroup(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.AbstractGroup>(count);
        _dataList = new System.Collections.Generic.List<demo.AbstractGroup>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.AbstractGroup _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.AbstractGroup.DeserializeAbstractGroup(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.GroupId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.AbstractGroup> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.AbstractGroup> DataList => _dataList;

    public demo.AbstractGroup GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.AbstractGroup Get(string key) => _dataMap[key];
    public demo.AbstractGroup this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

