
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbAlchemyAspectDef
{
    private readonly System.Collections.Generic.Dictionary<int, demo.AlchemyAspectDef> _dataMap;
    private readonly System.Collections.Generic.List<demo.AlchemyAspectDef> _dataList;
    
    public TbAlchemyAspectDef(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.AlchemyAspectDef>(count);
        _dataList = new System.Collections.Generic.List<demo.AlchemyAspectDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.AlchemyAspectDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.AlchemyAspectDef.DeserializeAlchemyAspectDef(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.AlchemyAspectDef> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.AlchemyAspectDef> DataList => _dataList;

    public demo.AlchemyAspectDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.AlchemyAspectDef Get(int key) => _dataMap[key];
    public demo.AlchemyAspectDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

