
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbBodyPartLevel
{
    private readonly System.Collections.Generic.List<demo.BodyPartLevel> _dataList;

    private System.Collections.Generic.Dictionary<(demo.EBodyPart, int), demo.BodyPartLevel> _dataMapUnion;

    public TbBodyPartLevel(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<demo.BodyPartLevel>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.BodyPartLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.BodyPartLevel.DeserializeBodyPartLevel(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(demo.EBodyPart, int), demo.BodyPartLevel>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.PartId, _v.Level), _v);
        }
    }

    public System.Collections.Generic.List<demo.BodyPartLevel> DataList => _dataList;

    public demo.BodyPartLevel Get(demo.EBodyPart part_id, int level) => _dataMapUnion.TryGetValue((part_id, level), out demo.BodyPartLevel __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

