
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbBodyPartDef
{
    private readonly System.Collections.Generic.Dictionary<demo.EBodyPart, demo.BodyPartDef> _dataMap;
    private readonly System.Collections.Generic.List<demo.BodyPartDef> _dataList;
    
    public TbBodyPartDef(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<demo.EBodyPart, demo.BodyPartDef>(count);
        _dataList = new System.Collections.Generic.List<demo.BodyPartDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.BodyPartDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.BodyPartDef.DeserializeBodyPartDef(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.PartId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<demo.EBodyPart, demo.BodyPartDef> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.BodyPartDef> DataList => _dataList;

    public demo.BodyPartDef GetOrDefault(demo.EBodyPart key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.BodyPartDef Get(demo.EBodyPart key) => _dataMap[key];
    public demo.BodyPartDef this[demo.EBodyPart key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

