
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 角色礼物固定覆盖规则
/// </summary>
public partial class TbCharacterGiftRule
{
    private readonly System.Collections.Generic.Dictionary<int, demo.CharacterGiftRule> _dataMap;
    private readonly System.Collections.Generic.List<demo.CharacterGiftRule> _dataList;
    
    public TbCharacterGiftRule(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.CharacterGiftRule>(count);
        _dataList = new System.Collections.Generic.List<demo.CharacterGiftRule>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.CharacterGiftRule _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.CharacterGiftRule.DeserializeCharacterGiftRule(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.CharacterGiftRule> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.CharacterGiftRule> DataList => _dataList;

    public demo.CharacterGiftRule GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.CharacterGiftRule Get(int key) => _dataMap[key];
    public demo.CharacterGiftRule this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

