
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 秘会献精能力值产出
/// </summary>
public partial class TbCultOfferEssenceRule
{
    private readonly System.Collections.Generic.Dictionary<int, demo.CultOfferEssenceRule> _dataMap;
    private readonly System.Collections.Generic.List<demo.CultOfferEssenceRule> _dataList;
    
    public TbCultOfferEssenceRule(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.CultOfferEssenceRule>(count);
        _dataList = new System.Collections.Generic.List<demo.CultOfferEssenceRule>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.CultOfferEssenceRule _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.CultOfferEssenceRule.DeserializeCultOfferEssenceRule(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.CapabilityMin, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.CultOfferEssenceRule> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.CultOfferEssenceRule> DataList => _dataList;

    public demo.CultOfferEssenceRule GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.CultOfferEssenceRule Get(int key) => _dataMap[key];
    public demo.CultOfferEssenceRule this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

