
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 锚点反制行动效果
/// </summary>
public partial class TbCultAnchorPressureAction
{
    private readonly System.Collections.Generic.Dictionary<string, demo.CultAnchorPressureAction> _dataMap;
    private readonly System.Collections.Generic.List<demo.CultAnchorPressureAction> _dataList;
    
    public TbCultAnchorPressureAction(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.CultAnchorPressureAction>(count);
        _dataList = new System.Collections.Generic.List<demo.CultAnchorPressureAction>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.CultAnchorPressureAction _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.CultAnchorPressureAction.DeserializeCultAnchorPressureAction(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ActionId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.CultAnchorPressureAction> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.CultAnchorPressureAction> DataList => _dataList;

    public demo.CultAnchorPressureAction GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.CultAnchorPressureAction Get(string key) => _dataMap[key];
    public demo.CultAnchorPressureAction this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

