
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 教团锚点周期产出
/// </summary>
public partial class TbCultAnchorOutput
{
    private readonly System.Collections.Generic.Dictionary<int, demo.CultAnchorOutput> _dataMap;
    private readonly System.Collections.Generic.List<demo.CultAnchorOutput> _dataList;
    
    public TbCultAnchorOutput(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.CultAnchorOutput>(count);
        _dataList = new System.Collections.Generic.List<demo.CultAnchorOutput>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.CultAnchorOutput _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.CultAnchorOutput.DeserializeCultAnchorOutput(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.OutputId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.CultAnchorOutput> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.CultAnchorOutput> DataList => _dataList;

    public demo.CultAnchorOutput GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.CultAnchorOutput Get(int key) => _dataMap[key];
    public demo.CultAnchorOutput this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

