
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbCultTechNodeLevel
{
    private readonly System.Collections.Generic.List<demo.CultTechNodeLevel> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), demo.CultTechNodeLevel> _dataMapUnion;

    public TbCultTechNodeLevel(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<demo.CultTechNodeLevel>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.CultTechNodeLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.CultTechNodeLevel.DeserializeCultTechNodeLevel(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), demo.CultTechNodeLevel>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.NodeId, _v.Level), _v);
        }
    }

    public System.Collections.Generic.List<demo.CultTechNodeLevel> DataList => _dataList;

    public demo.CultTechNodeLevel Get(int node_id, int level) => _dataMapUnion.TryGetValue((node_id, level), out demo.CultTechNodeLevel __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

