
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbCultTechNode
{
    private readonly System.Collections.Generic.Dictionary<int, demo.CultTechNode> _dataMap;
    private readonly System.Collections.Generic.List<demo.CultTechNode> _dataList;
    
    public TbCultTechNode(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.CultTechNode>(count);
        _dataList = new System.Collections.Generic.List<demo.CultTechNode>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.CultTechNode _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.CultTechNode.DeserializeCultTechNode(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.NodeId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.CultTechNode> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.CultTechNode> DataList => _dataList;

    public demo.CultTechNode GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.CultTechNode Get(int key) => _dataMap[key];
    public demo.CultTechNode this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

