
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 秘会能力值升级节点
/// </summary>
public partial class TbCultSecretCapabilityLevel
{
    private readonly System.Collections.Generic.Dictionary<int, demo.CultSecretCapabilityLevel> _dataMap;
    private readonly System.Collections.Generic.List<demo.CultSecretCapabilityLevel> _dataList;
    
    public TbCultSecretCapabilityLevel(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.CultSecretCapabilityLevel>(count);
        _dataList = new System.Collections.Generic.List<demo.CultSecretCapabilityLevel>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.CultSecretCapabilityLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.CultSecretCapabilityLevel.DeserializeCultSecretCapabilityLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.CultSecretCapabilityLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.CultSecretCapabilityLevel> DataList => _dataList;

    public demo.CultSecretCapabilityLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.CultSecretCapabilityLevel Get(int key) => _dataMap[key];
    public demo.CultSecretCapabilityLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

