
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 教团远征出征点
/// </summary>
public partial class TbCultScoutSite
{
    private readonly System.Collections.Generic.Dictionary<string, demo.CultScoutSite> _dataMap;
    private readonly System.Collections.Generic.List<demo.CultScoutSite> _dataList;
    
    public TbCultScoutSite(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.CultScoutSite>(count);
        _dataList = new System.Collections.Generic.List<demo.CultScoutSite>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.CultScoutSite _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.CultScoutSite.DeserializeCultScoutSite(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.SiteId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.CultScoutSite> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.CultScoutSite> DataList => _dataList;

    public demo.CultScoutSite GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.CultScoutSite Get(string key) => _dataMap[key];
    public demo.CultScoutSite this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

