
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 教团行为到锚点进度映射
/// </summary>
public partial class TbCultAnchorAction
{
    private readonly System.Collections.Generic.List<demo.CultAnchorAction> _dataList;

    private System.Collections.Generic.Dictionary<(string, string, int, string), demo.CultAnchorAction> _dataMapUnion;

    public TbCultAnchorAction(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<demo.CultAnchorAction>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.CultAnchorAction _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.CultAnchorAction.DeserializeCultAnchorAction(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(string, string, int, string), demo.CultAnchorAction>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.LogicAreaId, _v.AnchorId, _v.AnchorLevel, _v.ActionId), _v);
        }
    }

    public System.Collections.Generic.List<demo.CultAnchorAction> DataList => _dataList;

    public demo.CultAnchorAction Get(string logic_area_id, string anchor_id, int anchor_level, string action_id) => _dataMapUnion.TryGetValue((logic_area_id, anchor_id, anchor_level, action_id), out demo.CultAnchorAction __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

