
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 入梦抽象路人
/// </summary>
public partial class TbDreamPasserby
{
    private readonly System.Collections.Generic.Dictionary<string, demo.DreamPasserby> _dataMap;
    private readonly System.Collections.Generic.List<demo.DreamPasserby> _dataList;
    
    public TbDreamPasserby(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.DreamPasserby>(count);
        _dataList = new System.Collections.Generic.List<demo.DreamPasserby>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.DreamPasserby _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.DreamPasserby.DeserializeDreamPasserby(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.PasserbyId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.DreamPasserby> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.DreamPasserby> DataList => _dataList;

    public demo.DreamPasserby GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.DreamPasserby Get(string key) => _dataMap[key];
    public demo.DreamPasserby this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

