
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbFacilityRenovation
{
    private readonly System.Collections.Generic.List<demo.FacilityRenovation> _dataList;

    private System.Collections.Generic.Dictionary<(string, string), demo.FacilityRenovation> _dataMapUnion;

    public TbFacilityRenovation(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<demo.FacilityRenovation>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.FacilityRenovation _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.FacilityRenovation.DeserializeFacilityRenovation(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(string, string), demo.FacilityRenovation>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.FacilityCfgId, _v.RenovationId), _v);
        }
    }

    public System.Collections.Generic.List<demo.FacilityRenovation> DataList => _dataList;

    public demo.FacilityRenovation Get(string facility_cfg_id, string renovation_id) => _dataMapUnion.TryGetValue((facility_cfg_id, renovation_id), out demo.FacilityRenovation __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

