
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbFacilityDefinition
{
    private readonly System.Collections.Generic.Dictionary<string, demo.FacilityDefinition> _dataMap;
    private readonly System.Collections.Generic.List<demo.FacilityDefinition> _dataList;
    
    public TbFacilityDefinition(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.FacilityDefinition>(count);
        _dataList = new System.Collections.Generic.List<demo.FacilityDefinition>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.FacilityDefinition _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.FacilityDefinition.DeserializeFacilityDefinition(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.FacilityId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.FacilityDefinition> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.FacilityDefinition> DataList => _dataList;

    public demo.FacilityDefinition GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.FacilityDefinition Get(string key) => _dataMap[key];
    public demo.FacilityDefinition this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

