
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// human_weapon
/// </summary>
public partial class TbHumanWeapon
{
    private readonly System.Collections.Generic.Dictionary<string, demo.HumanWeapon> _dataMap;
    private readonly System.Collections.Generic.List<demo.HumanWeapon> _dataList;
    
    public TbHumanWeapon(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.HumanWeapon>(count);
        _dataList = new System.Collections.Generic.List<demo.HumanWeapon>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.HumanWeapon _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.HumanWeapon.DeserializeHumanWeapon(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.HumanWeapon> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.HumanWeapon> DataList => _dataList;

    public demo.HumanWeapon GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.HumanWeapon Get(string key) => _dataMap[key];
    public demo.HumanWeapon this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

