
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 物品分解产物配置
/// </summary>
public partial class TbItemDismantle
{
    private readonly System.Collections.Generic.Dictionary<string, demo.ItemDismantle> _dataMap;
    private readonly System.Collections.Generic.List<demo.ItemDismantle> _dataList;
    
    public TbItemDismantle(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.ItemDismantle>(count);
        _dataList = new System.Collections.Generic.List<demo.ItemDismantle>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.ItemDismantle _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.ItemDismantle.DeserializeItemDismantle(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.ItemDismantle> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.ItemDismantle> DataList => _dataList;

    public demo.ItemDismantle GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.ItemDismantle Get(string key) => _dataMap[key];
    public demo.ItemDismantle this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

