
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbJingYuanCodexLevel
{
    private readonly System.Collections.Generic.List<demo.JingYuanCodexLevel> _dataList;

    private System.Collections.Generic.Dictionary<(string, int), demo.JingYuanCodexLevel> _dataMapUnion;

    public TbJingYuanCodexLevel(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<demo.JingYuanCodexLevel>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.JingYuanCodexLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.JingYuanCodexLevel.DeserializeJingYuanCodexLevel(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(string, int), demo.JingYuanCodexLevel>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.CodexId, _v.Level), _v);
        }
    }

    public System.Collections.Generic.List<demo.JingYuanCodexLevel> DataList => _dataList;

    public demo.JingYuanCodexLevel Get(string codex_id, int level) => _dataMapUnion.TryGetValue((codex_id, level), out demo.JingYuanCodexLevel __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

