
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbJingYuanPremiumEffect
{
    private readonly System.Collections.Generic.List<demo.JingYuanPremiumEffect> _dataList;

    private System.Collections.Generic.Dictionary<(demo.EJingYuanType, int, int), demo.JingYuanPremiumEffect> _dataMapUnion;

    public TbJingYuanPremiumEffect(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<demo.JingYuanPremiumEffect>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.JingYuanPremiumEffect _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.JingYuanPremiumEffect.DeserializeJingYuanPremiumEffect(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(demo.EJingYuanType, int, int), demo.JingYuanPremiumEffect>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.TypeId, _v.DropLevel, _v.ConcentrationFloor), _v);
        }
    }

    public System.Collections.Generic.List<demo.JingYuanPremiumEffect> DataList => _dataList;

    public demo.JingYuanPremiumEffect Get(demo.EJingYuanType type_id, int drop_level, int concentration_floor) => _dataMapUnion.TryGetValue((type_id, drop_level, concentration_floor), out demo.JingYuanPremiumEffect __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

