
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbMindFragmentPoolEntry
{
    private readonly System.Collections.Generic.List<demo.MindFragmentPoolEntry> _dataList;


    public TbMindFragmentPoolEntry(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<demo.MindFragmentPoolEntry>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.MindFragmentPoolEntry _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.MindFragmentPoolEntry.DeserializeMindFragmentPoolEntry(_ele);  }
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.List<demo.MindFragmentPoolEntry> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

