
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbNamedNpcJingYuanType
{
    private readonly System.Collections.Generic.Dictionary<string, demo.NamedNpcJingYuanType> _dataMap;
    private readonly System.Collections.Generic.List<demo.NamedNpcJingYuanType> _dataList;
    
    public TbNamedNpcJingYuanType(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.NamedNpcJingYuanType>(count);
        _dataList = new System.Collections.Generic.List<demo.NamedNpcJingYuanType>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.NamedNpcJingYuanType _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.NamedNpcJingYuanType.DeserializeNamedNpcJingYuanType(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.CharacterKey, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.NamedNpcJingYuanType> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.NamedNpcJingYuanType> DataList => _dataList;

    public demo.NamedNpcJingYuanType GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.NamedNpcJingYuanType Get(string key) => _dataMap[key];
    public demo.NamedNpcJingYuanType this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

