
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbPlayerAttachInfo
{
    private readonly System.Collections.Generic.Dictionary<string, demo.PlayerAttachInfo> _dataMap;
    private readonly System.Collections.Generic.List<demo.PlayerAttachInfo> _dataList;
    
    public TbPlayerAttachInfo(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.PlayerAttachInfo>(count);
        _dataList = new System.Collections.Generic.List<demo.PlayerAttachInfo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.PlayerAttachInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.PlayerAttachInfo.DeserializePlayerAttachInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.AttachId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.PlayerAttachInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.PlayerAttachInfo> DataList => _dataList;

    public demo.PlayerAttachInfo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.PlayerAttachInfo Get(string key) => _dataMap[key];
    public demo.PlayerAttachInfo this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

