
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 玩家背包定义
/// </summary>
public partial class TbPlayerBagDef
{
    private readonly System.Collections.Generic.Dictionary<int, demo.PlayerBagDef> _dataMap;
    private readonly System.Collections.Generic.List<demo.PlayerBagDef> _dataList;
    
    public TbPlayerBagDef(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.PlayerBagDef>(count);
        _dataList = new System.Collections.Generic.List<demo.PlayerBagDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.PlayerBagDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.PlayerBagDef.DeserializePlayerBagDef(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.BagId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.PlayerBagDef> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.PlayerBagDef> DataList => _dataList;

    public demo.PlayerBagDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.PlayerBagDef Get(int key) => _dataMap[key];
    public demo.PlayerBagDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

