
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbPlayerDesireLevel
{
    private readonly System.Collections.Generic.Dictionary<int, demo.PlayerDesireLevel> _dataMap;
    private readonly System.Collections.Generic.List<demo.PlayerDesireLevel> _dataList;
    
    public TbPlayerDesireLevel(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.PlayerDesireLevel>(count);
        _dataList = new System.Collections.Generic.List<demo.PlayerDesireLevel>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.PlayerDesireLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.PlayerDesireLevel.DeserializePlayerDesireLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.PlayerDesireLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.PlayerDesireLevel> DataList => _dataList;

    public demo.PlayerDesireLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.PlayerDesireLevel Get(int key) => _dataMap[key];
    public demo.PlayerDesireLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

