
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 养成总面板选项卡
/// </summary>
public partial class TbProgressionHubTab
{
    private readonly System.Collections.Generic.Dictionary<demo.EProgressionHubTab, demo.ProgressionHubTabDef> _dataMap;
    private readonly System.Collections.Generic.List<demo.ProgressionHubTabDef> _dataList;
    
    public TbProgressionHubTab(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<demo.EProgressionHubTab, demo.ProgressionHubTabDef>(count);
        _dataList = new System.Collections.Generic.List<demo.ProgressionHubTabDef>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.ProgressionHubTabDef _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.ProgressionHubTabDef.DeserializeProgressionHubTabDef(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.TabId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<demo.EProgressionHubTab, demo.ProgressionHubTabDef> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.ProgressionHubTabDef> DataList => _dataList;

    public demo.ProgressionHubTabDef GetOrDefault(demo.EProgressionHubTab key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.ProgressionHubTabDef Get(demo.EProgressionHubTab key) => _dataMap[key];
    public demo.ProgressionHubTabDef this[demo.EProgressionHubTab key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

