
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 周期恢复资源节点
/// </summary>
public partial class TbRenewableResourceNode
{
    private readonly System.Collections.Generic.Dictionary<string, demo.RenewableResourceNode> _dataMap;
    private readonly System.Collections.Generic.List<demo.RenewableResourceNode> _dataList;
    
    public TbRenewableResourceNode(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.RenewableResourceNode>(count);
        _dataList = new System.Collections.Generic.List<demo.RenewableResourceNode>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.RenewableResourceNode _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.RenewableResourceNode.DeserializeRenewableResourceNode(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.RenewableResourceNode> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.RenewableResourceNode> DataList => _dataList;

    public demo.RenewableResourceNode GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.RenewableResourceNode Get(string key) => _dataMap[key];
    public demo.RenewableResourceNode this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

