
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbRuneEquipSlot
{
    private readonly System.Collections.Generic.Dictionary<demo.ERuneEquipSlot, demo.RuneEquipSlotInfo> _dataMap;
    private readonly System.Collections.Generic.List<demo.RuneEquipSlotInfo> _dataList;
    
    public TbRuneEquipSlot(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<demo.ERuneEquipSlot, demo.RuneEquipSlotInfo>(count);
        _dataList = new System.Collections.Generic.List<demo.RuneEquipSlotInfo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.RuneEquipSlotInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.RuneEquipSlotInfo.DeserializeRuneEquipSlotInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.EquipSlot, _v);
        }
    }

    public System.Collections.Generic.Dictionary<demo.ERuneEquipSlot, demo.RuneEquipSlotInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.RuneEquipSlotInfo> DataList => _dataList;

    public demo.RuneEquipSlotInfo GetOrDefault(demo.ERuneEquipSlot key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.RuneEquipSlotInfo Get(demo.ERuneEquipSlot key) => _dataMap[key];
    public demo.RuneEquipSlotInfo this[demo.ERuneEquipSlot key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

