
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbRumorRandomPool
{
    private readonly System.Collections.Generic.Dictionary<string, demo.RumorRandomPool> _dataMap;
    private readonly System.Collections.Generic.List<demo.RumorRandomPool> _dataList;
    
    public TbRumorRandomPool(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.RumorRandomPool>(count);
        _dataList = new System.Collections.Generic.List<demo.RumorRandomPool>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.RumorRandomPool _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.RumorRandomPool.DeserializeRumorRandomPool(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.EntryId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.RumorRandomPool> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.RumorRandomPool> DataList => _dataList;

    public demo.RumorRandomPool GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.RumorRandomPool Get(string key) => _dataMap[key];
    public demo.RumorRandomPool this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

