
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbRumorIntel
{
    private readonly System.Collections.Generic.Dictionary<string, demo.RumorIntel> _dataMap;
    private readonly System.Collections.Generic.List<demo.RumorIntel> _dataList;
    
    public TbRumorIntel(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.RumorIntel>(count);
        _dataList = new System.Collections.Generic.List<demo.RumorIntel>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.RumorIntel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.RumorIntel.DeserializeRumorIntel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.RumorId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.RumorIntel> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.RumorIntel> DataList => _dataList;

    public demo.RumorIntel GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.RumorIntel Get(string key) => _dataMap[key];
    public demo.RumorIntel this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

