
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 秘密据点角色自定义选项
/// </summary>
public partial class TbSecretBaseCharacterOption
{
    private readonly System.Collections.Generic.Dictionary<string, demo.SecretBaseCharacterOption> _dataMap;
    private readonly System.Collections.Generic.List<demo.SecretBaseCharacterOption> _dataList;
    
    public TbSecretBaseCharacterOption(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.SecretBaseCharacterOption>(count);
        _dataList = new System.Collections.Generic.List<demo.SecretBaseCharacterOption>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.SecretBaseCharacterOption _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.SecretBaseCharacterOption.DeserializeSecretBaseCharacterOption(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.OptionId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.SecretBaseCharacterOption> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.SecretBaseCharacterOption> DataList => _dataList;

    public demo.SecretBaseCharacterOption GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.SecretBaseCharacterOption Get(string key) => _dataMap[key];
    public demo.SecretBaseCharacterOption this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

