
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 据点建设等级卷轴边界
/// </summary>
public partial class TbSecretBaseBuildLevel
{
    private readonly System.Collections.Generic.Dictionary<int, demo.SecretBaseBuildLevel> _dataMap;
    private readonly System.Collections.Generic.List<demo.SecretBaseBuildLevel> _dataList;
    
    public TbSecretBaseBuildLevel(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.SecretBaseBuildLevel>(count);
        _dataList = new System.Collections.Generic.List<demo.SecretBaseBuildLevel>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.SecretBaseBuildLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.SecretBaseBuildLevel.DeserializeSecretBaseBuildLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.SecretBaseBuildLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.SecretBaseBuildLevel> DataList => _dataList;

    public demo.SecretBaseBuildLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.SecretBaseBuildLevel Get(int key) => _dataMap[key];
    public demo.SecretBaseBuildLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

