
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 秘密据点角色
/// </summary>
public partial class TbSecretBaseCharacter
{
    private readonly System.Collections.Generic.Dictionary<string, demo.SecretBaseCharacter> _dataMap;
    private readonly System.Collections.Generic.List<demo.SecretBaseCharacter> _dataList;
    
    public TbSecretBaseCharacter(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.SecretBaseCharacter>(count);
        _dataList = new System.Collections.Generic.List<demo.SecretBaseCharacter>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.SecretBaseCharacter _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.SecretBaseCharacter.DeserializeSecretBaseCharacter(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.SlotId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.SecretBaseCharacter> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.SecretBaseCharacter> DataList => _dataList;

    public demo.SecretBaseCharacter GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.SecretBaseCharacter Get(string key) => _dataMap[key];
    public demo.SecretBaseCharacter this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

