
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 据点固定设施
/// </summary>
public partial class TbSecretBaseFacility
{
    private readonly System.Collections.Generic.Dictionary<string, demo.SecretBaseFacility> _dataMap;
    private readonly System.Collections.Generic.List<demo.SecretBaseFacility> _dataList;
    
    public TbSecretBaseFacility(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.SecretBaseFacility>(count);
        _dataList = new System.Collections.Generic.List<demo.SecretBaseFacility>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.SecretBaseFacility _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.SecretBaseFacility.DeserializeSecretBaseFacility(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.FacilityId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.SecretBaseFacility> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.SecretBaseFacility> DataList => _dataList;

    public demo.SecretBaseFacility GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.SecretBaseFacility Get(string key) => _dataMap[key];
    public demo.SecretBaseFacility this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

