
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbShop
{
    private readonly System.Collections.Generic.Dictionary<int, demo.Shop> _dataMap;
    private readonly System.Collections.Generic.List<demo.Shop> _dataList;
    
    public TbShop(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.Shop>(count);
        _dataList = new System.Collections.Generic.List<demo.Shop>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.Shop _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.Shop.DeserializeShop(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.Shop> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.Shop> DataList => _dataList;

    public demo.Shop GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.Shop Get(int key) => _dataMap[key];
    public demo.Shop this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

