
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 天赋树定义
/// </summary>
public partial class TbTalentTree
{
    private readonly System.Collections.Generic.Dictionary<string, demo.TalentTree> _dataMap;
    private readonly System.Collections.Generic.List<demo.TalentTree> _dataList;
    
    public TbTalentTree(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, demo.TalentTree>(count);
        _dataList = new System.Collections.Generic.List<demo.TalentTree>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.TalentTree _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.TalentTree.DeserializeTalentTree(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.TreeId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, demo.TalentTree> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.TalentTree> DataList => _dataList;

    public demo.TalentTree GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.TalentTree Get(string key) => _dataMap[key];
    public demo.TalentTree this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

