
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
/// <summary>
/// 城镇路人数量阶段配置，按 Prosperity 选择最高可用阶段
/// </summary>
public partial class TbTownWalkerPopulation
{
    private readonly System.Collections.Generic.List<demo.TownWalkerPopulation> _dataList;

    private System.Collections.Generic.Dictionary<(string, int), demo.TownWalkerPopulation> _dataMapUnion;

    public TbTownWalkerPopulation(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<demo.TownWalkerPopulation>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.TownWalkerPopulation _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.TownWalkerPopulation.DeserializeTownWalkerPopulation(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(string, int), demo.TownWalkerPopulation>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.LogicAreaId, _v.Stage), _v);
        }
    }

    public System.Collections.Generic.List<demo.TownWalkerPopulation> DataList => _dataList;

    public demo.TownWalkerPopulation Get(string logic_area_id, int stage) => _dataMapUnion.TryGetValue((logic_area_id, stage), out demo.TownWalkerPopulation __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

