
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbWantedBehaveInfo
{
    private readonly System.Collections.Generic.Dictionary<demo.EWantedBehaveType, demo.WantedBehaveInfo> _dataMap;
    private readonly System.Collections.Generic.List<demo.WantedBehaveInfo> _dataList;
    
    public TbWantedBehaveInfo(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<demo.EWantedBehaveType, demo.WantedBehaveInfo>(count);
        _dataList = new System.Collections.Generic.List<demo.WantedBehaveInfo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.WantedBehaveInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.WantedBehaveInfo.DeserializeWantedBehaveInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.BehaveType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<demo.EWantedBehaveType, demo.WantedBehaveInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.WantedBehaveInfo> DataList => _dataList;

    public demo.WantedBehaveInfo GetOrDefault(demo.EWantedBehaveType key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.WantedBehaveInfo Get(demo.EWantedBehaveType key) => _dataMap[key];
    public demo.WantedBehaveInfo this[demo.EWantedBehaveType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

