
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbWantedLevelInfo
{
    private readonly System.Collections.Generic.Dictionary<int, demo.WantedLevelInfo> _dataMap;
    private readonly System.Collections.Generic.List<demo.WantedLevelInfo> _dataList;
    
    public TbWantedLevelInfo(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.WantedLevelInfo>(count);
        _dataList = new System.Collections.Generic.List<demo.WantedLevelInfo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.WantedLevelInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo.WantedLevelInfo.DeserializeWantedLevelInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.WantedLevelInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.WantedLevelInfo> DataList => _dataList;

    public demo.WantedLevelInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.WantedLevelInfo Get(int key) => _dataMap[key];
    public demo.WantedLevelInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

