
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class TbWorldMapGlobal
{

     private readonly demo.WorldMapGlobal _data;

     public demo.WorldMapGlobal Data => _data;

    public TbWorldMapGlobal(JSONNode _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_buf[0].IsObject) { throw new SerializationException(); }  _data = global::cfg.demo.WorldMapGlobal.DeserializeWorldMapGlobal(_buf[0]);  }
    }


    /// <summary>
    /// 未知地图是否可开
    /// </summary>
     public bool AllowOpenWhenAreaUnknown => _data.AllowOpenWhenAreaUnknown;
    /// <summary>
    /// fallback 底图
    /// </summary>
     public string FallbackBigMapTextureResourcePath => _data.FallbackBigMapTextureResourcePath;
    /// <summary>
    /// 边界
    /// </summary>
     public float FallbackWorldMinX => _data.FallbackWorldMinX;
     public float FallbackWorldMinY => _data.FallbackWorldMinY;
     public float FallbackWorldMaxX => _data.FallbackWorldMaxX;
     public float FallbackWorldMaxY => _data.FallbackWorldMaxY;
    /// <summary>
    /// 逗号分隔
    /// </summary>
     public string GlobalNpcBossLandmarkCfgIds => _data.GlobalNpcBossLandmarkCfgIds;
    /// <summary>
    /// 逗号分隔
    /// </summary>
     public string GlobalInteractLandmarkCfgIds => _data.GlobalInteractLandmarkCfgIds;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

