
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class TiaoJingConcentrationLevel : Luban.BeanBase
{
    public TiaoJingConcentrationLevel(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["need_amount"].IsNumber) { throw new SerializationException(); }  NeedAmount = _buf["need_amount"]; }
        { if(!_buf["cost_per_sec"].IsNumber) { throw new SerializationException(); }  CostPerSec = _buf["cost_per_sec"]; }
    }

    public static TiaoJingConcentrationLevel DeserializeTiaoJingConcentrationLevel(JSONNode _buf)
    {
        return new demo.TiaoJingConcentrationLevel(_buf);
    }

    /// <summary>
    /// level
    /// </summary>
    public int Level;
    /// <summary>
    /// need_amount
    /// </summary>
    public long NeedAmount;
    /// <summary>
    /// cost_per_sec
    /// </summary>
    public float CostPerSec;
   
    public const int __ID__ = 311604413;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "needAmount:" + NeedAmount + ","
        + "costPerSec:" + CostPerSec + ","
        + "}";
    }
}
}

