
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class TownWalkerPopulation : Luban.BeanBase
{
    public TownWalkerPopulation(JSONNode _buf) 
    {
        { if(!_buf["logic_area_id"].IsString) { throw new SerializationException(); }  LogicAreaId = _buf["logic_area_id"]; }
        { if(!_buf["stage"].IsNumber) { throw new SerializationException(); }  Stage = _buf["stage"]; }
        { if(!_buf["min_prosperity"].IsNumber) { throw new SerializationException(); }  MinProsperity = _buf["min_prosperity"]; }
        { if(!_buf["walker_limit"].IsNumber) { throw new SerializationException(); }  WalkerLimit = _buf["walker_limit"]; }
        { if(!_buf["walker_spawn_interval"].IsNumber) { throw new SerializationException(); }  WalkerSpawnInterval = _buf["walker_spawn_interval"]; }
        { if(!_buf["walker_normal_weight"].IsNumber) { throw new SerializationException(); }  WalkerNormalWeight = _buf["walker_normal_weight"]; }
        { if(!_buf["walker_advanced_weight"].IsNumber) { throw new SerializationException(); }  WalkerAdvancedWeight = _buf["walker_advanced_weight"]; }
        { if(!_buf["walker_elite_weight"].IsNumber) { throw new SerializationException(); }  WalkerEliteWeight = _buf["walker_elite_weight"]; }
        { if(!_buf["resident_idle_limit"].IsNumber) { throw new SerializationException(); }  ResidentIdleLimit = _buf["resident_idle_limit"]; }
        { if(!_buf["resident_idle_spawn_interval"].IsNumber) { throw new SerializationException(); }  ResidentIdleSpawnInterval = _buf["resident_idle_spawn_interval"]; }
        { if(!_buf["resident_idle_cfg_id"].IsString) { throw new SerializationException(); }  ResidentIdleCfgId = _buf["resident_idle_cfg_id"]; }
    }

    public static TownWalkerPopulation DeserializeTownWalkerPopulation(JSONNode _buf)
    {
        return new demo.TownWalkerPopulation(_buf);
    }

    /// <summary>
    /// 逻辑区域id
    /// </summary>
    public string LogicAreaId;
    /// <summary>
    /// 阶段
    /// </summary>
    public int Stage;
    /// <summary>
    /// 最低繁荣度
    /// </summary>
    public int MinProsperity;
    /// <summary>
    /// 路人数量上限
    /// </summary>
    public int WalkerLimit;
    /// <summary>
    /// 刷新间隔
    /// </summary>
    public float WalkerSpawnInterval;
    /// <summary>
    /// 普通权重
    /// </summary>
    public int WalkerNormalWeight;
    /// <summary>
    /// 高级权重
    /// </summary>
    public int WalkerAdvancedWeight;
    /// <summary>
    /// 精英权重
    /// </summary>
    public int WalkerEliteWeight;
    /// <summary>
    /// 固定村民数量上限
    /// </summary>
    public int ResidentIdleLimit;
    /// <summary>
    /// 固定村民刷新间隔
    /// </summary>
    public float ResidentIdleSpawnInterval;
    /// <summary>
    /// 固定村民单位配置
    /// </summary>
    public string ResidentIdleCfgId;
   
    public const int __ID__ = 2030505504;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "logicAreaId:" + LogicAreaId + ","
        + "stage:" + Stage + ","
        + "minProsperity:" + MinProsperity + ","
        + "walkerLimit:" + WalkerLimit + ","
        + "walkerSpawnInterval:" + WalkerSpawnInterval + ","
        + "walkerNormalWeight:" + WalkerNormalWeight + ","
        + "walkerAdvancedWeight:" + WalkerAdvancedWeight + ","
        + "walkerEliteWeight:" + WalkerEliteWeight + ","
        + "residentIdleLimit:" + ResidentIdleLimit + ","
        + "residentIdleSpawnInterval:" + ResidentIdleSpawnInterval + ","
        + "residentIdleCfgId:" + ResidentIdleCfgId + ","
        + "}";
    }
}
}

