
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class TrapSpec : Luban.BeanBase
{
    public TrapSpec(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["trigger_radius"].IsNumber) { throw new SerializationException(); }  TriggerRadius = _buf["trigger_radius"]; }
        { if(!_buf["camp_filter"].IsNumber) { throw new SerializationException(); }  CampFilter = _buf["camp_filter"]; }
        { if(!_buf["only_player"].IsBoolean) { throw new SerializationException(); }  OnlyPlayer = _buf["only_player"]; }
        { if(!_buf["post_trigger"].IsNumber) { throw new SerializationException(); }  PostTrigger = _buf["post_trigger"]; }
        { if(!_buf["sleep_duration"].IsNumber) { throw new SerializationException(); }  SleepDuration = _buf["sleep_duration"]; }
        { var __json0 = _buf["trigger_effects"]; if(!__json0.IsArray) { throw new SerializationException(); } TriggerEffects = new System.Collections.Generic.List<demo.TrapTriggerEffect>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { demo.TrapTriggerEffect __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.demo.TrapTriggerEffect.DeserializeTrapTriggerEffect(__e0);  }  TriggerEffects.Add(__v0); }   }
    }

    public static TrapSpec DeserializeTrapSpec(JSONNode _buf)
    {
        return new demo.TrapSpec(_buf);
    }

    /// <summary>
    /// 与 Trap CfgId 一致
    /// </summary>
    public string Id;
    /// <summary>
    /// 触发半径
    /// </summary>
    public float TriggerRadius;
    /// <summary>
    /// ECampFilterType 整型
    /// </summary>
    public int CampFilter;
    /// <summary>
    /// 仅玩家
    /// </summary>
    public bool OnlyPlayer;
    /// <summary>
    /// ETrapPostTrigger 整型
    /// </summary>
    public int PostTrigger;
    /// <summary>
    /// 触发后休眠秒数
    /// </summary>
    public float SleepDuration;
    /// <summary>
    /// 效果列表；每条 kind,buff_id,layer,duration,target_type；多条分号分隔
    /// </summary>
    public System.Collections.Generic.List<demo.TrapTriggerEffect> TriggerEffects;
   
    public const int __ID__ = 2047461459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in TriggerEffects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "triggerRadius:" + TriggerRadius + ","
        + "campFilter:" + CampFilter + ","
        + "onlyPlayer:" + OnlyPlayer + ","
        + "postTrigger:" + PostTrigger + ","
        + "sleepDuration:" + SleepDuration + ","
        + "triggerEffects:" + Luban.StringUtil.CollectionToString(TriggerEffects) + ","
        + "}";
    }
}
}

