
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class UnitNpcAttr : Luban.BeanBase
{
    public UnitNpcAttr(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["move_speed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["move_speed"]; }
    }

    public static UnitNpcAttr DeserializeUnitNpcAttr(JSONNode _buf)
    {
        return new demo.UnitNpcAttr(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id;
    /// <summary>
    /// 生命
    /// </summary>
    public int Hp;
    /// <summary>
    /// 移速
    /// </summary>
    public float MoveSpeed;
   
    public const int __ID__ = -1255865693;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "hp:" + Hp + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "}";
    }
}
}

