
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class WantedGuardSpawnTier : Luban.BeanBase
{
    public WantedGuardSpawnTier(JSONNode _buf) 
    {
        { if(!_buf["tier_id"].IsNumber) { throw new SerializationException(); }  TierId = _buf["tier_id"]; }
        { if(!_buf["min_wanted_star_level"].IsNumber) { throw new SerializationException(); }  MinWantedStarLevel = _buf["min_wanted_star_level"]; }
        { if(!_buf["guard_count"].IsNumber) { throw new SerializationException(); }  GuardCount = _buf["guard_count"]; }
        { if(!_buf["npc_cfg_id"].IsString) { throw new SerializationException(); }  NpcCfgId = _buf["npc_cfg_id"]; }
        { if(!_buf["spawn_radius_min"].IsNumber) { throw new SerializationException(); }  SpawnRadiusMin = _buf["spawn_radius_min"]; }
        { if(!_buf["spawn_radius_max"].IsNumber) { throw new SerializationException(); }  SpawnRadiusMax = _buf["spawn_radius_max"]; }
        { if(!_buf["cull_distance"].IsNumber) { throw new SerializationException(); }  CullDistance = _buf["cull_distance"]; }
    }

    public static WantedGuardSpawnTier DeserializeWantedGuardSpawnTier(JSONNode _buf)
    {
        return new demo.WantedGuardSpawnTier(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int TierId;
    /// <summary>
    /// 通缉星级(见 wanted_level_info)
    /// </summary>
    public int MinWantedStarLevel;
    /// <summary>
    /// 守卫数
    /// </summary>
    public int GuardCount;
    /// <summary>
    /// NPC
    /// </summary>
    public string NpcCfgId;
    /// <summary>
    /// 环内径
    /// </summary>
    public float SpawnRadiusMin;
    /// <summary>
    /// 环外径
    /// </summary>
    public float SpawnRadiusMax;
    /// <summary>
    /// 超出距离销毁
    /// </summary>
    public float CullDistance;
   
    public const int __ID__ = -1409456462;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "tierId:" + TierId + ","
        + "minWantedStarLevel:" + MinWantedStarLevel + ","
        + "guardCount:" + GuardCount + ","
        + "npcCfgId:" + NpcCfgId + ","
        + "spawnRadiusMin:" + SpawnRadiusMin + ","
        + "spawnRadiusMax:" + SpawnRadiusMax + ","
        + "cullDistance:" + CullDistance + ","
        + "}";
    }
}
}

