
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class WantedBehaveInfo : Luban.BeanBase
{
    public WantedBehaveInfo(JSONNode _buf) 
    {
        { if(!_buf["BehaveType"].IsNumber) { throw new SerializationException(); }  BehaveType = (demo.EWantedBehaveType)_buf["BehaveType"].AsInt; }
        { if(!_buf["add_wanted"].IsNumber) { throw new SerializationException(); }  AddWanted = _buf["add_wanted"]; }
        { if(!_buf["trigger_range"].IsNumber) { throw new SerializationException(); }  TriggerRange = _buf["trigger_range"]; }
    }

    public static WantedBehaveInfo DeserializeWantedBehaveInfo(JSONNode _buf)
    {
        return new demo.WantedBehaveInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public demo.EWantedBehaveType BehaveType;
    /// <summary>
    /// 增加通缉
    /// </summary>
    public int AddWanted;
    /// <summary>
    /// 触发视线
    /// </summary>
    public float TriggerRange;
   
    public const int __ID__ = 695006291;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BehaveType:" + BehaveType + ","
        + "addWanted:" + AddWanted + ","
        + "triggerRange:" + TriggerRange + ","
        + "}";
    }
}
}

