
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class WantedBehaveInfo : Luban.BeanBase
{
    public WantedBehaveInfo(JSONNode _buf) 
    {
        { if(!_buf["BehaveType"].IsNumber) { throw new SerializationException(); }  BehaveType = (demo.EWantedBehaveType)_buf["BehaveType"].AsInt; }
        { if(!_buf["add_wanted"].IsNumber) { throw new SerializationException(); }  AddWanted = _buf["add_wanted"]; }
        { if(!_buf["trigger_range"].IsNumber) { throw new SerializationException(); }  TriggerRange = _buf["trigger_range"]; }
        { if(!_buf["max_add_once"].IsNumber) { throw new SerializationException(); }  MaxAddOnce = _buf["max_add_once"]; }
    }

    public static WantedBehaveInfo DeserializeWantedBehaveInfo(JSONNode _buf)
    {
        return new demo.WantedBehaveInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public demo.EWantedBehaveType BehaveType;
    /// <summary>
    /// 每次基础增量(传入 AddWantedVal 的逻辑量，会再&#215;1000)
    /// </summary>
    public int AddWanted;
    /// <summary>
    /// NPC 感知/视线相关占位
    /// </summary>
    public float TriggerRange;
    /// <summary>
    /// 单次叠加封顶(逻辑量，0=不限制)与 add_wanted 取较小
    /// </summary>
    public int MaxAddOnce;
   
    public const int __ID__ = 695006291;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BehaveType:" + BehaveType + ","
        + "addWanted:" + AddWanted + ","
        + "triggerRange:" + TriggerRange + ","
        + "maxAddOnce:" + MaxAddOnce + ","
        + "}";
    }
}
}

