
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class WorldMapRoomRule : Luban.BeanBase
{
    public WorldMapRoomRule(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["area_id"].IsString) { throw new SerializationException(); }  AreaId = _buf["area_id"]; }
        { if(!_buf["room_id"].IsString) { throw new SerializationException(); }  RoomId = _buf["room_id"]; }
        { if(!_buf["rule_priority"].IsNumber) { throw new SerializationException(); }  RulePriority = _buf["rule_priority"]; }
        { if(!_buf["behavior"].IsNumber) { throw new SerializationException(); }  Behavior = (demo.EWorldMapRoomBehavior)_buf["behavior"].AsInt; }
        { if(!_buf["alternate_map_texture_resource_path"].IsString) { throw new SerializationException(); }  AlternateMapTextureResourcePath = _buf["alternate_map_texture_resource_path"]; }
        { if(!_buf["use_separate_bounds"].IsBoolean) { throw new SerializationException(); }  UseSeparateBounds = _buf["use_separate_bounds"]; }
        { if(!_buf["alternate_world_min_x"].IsNumber) { throw new SerializationException(); }  AlternateWorldMinX = _buf["alternate_world_min_x"]; }
        { if(!_buf["alternate_world_min_y"].IsNumber) { throw new SerializationException(); }  AlternateWorldMinY = _buf["alternate_world_min_y"]; }
        { if(!_buf["alternate_world_max_x"].IsNumber) { throw new SerializationException(); }  AlternateWorldMaxX = _buf["alternate_world_max_x"]; }
        { if(!_buf["alternate_world_max_y"].IsNumber) { throw new SerializationException(); }  AlternateWorldMaxY = _buf["alternate_world_max_y"]; }
    }

    public static WorldMapRoomRule DeserializeWorldMapRoomRule(JSONNode _buf)
    {
        return new demo.WorldMapRoomRule(_buf);
    }

    /// <summary>
    /// 规则 id
    /// </summary>
    public int Id;
    /// <summary>
    /// 所属区域
    /// </summary>
    public string AreaId;
    /// <summary>
    /// 房间 id，* 为默认
    /// </summary>
    public string RoomId;
    /// <summary>
    /// 同区多条时大者优先
    /// </summary>
    public int RulePriority;
    /// <summary>
    /// 行为
    /// </summary>
    public demo.EWorldMapRoomBehavior Behavior;
    /// <summary>
    /// 换图时纹理路径
    /// </summary>
    public string AlternateMapTextureResourcePath;
    /// <summary>
    /// 是否用独立边界
    /// </summary>
    public bool UseSeparateBounds;
    /// <summary>
    /// alt min/max
    /// </summary>
    public float AlternateWorldMinX;
    public float AlternateWorldMinY;
    public float AlternateWorldMaxX;
    public float AlternateWorldMaxY;
   
    public const int __ID__ = -1641816628;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "areaId:" + AreaId + ","
        + "roomId:" + RoomId + ","
        + "rulePriority:" + RulePriority + ","
        + "behavior:" + Behavior + ","
        + "alternateMapTextureResourcePath:" + AlternateMapTextureResourcePath + ","
        + "useSeparateBounds:" + UseSeparateBounds + ","
        + "alternateWorldMinX:" + AlternateWorldMinX + ","
        + "alternateWorldMinY:" + AlternateWorldMinY + ","
        + "alternateWorldMaxX:" + AlternateWorldMaxX + ","
        + "alternateWorldMaxY:" + AlternateWorldMaxY + ","
        + "}";
    }
}
}

