
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
[System.Serializable]
public sealed partial class WorldMapGlobal : Luban.BeanBase
{
    public WorldMapGlobal(JSONNode _buf) 
    {
        { if(!_buf["allow_open_when_area_unknown"].IsBoolean) { throw new SerializationException(); }  AllowOpenWhenAreaUnknown = _buf["allow_open_when_area_unknown"]; }
        { if(!_buf["fallback_big_map_texture_resource_path"].IsString) { throw new SerializationException(); }  FallbackBigMapTextureResourcePath = _buf["fallback_big_map_texture_resource_path"]; }
        { if(!_buf["fallback_world_min_x"].IsNumber) { throw new SerializationException(); }  FallbackWorldMinX = _buf["fallback_world_min_x"]; }
        { if(!_buf["fallback_world_min_y"].IsNumber) { throw new SerializationException(); }  FallbackWorldMinY = _buf["fallback_world_min_y"]; }
        { if(!_buf["fallback_world_max_x"].IsNumber) { throw new SerializationException(); }  FallbackWorldMaxX = _buf["fallback_world_max_x"]; }
        { if(!_buf["fallback_world_max_y"].IsNumber) { throw new SerializationException(); }  FallbackWorldMaxY = _buf["fallback_world_max_y"]; }
        { if(!_buf["global_npc_boss_landmark_cfg_ids"].IsString) { throw new SerializationException(); }  GlobalNpcBossLandmarkCfgIds = _buf["global_npc_boss_landmark_cfg_ids"]; }
        { if(!_buf["global_interact_landmark_cfg_ids"].IsString) { throw new SerializationException(); }  GlobalInteractLandmarkCfgIds = _buf["global_interact_landmark_cfg_ids"]; }
    }

    public static WorldMapGlobal DeserializeWorldMapGlobal(JSONNode _buf)
    {
        return new demo.WorldMapGlobal(_buf);
    }

    /// <summary>
    /// 未知地图是否可开
    /// </summary>
    public bool AllowOpenWhenAreaUnknown;
    /// <summary>
    /// fallback 底图
    /// </summary>
    public string FallbackBigMapTextureResourcePath;
    /// <summary>
    /// 边界
    /// </summary>
    public float FallbackWorldMinX;
    public float FallbackWorldMinY;
    public float FallbackWorldMaxX;
    public float FallbackWorldMaxY;
    /// <summary>
    /// 逗号分隔
    /// </summary>
    public string GlobalNpcBossLandmarkCfgIds;
    /// <summary>
    /// 逗号分隔
    /// </summary>
    public string GlobalInteractLandmarkCfgIds;
   
    public const int __ID__ = -1602089928;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "allowOpenWhenAreaUnknown:" + AllowOpenWhenAreaUnknown + ","
        + "fallbackBigMapTextureResourcePath:" + FallbackBigMapTextureResourcePath + ","
        + "fallbackWorldMinX:" + FallbackWorldMinX + ","
        + "fallbackWorldMinY:" + FallbackWorldMinY + ","
        + "fallbackWorldMaxX:" + FallbackWorldMaxX + ","
        + "fallbackWorldMaxY:" + FallbackWorldMaxY + ","
        + "globalNpcBossLandmarkCfgIds:" + GlobalNpcBossLandmarkCfgIds + ","
        + "globalInteractLandmarkCfgIds:" + GlobalInteractLandmarkCfgIds + ","
        + "}";
    }
}
}

